Repository red-hat-data-services/ods-ci, pull requests merged in 2022-09, with the labels that each got.

#533 Adapt different TCs to work with KFNBC and without old config maps
  tests/Resources/ODS.robot
  tests/Resources/Page/OCPDashboard/UserManagement/Groups.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Resources/Page/ODH/JupyterHub/LoginJupyterHub.robot
  tests/Tests/100__deploy/110__auth_providers_and_rbac/110__rbac.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/500__jupyterhub/jupyterhub-user-access.robot
Labels: verified, enhancements

#503 Update ODS-488 to remove perceptilabs check for Jupyter (instead of JupyterHub)
  tests/Resources/Files/AppsInfoDictionary.json
  tests/Resources/Files/AppsInfoDictionary_latest.json
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements

#537 Fix wrong label selector in Smoke
  tests/Tests/500__jupyterhub/test-minimal-image.robot
Labels: enhancements

#532 Add TC's for Admin UI
  tests/Resources/Page/ODH/ODHDashboard/ODHAdminUI.robot
  tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
Labels: verified, new test, enhancements

#534 Update monitoring tests for kubeflow (Tier1, Tier2)
  tests/Resources/Common.robot
  tests/Resources/ODS.robot
  tests/Tests/100__deploy/130__operators/130__rhods_operator/132__traefik-proxy_restart_verification.robot
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
Labels: needs testing, verified, enhancements, :warning: high priority review

#536 Fix some failing smoke tests due to JH to Jupyter migration
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, enhancements

#540 fix-minor-issue size=Default to size=Small
  tests/Tests/500__jupyterhub/minimal-cuda-test.robot
  tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
Labels: enhancements

#544 Run black formatter only on python file
  .github/workflows/black.yaml
Labels: enhancements

#545 Update fix spawner status keyword for KFNBC
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: enhancements

#546 Fix spawner typos
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: enhancements

#547 Update expected CUDA version to 11.7
  tests/Tests/500__jupyterhub/minimal-cuda-test.robot
  tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
Labels: verified, enhancements

#538 Black doc
  docs/check-code-style.md
  requirements-dev.txt
Labels: documentation

#487 added support to check rhods operator
  tests/Tests/700__sandbox/701__performance_sandbox.robot
Labels: verified, enhancements

#543 Update culler test suite for KFNBC
  libs/Helpers.py
  tests/Resources/Page/OCPDashboard/Pods/Pods.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Resources/Page/ODH/JupyterHub/jupyter-helper.py
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/400__ods_dashboard/413__ods_dashboard_settings_pod_tolerations.robot
  tests/Tests/800__culler/culler.robot
Labels: verified, enhancements

#550 Fix metrics tests for kubeflow
  tests/Resources/Page/OCPDashboard/Monitoring/Metrics.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  tests/Tests/500__jupyterhub/test-jupyterhub-api-telemetry.robot
Labels: verified, enhancements

#548 Add support to create osd cluster on gcp
  utils/scripts/ocm/ocm.py
  utils/scripts/ocm/templates/create_gcp_sa_json.jinja
Labels: verified, utils

#549 Workaround for modal not appearing during spawn
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: enhancements

#551 Added changes to PVC related tc to support KFNBC
  setup.py
  tests/Resources/Page/OCPDashboard/ConfigMaps/ConfigMaps.robot
  tests/Resources/Page/ODH/JupyterHub/PVCChange.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/400__ods_dashboard/411__ods_dashboard_settings_pvc_size.robot
Labels: verified, enhancements

#552 Added rhods version to be available globally
  tests/Resources/Page/OCPDashboard/InstalledOperators/InstalledOperators.robot
  tests/Resources/RHOSi.resource
Labels: enhancements

#557 Use shell script for configuring aws
  utils/scripts/openshift/openshift.py
Labels: verified

#553 Add tests for new kubeflow alerts
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
Labels: verified, new test

#558 Fix PSI related TC
  tests/Tests/100__deploy/100__installation/108__jupyterhub.robot
  tests/Tests/100__deploy/100__installation/109__operator.robot
Labels: verified, enhancements

#562 Add Feature AWS Provisioning Beta
  infrastructure_configuration.yaml.example
  tasks/Resources/Provisioning/Hive/AWS/aws-cluster.yaml
  tasks/Resources/Provisioning/Hive/AWS/claim.yaml
  tasks/Resources/Provisioning/Hive/AWS/oc-provision.robot
  tasks/Resources/Provisioning/Hive/AWS/provision-gpu.sh
  tasks/Tasks/provision_aws_cluster.robot
Labels: verified, new test

#560 Update ODS-469 to use Notebook CR for last spawn details
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-notebook.robot
Labels: enhancements

#564 Fix typo in spawn keyword
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: enhancements

#568 Add namespace parameter to oc call
  tests/Tests/500__jupyterhub/test-jupyterlab-notebook.robot
Labels: enhancements

#563 Fix Anaconda and Application Switcher test cases based on results from automated runs
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
Labels: enhancements

#556 Add tests for testing API based on user permission
  tests/Resources/Common.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboardAPI.resource
  tests/Resources/RHOSi.resource
  tests/Tests/400__ods_dashboard/414__ods_dashboard_api.robot
Labels: verified, new test

#574 Added new TCs for Notebook Controller Routes and Jupyter Notebook
  tests/Tests/500__jupyterhub/test-jupyterlab-notebook.robot
Labels: verified, new test

#572 Add product bug and and remove flaky test from operator test
  tests/Tests/100__deploy/130__operators/130__rhods_operator/130__rhods_operator.robot
Labels: verified, enhancements

#573 Fix bug in keyword "Verify Operator Pod Status"
  tests/Resources/Page/OCPDashboard/Pods/Pods.robot
Labels: verified, enhancements

#577 Fix qaprodauth url
  tests/Tests/100__deploy/100__installation/101__installation.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: enhancements

#561 Update performance tests for kfnbc
  tests/Tests/700__sandbox/701__performance_sandbox.robot
Labels: verified, enhancements

#555 Add support to install rhods using the self-managed-installer
  tasks/Resources/RHODS_OLM/install/oc_install.robot
  tasks/Tasks/rhods_olm.robot
Labels: verified, enhancements

#570 Add ODS-650 to Anaconda e2e test case
  tests/Resources/Page/OCPDashboard/Builds/Builds.robot
  tests/Resources/Page/ODH/AiApps/Anaconda.resource
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
Labels: verified, enhancements

#576 Verify Clean Up ODS Deployer Post-Migration
  tests/Tests/100__deploy/100__installation/109__operator.robot
Labels: verified, new test, :warning: high priority review

#575 Fix failures in Dashboard API testing
  tests/Tests/400__ods_dashboard/414__ods_dashboard_api.robot
Labels: verified, enhancements

#578 Fix test on Dashboard deployment increasing expected replicas to 5
  tests/Tests/100__deploy/100__installation/104__dashboard.robot
Labels: needs testing, enhancements

#579 Cluster config
  utils/scripts/ocm/ocm.py
  utils/scripts/openshift/openshift.py
Labels: verified

#580 Added support for new uninstaller
  tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: verified, enhancements
