Repository red-hat-data-services/ods-ci, pull requests merged in 2022-05, with the labels that each got.

#338 add Tier tag to ODS-1226
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: enhancements

#317 Custom Notebooks test cases and keywords
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/500__jupyterhub/custom-image.robot
Labels: verified, new test, new lib

#334 Replacing load witrh safe_load for yaml lib
  utils/scripts/ocm/ocm.py
  utils/scripts/polarion/xunit_add_properties.py
Labels: verified, enhancements, :warning: high priority review

#342 Close all browsers before starting minimal CUDA test
  tests/Tests/500__jupyterhub/minimal-cuda-test.robot
Labels: enhancements

#341 Modify update_notification_email_address keyword so that it doesn't stop test execution on errors
  libs/Helpers.py
  utils/scripts/ocm/ocm.py
Labels: verified, enhancements

#346 Few minor Changes in Readme.md
  README.md
Labels: documentation

#349 Add support to provide notification email during rhods installation
  utils/scripts/ocm/ocm.py
  utils/scripts/ocm/templates/install_addon_gpu.jinja
  utils/scripts/ocm/templates/install_addon_rhods.jinja
Labels: verified, utils, :warning: high priority review

#329 remove explicit secret creation from RHOAM Interop test
  libs/Helpers.py
  tests/Tests/600__ai_apps/640__rhoam/640__rhoam_installation.robot
  utils/scripts/ocm/ocm.py
  utils/scripts/ocm/templates/dms.yaml
  utils/scripts/ocm/templates/smpt.yaml
Labels: verified, enhancements

#350 Fix CUDA suite setup failure
  tests/Tests/500__jupyterhub/minimal-cuda-test.robot
Labels: enhancements

#347 Add Grafana test to verify if it is shipped and enabled
  tests/Resources/ODS.robot
  tests/Tests/100__deploy/100__installation/103__grafana.robot
Labels: needs testing, new test

#357 Verify that Blackbox exporter is shipped and enabled within RHODS
  tests/Tests/100__deploy/100__installation/106__blackbox_exporter.robot
Labels: verified, new test

#354 Verify Traefik Proxy is deployed in HA
  tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, new test

#362 Anaconda image name change in v1.11
  tests/Resources/Files/AppsInfoDictionary.json
  tests/Resources/Files/AppsInfoDictionary_latest.json
  tests/Resources/Page/ODH/AiApps/Anaconda.resource
  tests/Resources/Page/ODH/ODHDashboard/AppsInfoDictionary.json
  tests/Resources/Page/ODH/ODHDashboard/AppsInfoDictionary_latest.json
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
Labels: verified, enhancements, :warning: high priority review

#361 Changes in ods-1227(verify alert severity)
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
Labels: verified, enhancements, :warning: high priority review

#359 Verify Alert Manager Is Shipped And Enabled Within ODS
  tests/Tests/100__deploy/100__installation/107__alert_manager.robot
Labels: verified, new test

#348 Added Tests to Verify MT-SRE Can Connect To Prometheus , Alert Manager Using OpenShift Port-Forwarding
  tests/Resources/Common.robot
  tests/Resources/ODS.robot
  tests/Resources/Page/OCPDashboard/Monitoring/Grafana.robot
  tests/Resources/Page/ODH/Grafana/Grafana.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/100__deploy/100__installation/103__post_install_monitoring_port_forwarding.robot
  tests/Tests/200__monitor_and_manage/220__grafana/220__test_verify_port_forwarding_grafana.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, new test

#356 Add jupyterhub test tag
  tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, new test

#340 Add Tests to verify Grafana Connected to Prometheus using TLS(ODS-963)
  tests/Resources/ODS.robot
  tests/Resources/Page/ODH/Grafana/Grafana.resource
  tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, new test

#366 email-report changed to False as run_robot_test.sh
  build/README.md
Labels: documentation

#276 Verify pushing project changes to a git repository [ODS-326]
  test-variables.yml.example
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Resources/RHOSi.resource
  tests/Tests/500__jupyterhub/test-jupyterlab-git.robot
Labels: needs testing, new test

#365 verify rhods-dashboard cluster role
  tests/Tests/100__deploy/100__installation/104__dashboard.robot
Labels: verified, new test

#373 Added code to verify the default size
  tests/Resources/Page/ODH/JupyterHub/PVCChange.resource
  tests/Tests/400__ods_dashboard/411__ods_dashboard_settings_pvc_size.robot
Labels: verified, enhancements

#320 Add test to verify JupyterHub leader monitoring using RHODS Prometheus(ODS-689)
  tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
Labels: verified, new test

#374 fix RHOSAK test case after changes in UI
  tests/Resources/Page/HybridCloudConsole/HCCLogin.robot
Labels: verified, enhancements

#377 added pattern to check failed entry
  tests/Tests/100__deploy/130__operators/130__rhods_operator/135__rhods_operator_logs_verification.robot
Labels: verified, enhancements

#372 update ods-ci container to install python3.8 and use RH ubi image
  build/Dockerfile
Labels: verified, enhancements

#378 Update ODS-CI container with new features
  build/README.md
  run_robot_test.sh
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
Labels: verified, enhancements

#314 Calculates avg time taken by server to start
  tests/Tests/500__jupyterhub/test-jupyterlab-time.robot
Labels: verified, new test

#382 Add ods-ci serviceaccount variables to test-variables yaml
  utils/scripts/testconfig/generateTestConfigFile.py
  utils/scripts/testconfig/test-variables.yml
Labels: verified, enhancements, :warning: high priority review

#380 Sec update for ODS-CI
  build/Dockerfile
  run_robot_test.sh
Labels: verified, enhancements

#381 Add keyword to check for npm library installed version in container
  tests/Resources/Common.robot
  tests/Resources/Page/ODH/JupyterHub/HighAvailability.robot
Labels: verified, new test, enhancements

#384 Fix "Verify JupyterHub Deployment" for RHODS < 1.12
  tests/Resources/Page/ODH/JupyterHub/HighAvailability.robot
Labels: enhancements

#379 Add performance test
  tests/Tests/700__sandbox/701__performance_sandbox.robot
Labels: verified, new test

#383 Fix "Usage Data Collection" test. Add keyword "Save Changes In Cluster Settings"
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/400__ods_dashboard/410__ods_dashboard_settings.robot
  tests/Tests/500__jupyterhub/culler.robot
Labels: verified, enhancements, :warning: high priority review

#312 Add test cases for metrics in OpenShift Monitoring: notebook cpu usage, rhods_total_users and rhods_aggregate_availability (RHODS-3288)
  setup.py
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
Labels: needs testing, verified

#385 Fix automation bug in "Verify RHODS operator information" (ODS-644)
  tests/Tests/100__deploy/100__installation/104__dashboard.robot
Labels: verified, :warning: high priority review

#351 Fix configuration of autogeneration of release notes
  .github/release.yml
Labels: enhancements

#387 Fix "Test Metric "Notebook CPU Usage" (ODS-178) when cpu usage is null
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
Labels: verified, enhancements, :warning: high priority review

#388 fix ODS-293 by adding wait for rollout to start
  tests/Resources/Page/OCPDashboard/DeploymentConfigs/DeploymentConfigs.robot
  tests/Resources/Page/ODH/JupyterHub/HighAvailability.robot
Labels: verified, enhancements

#386 Miscelaneous fixes for ods-ci 1.11.0
  tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/100__deploy/130__operators/130__rhods_operator/130__rhods_operator.robot
  tests/Tests/100__deploy/130__operators/130__rhods_operator/132__traefik-proxy_restart_verification.robot
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/400__ods_dashboard/411__ods_dashboard_settings_pvc_size.robot
  tests/Tests/500__jupyterhub/culler.robot
  tests/Tests/500__jupyterhub/plugin-verification.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
Labels: verified, enhancements, :warning: high priority review

#369 Checking for oauth container ODS-355
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, new test
