Repository red-hat-data-services/ods-ci, pull requests merged in 2022-08, with the labels that each got.

#441 Adding memory and cpu resource
  build/ods-ci.pod.yaml
Labels: misc

#491 Add PSI uninstall
  tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  tasks/Tasks/rhods_olm.robot
Labels: verified, new task

#494 added fix for smoke run
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements, :warning: high priority review

#495 chnage default gpu node
  utils/scripts/ocm/ocm.py
Labels: enhancements

#485 Change python code in Pep8 format
  libs/Helpers.py
  setup.py
  tests/Resources/Page/ODH/JupyterHub/jupyter-helper.py
  utils/scripts/Sender/EmailSender.py
  utils/scripts/Sender/Sender.py
  utils/scripts/Sender/send_report.py
  utils/scripts/SplitSuite.py
  utils/scripts/logger.py
  utils/scripts/ocm/ocm.py
  utils/scripts/openshift/openshift.py
  utils/scripts/polarion/createPolarionTestRun.py
  utils/scripts/polarion/polarionUpdater.py
  utils/scripts/polarion/xunit_add_properties.py
  utils/scripts/reportportal/rp_uploader.py
  utils/scripts/terraform/openstack/provision.py
  utils/scripts/testconfig/generateTestConfigFile.py
  utils/scripts/util.py
Labels: verified

#502 Verify cuda buildchain in smoke pipeline
  tests/Resources/Page/OCPDashboard/Builds/Builds.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, enhancements, :warning: high priority review

#492 Add further check on doc links from Dashboard in ODS-327
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, enhancements

#510 Increase build timeout when waiting for CUDA builds
  tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, enhancements

#508 Fix test-versions suite
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Tests/500__jupyterhub/test-versions.robot
Labels: verified, enhancements

#484 Fix ODS-1491 to remove Openvino from dashboard after uninstall
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, enhancements

#515 remove JH
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/100__deploy/100__installation/108__jupyterhub.robot
Labels: :warning: high priority review

#482 Add test to verify app switcher menu in RHODS Dashboard
  tests/Resources/Common.robot
  tests/Resources/ODS.robot
  tests/Resources/Page/HybridCloudConsole/OCM.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, new test

#513 added code to skip the TC since traefik pod is removed
  tests/Tests/100__deploy/130__operators/130__rhods_operator/132__traefik-proxy_restart_verification.robot
Labels: enhancements, :warning: high priority review

#507 Fix ISV tests to work with KFNBC
  build/ods-ci.pod.yaml
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/500__jupyterhub/test-jupyterhub-api-telemetry.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-flask-notebook.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
  tests/Tests/600__ai_apps/650__rhosak/650__rhosak.robot
  tests/Tests/700__sandbox/700__sandbox.robot
Labels: verified, enhancements

#509 Minor Fixes
  build/ods-ci.pod.yaml
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/500__jupyterhub/test-jupyterhub-api-telemetry.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
  tests/Tests/600__ai_apps/650__rhosak/650__rhosak.robot
  tests/Tests/700__sandbox/700__sandbox.robot
Labels: verified, enhancements

#511 Update telemetry configmap and secret for kubeflow. Fix RHOSi Setup when prometheus is not running
  tests/Resources/ODS.robot
  tests/Resources/Page/ODH/Monitoring/Monitoring.resource
  tests/Tests/400__ods_dashboard/410__ods_dashboard_settings.robot
Labels: verified, enhancements

#521 Merge KFNBC branch onto main
  tests/Resources/Common.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Resources/Page/ODH/JupyterHub/LaunchJupyterHub.robot
  tests/Resources/Page/ODH/JupyterHub/jupyter-helper.py
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/100__deploy/100__installation/104__dashboard.robot
  tests/Tests/100__deploy/100__installation/108__jupyterhub.robot
  tests/Tests/100__deploy/100__installation/109__operator.robot
  tests/Tests/100__deploy/110__auth_providers_and_rbac/110__rbac.robot
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/500__jupyterhub/image-iteration.robot
  tests/Tests/500__jupyterhub/jupyterhub-user-access.robot
  tests/Tests/500__jupyterhub/long-running-test-generic-ds.robot
  tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
  tests/Tests/500__jupyterhub/notebook_size_verification.robot
  tests/Tests/500__jupyterhub/odh_jh_global_profile.sh
  tests/Tests/500__jupyterhub/plugin-verification.robot
  tests/Tests/500__jupyterhub/special-user-testing.robot
  tests/Tests/500__jupyterhub/test-filling-pvc.robot
  tests/Tests/500__jupyterhub/test-folder-permissions.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-flask-notebook.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-git-notebook.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-git.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-notebook.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-time.robot
  tests/Tests/500__jupyterhub/test-minimal-image.robot
  tests/Tests/500__jupyterhub/test-s3-cc-fraud.robot
  tests/Tests/500__jupyterhub/test-versions.robot
  tests/Tests/500__jupyterhub/test.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
Labels: do not merge

#531 Add TCs for pod tolerations
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Resources/Page/ODH/JupyterHub/jupyter-helper.py
  tests/Tests/500__jupyterhub/test-pod-affinity.robot
Labels: verified, new test
