Repository red-hat-data-services/ods-ci, pull requests merged in 2022-11, with the labels that each got.

#613 Support for deploying/uninstalling rhods in GCP cluster
  tasks/Resources/RHODS_OLM/install/oc_install.robot
  tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: enhancements

#614 Add pre-req pkgs for a jenkins worker node
  utils/scripts/terraform/openstack/requirements.sh
Labels: verified, misc

#612 Modify aws cluster config to expose variables to user
  tasks/Resources/Provisioning/Hive/AWS/aws-cluster.yaml
Labels: verified, enhancements

#617 Check and verify rhods version and display name
  tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, new test

#619 Add new rules in Dashboard clusterrole
  tests/Tests/100__deploy/100__installation/104__dashboard.robot
Labels: verified, new test, :warning: high priority review

#583 Add tests for Data Science Projects page
  tests/Resources/Common.robot
  tests/Resources/OCP.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, new test

#627 Add fixes for RHOSAK UI testing
  tests/Resources/Page/HybridCloudConsole/HCCLogin.robot
  tests/Resources/Page/HybridCloudConsole/Rhosak.robot
  tests/Tests/600__ai_apps/650__rhosak/650__rhosak.robot
Labels: verified, enhancements

#629 Bugfixes for releasing ods-ci 1.19. Add AutomationBug and ProductBug
  tests/Resources/Page/OCPDashboard/Pods/Pods.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/100__deploy/100__installation/103__grafana.robot
  tests/Tests/100__deploy/100__installation/103__post_install_monitoring_port_forwarding.robot
  tests/Tests/100__deploy/100__installation/104__dashboard.robot
  tests/Tests/100__deploy/100__installation/105__prometheus.robot
  tests/Tests/100__deploy/100__installation/106__blackbox_exporter.robot
  tests/Tests/100__deploy/100__installation/109__operator.robot
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
  tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
  tests/Tests/500__jupyterhub/test.robot
Labels: verified, enhancements, :warning: high priority review

#628 Added support for rhods installtion by olm repo
  rhods_install_configuration.yaml.example
  tasks/Resources/RHODS_OLM/install/install.robot
  tasks/Resources/RHODS_OLM/install/oc_install.robot
  tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
  tasks/Resources/RHODS_OLM/uninstall/oc_uninstall.robot
  tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  tasks/Tasks/rhods_olm.robot
Labels: enhancements

#625 Update tests to account for prebuilt CUDA images
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
  tests/Tests/500__jupyterhub/test-folder-permissions.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-time.robot
  tests/Tests/500__jupyterhub/test-versions.robot
Labels: verified, enhancements
