Repository red-hat-data-services/ods-ci, pull requests merged in 2022-02, with the labels that each got.

#181 created new PR to have both Tcs AIKIT/openvino
  tests/Resources/Page/OCPDashboard/Builds/Builds.robot
  tests/Resources/Page/OCPDashboard/InstalledOperators/InstalledOperators.robot
  tests/Resources/Page/OCPDashboard/OperatorHub/InstallODH.robot
  tests/Resources/Page/OCPDashboard/OperatorHub/OperatorHub.robot
  tests/Resources/Page/ODH/AiApps/AiApps.resource
  tests/Resources/Page/ODH/AiApps/Aikit.robot
  tests/Resources/Page/ODH/AiApps/Openvino.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/600__ai_apps/620__intel_aikit/620__intel_aikit.robot
  tests/Tests/600__ai_apps/660__openvino/660__openvino.robot
Labels: Verified

#190 integrate RHOSAK TC for new UI changes
  tests/Resources/Page/HybridCloudConsole/HCCLogin.robot
  tests/Resources/Page/HybridCloudConsole/Rhosak.robot
  tests/Resources/Page/ODH/AiApps/Rhosak.robot
  tests/Tests/600__ai_apps/650__rhosak/650__rhosak.robot
Labels: Verified

#189 Integrate ACE and RHOSAK TCs with new feature to remove disabled cards from dashboard
  tests/Resources/Page/HybridCloudConsole/Rhosak.robot
  tests/Resources/Page/ODH/AiApps/Rhosak.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
  tests/Tests/600__ai_apps/650__rhosak/650__rhosak.robot
Labels: Verified

#193 request and limit size verification
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Tests/500__jupyterhub/notebook_size_verification.robot
  tests/Tests/500__jupyterhub/odh_jh_global_profile.sh
Labels: Verified

#202 [TestLib] Add keyword to Install import package and Test to verify Pip Changes
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Tests/500__jupyterhub/test-pipChanges-not-permanent.robot
Labels: Verified

#218 Add some polarion IDs and KnownIssues tags to Dashboard/AiApps TCs
  tests/Tests/400_ods_dashboard/400_ods_dashboard.robot
  tests/Tests/500__jupyterhub/plugin-verification.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
  tests/Tests/600__ai_apps/660__openvino/660__openvino.robot
Labels: enhancements

#217 Fix for spawner failures in 1.7 automated runs
  tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
Labels: verified, enhancements

#220 Remove Anaconda Teardown for Smoke TCs + fix compatibility issue with OCP4.10
  tests/Resources/Page/OCPDashboard/Pods/Pods.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
Labels: verified, enhancements
