Repository red-hat-data-services/ods-ci, pull requests merged in 2022-07, with the labels that each got.

#426 Dockerfile: expose utils/scripts/testconfig/test-variables.yml as test-variables.yml.model
  build/Dockerfile
Labels: misc

#442 Add gpu details for ods 488
  build/ods-ci.pod.yaml
  tests/Resources/Files/AppsInfoDictionary.json
  tests/Resources/Files/AppsInfoDictionary_latest.json
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements

#445 Add header to GET request
  tests/Resources/Common.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
Labels: verified, enhancements

#447 Update addon ID for GPU addon
  utils/scripts/ocm/ocm.py
Labels: verified, enhancements

#448 Change nfd operator name
  tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, enhancements

#443 Add test to check if Intel images are pinned to a numeric version
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Tests/600__ai_apps/620__intel_aikit/620__intel_aikit.robot
  tests/Tests/600__ai_apps/660__openvino/660__openvino.robot
Labels: verified, new test

#450 Add new tests to verify alert RHODS JupyterHub Probe Success Burn Rate
  tests/Resources/ODS.robot
  tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
Labels: verified, new test, :warning: high priority review

#451 Add test to Verify Culler Settings are not overwritten [RHODS-4336]
  tests/Tests/800__culler/culler.robot
Labels: verified, new test

#453 Slim down Sanity moving some tests to Tier2 (execution time > 15 mins)
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/500__jupyterhub/image-iteration.robot
  tests/Tests/500__jupyterhub/long-running-test-generic-ds.robot
  tests/Tests/500__jupyterhub/notebook_size_verification.robot
  tests/Tests/800__culler/culler.robot
Labels: verified, enhancements

#446 Add TC to Verify external links in Quick Starts are not broken
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
Labels: needs testing, new test

#455 moving PVC size verification TCs out of smoke
  tests/Tests/400__ods_dashboard/411__ods_dashboard_settings_pvc_size.robot
Labels: misc

#456 Fix test "Verify That MT-SRE Are Not Paged For Alerts In Clusters Used For Development Or Testing" (ODS-1058)
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
Labels: verified, enhancements

#457 Spawn Notebook With Arguments: fail if the retry count is exhausted
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: enhancements

#459 Fix test checking Active_Users metrics not to skip when active_users > 0
  tests/Resources/Page/OCPDashboard/Monitoring/Metrics.robot
  tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
Labels: verified, enhancements

#458 [Test] User should not see No Components Found in RHODS Dashboard
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/100__deploy/100__installation/bad_subscription.yaml
Labels: needs testing, new test

#461 Script to create openshift cluster on aws using openshift-install
  setup.py
  utils/scripts/openshift/openshift.py
Labels: verified, utils

#463 Move ISVs test cases from Sanity to Tier2
  tests/Tests/600__ai_apps/650__rhosak/650__rhosak.robot
  tests/Tests/600__ai_apps/680__starburst/680__starburst.robot
Labels: enhancements

#465 Check if rhods dashborad pods doesn't restart
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, new test

#466 Fix RHOSAK teardown
  tests/Resources/Page/HybridCloudConsole/Rhosak.robot
Labels: verified, enhancements

#469 Spawn Notebook With Arguments: initialize ${spawn_fail} variable
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: misc

#472 Spawn Notebook With Arguments: correctly initialize ${spawn_fail} variable
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: misc

#470 Add tensorboard test for tensorflow/pytorch images
  tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
Labels: verified, new test

#444 Check aggregate availability in "RHOSi Setup" and "RHOSi Teardown"
  tests/Resources/Page/ODH/Monitoring/Monitoring.resource
  tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  tests/Resources/RHOSi.resource
  tests/Tests/100__deploy/100__installation/101__installation.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/100__deploy/100__installation/103__grafana.robot
  tests/Tests/100__deploy/100__installation/103__post_install_monitoring_port_forwarding.robot
  tests/Tests/100__deploy/100__installation/104__dashboard.robot
  tests/Tests/100__deploy/100__installation/105__prometheus.robot
  tests/Tests/100__deploy/100__installation/106__blackbox_exporter.robot
  tests/Tests/100__deploy/100__installation/107__alert_manager.robot
  tests/Tests/100__deploy/100__installation/108__jupyterhub.robot
  tests/Tests/100__deploy/100__installation/109__operator.robot
  tests/Tests/100__deploy/110__auth_providers_and_rbac/110__rbac.robot
  tests/Tests/100__deploy/130__operators/130__rhods_operator/130__rhods_operator.robot
  tests/Tests/100__deploy/130__operators/130__rhods_operator/132__traefik-proxy_restart_verification.robot
  tests/Tests/100__deploy/130__operators/130__rhods_operator/135__rhods_operator_logs_verification.robot
  tests/Tests/100__deploy/130__operators/130__rhods_operator/138__rhods_operator_oom_kill_verification.robot
  tests/Tests/100__deploy/130__operators/130__rhods_operator/139__rhods_kfdef_event.robot
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
  tests/Tests/200__monitor_and_manage/200__metrics/204__check_pager_duty.robot
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/400__ods_dashboard/410__ods_dashboard_settings.robot
  tests/Tests/400__ods_dashboard/411__ods_dashboard_settings_pvc_size.robot
  tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
Labels: verified, enhancements

#468 Fix service account token fetching in ODS-CI for compatibility issue with OCP 4.11
  run_robot_test.sh
Labels: verified, enhancements

#467 Fix compatibility issue with OSD 4.11 in installing ISV from UI
  tests/Resources/Page/OCPDashboard/InstalledOperators/InstalledOperators.robot
  tests/Resources/Page/OCPDashboard/OperatorHub/OperatorHub.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/600__ai_apps/620__intel_aikit/620__intel_aikit.robot
  tests/Tests/600__ai_apps/660__openvino/660__openvino.robot
  tests/Tests/600__ai_apps/670__pachyderm/670__pachyderm.robot
Labels: verified, enhancements

#475 Verify rhods_aggregated_availability Detects Downtime In Jupyterhub And Dashboard
  tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  tests/Tests/900__high_availability/900__openshift/900__openshift.robot
Labels: verified, new test

#474 Added support to install rhods on PSI with git repo
  tasks/Resources/RHODS_OLM/install/install.robot
  tasks/Resources/RHODS_OLM/install/oc_install.robot
  tasks/Tasks/rhods_olm.robot
Labels: verified, utils
