Repository red-hat-data-services/ods-ci, pull requests merged in 2022-06, with the labels that each got.

#360 Verify CPU And Memory Requests And Limits
  tests/Resources/ODS.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, new test

#393 Update tags for nvcc TC
  tests/Tests/500__jupyterhub/minimal-cuda-test.robot
Labels: enhancements

#322 Add Test To Verify If Pachyderm Pipeline Can Be Created Using Jupyterlab
  tests/Resources/Page/OCPDashboard/InstalledOperators/InstalledOperators.robot
  tests/Resources/Page/ODH/AiApps/Pachyderm.robot
  tests/Tests/600__ai_apps/670__pachyderm/670__pachyderm.robot
Labels: verified, enhancements

#371 Add func in ocm.py to Automated Trigger smoke sanity with candidate version
  utils/scripts/ocm/ocm.py
  utils/scripts/util.py
Labels: needs testing

#337 Add test to Verify Git Plugin
  tests/Resources/Page/ODH/AiApps/Aikit.robot
  tests/Resources/Page/ODH/AiApps/Openvino.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
  tests/Tests/600__ai_apps/620__intel_aikit/620__intel_aikit.robot
  tests/Tests/600__ai_apps/660__openvino/660__openvino.robot
Labels: verified, new test

#391 Verify Monitoring Stack Is Reconciled Without Restarting The ODS Operator
  tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, new test

#367 Add test to verify dashboard's favorite resource cards behavior (ODS-389)
  tests/Resources/Common.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, new test

#395 Fix test "Verify That MT-SRE Are Not Paged For Alerts ..." with new keyword "Get Cluster Name From Console URL"
  tests/Resources/Common.robot
  tests/Tests/100__deploy/130__operators/130__rhods_operator/135__rhods_operator_logs_verification.robot
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
Labels: verified, enhancements, misc

#396 Verify JupyterHub DB Is Shipped And Enabled Within ODS
  tests/Resources/ODS.robot
  tests/Tests/100__deploy/100__installation/108__jupyterhub.robot
Labels: verified, new test

#394 Add fix for RHOSAK e2e test case
  tests/Resources/Page/HybridCloudConsole/Rhosak.robot
Labels: verified, enhancements

#332 Add Tests to Verify Empty User Groups Doesn't Allow Users to Spawn Notebooks(ODS-572)
  tests/Tests/100__deploy/110__auth_providers_and_rbac/110__rbac.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
Labels: verified, new test

#397 Modify keyword to fetch the name and added retrun to the notification…
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  utils/scripts/ocm/ocm.py
Labels: verified, enhancements, misc

#398 Verify PostgreSQL Is Not Deployed When AWS RDS Is Enabled
  tests/Tests/100__deploy/100__installation/108__jupyterhub.robot
Labels: verified, new test

#399 Fix some test Tags, Documentation and Title
  tests/Tests/500__jupyterhub/test.robot
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
  tests/Tests/600__ai_apps/620__intel_aikit/620__intel_aikit.robot
  tests/Tests/600__ai_apps/640__rhoam/640__rhoam_installation.robot
  tests/Tests/600__ai_apps/650__rhosak/650__rhosak.robot
  tests/Tests/600__ai_apps/660__openvino/660__openvino.robot
Labels: enhancements

#401 Verify JupyterHub Receives Credentials And Creates Instance Of AWS RDS
  tests/Resources/ODS.robot
  tests/Tests/100__deploy/100__installation/108__jupyterhub.robot
Labels: verified, new test

#403 Remove version check from ODS-1165
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: needs testing, enhancements

#318 Update "Clone Git Repository" to confirm if and when clone operation is successful
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
Labels: verified, new test, do not merge

#404 Fix Dockerfile
  build/Dockerfile
Labels: verified, misc

#416 Reenable url-parse check
  tests/Resources/Page/ODH/JupyterHub/HighAvailability.robot
Labels: enhancements

#414 Fix error in Smoke test of Anaconda
  tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
Labels: enhancements

#410 Add Tests to Verify Tensorflow GPU(ODS-474)
  tests/Tests/500__jupyterhub/test-versions.robot
Labels: misc

#407 venv: only create when absent
  run_robot_test.sh
Labels: verified, misc

#415 Check enabled page is loading after uninstalling operator
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, new test

#422 Add timeout in select explore keyword for monitoring in grafana
  tests/Resources/Page/ODH/Grafana/Grafana.resource
Labels: enhancements

#423 Add ODS-543 label
  tasks/Tasks/rhods_olm.robot
Labels: verified, new task

#428 Add script to split Suites
  build/Dockerfile
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/500__jupyterhub/notebook_size_verification.robot
  tests/Tests/800__culler/culler.robot
  utils/scripts/SplitSuite.py
Labels: verified, utils

#323 Added Tests to Verify Notifications Are Shown When Notebook Builds Are Not Started(ODS-1347)
  tests/Resources/Page/OCPDashboard/Builds/Builds.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-notebook.robot
Labels: verified, new test

#400 Add tests to Verify CPU and Memory requests for the CUDA and Image Pods(ODS-313)
  tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, new test

#260 Add Tests to Verify Failing Notebook Names Are Shown In Notifications(ODS-470)
  tests/Resources/Page/OCPDashboard/Builds/Builds.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/500__jupyterhub/test.robot
Labels: needs testing, new test

#412 Update GPU add-on testing for new SKU
  tests/Resources/OCP.resource
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/500__jupyterhub/minimal-cuda-test.robot
  tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
Labels: verified, enhancements

#413 Added steps to disable csvcopy to diable
  tests/Tests/700__sandbox/701__performance_sandbox.robot
  tests/Tests/700__sandbox/olm.yaml
Labels: verified, enhancements

#417 Update tests for RHODS Alerts
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
Labels: verified, enhancements

#424 Add test cases to check error messages about RHODS groups
  tests/Resources/Common.robot
  tests/Resources/ODS.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, new test

#425 Add test Verify That The Operator Pod Does Not Get Stuck After Upgrade
  tests/Tests/100__deploy/100__installation/109__operator.robot
Labels: verified, new test

#433 Add flaky test tags for some TCs in Sanity
  tests/Tests/100__deploy/110__auth_providers_and_rbac/110__rbac.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/400__ods_dashboard/410__ods_dashboard_settings.robot
Labels: enhancements

#431 Add Tests to verify Cuda Image builds in cluster(ODS-444)
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: new test

#246 Adding README to ocm script
  utils/scripts/ocm/README.md
Labels: documentation

#331 Add test to verify user can access documentation
  tests/Resources/ODS.robot
  tests/Resources/Page/HybridCloudConsole/HCCLogin.robot
  tests/Resources/RHOSi.resource
  tests/Tests/100__deploy/100__installation/101__installation.robot
Labels: verified, new test

#436 Fix for empty String in json files
  utils/scripts/ocm/ocm.py
Labels: verified, utils

#435 Fix Tier2 tag in ODS-1303
  tests/Tests/100__deploy/100__installation/101__installation.robot
Labels: verified, enhancements

#434 modify script with new changes in latest rhods version
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, enhancements

#438 Fix issue while getting token for prometheus
  utils/scripts/testconfig/generateTestConfigFile.py
Labels: verified
