Repository red-hat-data-services/ods-ci, pull requests merged in 2022-10, with the labels that each got.

#584 Shellcheck lineter implementation
  .github/workflows/code_quality.yaml
Labels: enhancements

#586 Add self managed catalog source
  tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
  tasks/Resources/RHODS_OLM/uninstall/oc_uninstall.robot
Labels: verified, enhancements

#592 Prepare ods-ci 1.17.0 release
  tests/Tests/100__deploy/100__installation/101__installation.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/100__deploy/100__installation/103__post_install_monitoring_port_forwarding.robot
  tests/Tests/100__deploy/100__installation/104__dashboard.robot
  tests/Tests/100__deploy/100__installation/109__operator.robot
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/400__ods_dashboard/410__ods_dashboard_settings.robot
  tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
  tests/Tests/400__ods_dashboard/413__ods_dashboard_settings_pod_tolerations.robot
  tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
  tests/Tests/500__jupyterhub/custom-image.robot
  tests/Tests/500__jupyterhub/jupyterhub-user-access.robot
  tests/Tests/500__jupyterhub/test-pipChanges-not-permanent.robot
  tests/Tests/500__jupyterhub/test-versions.robot
  tests/Tests/500__jupyterhub/test.robot
  tests/Tests/800__culler/culler.robot
  tests/Tests/900__high_availability/900__openshift/900__openshift.robot
Labels: verified, enhancements

#597 Remove dot from expected text when changing cluster settings
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: enhancements

#591 Fix pod toleration test case, add new TC for unsupported tolerations
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/400__ods_dashboard/415__ods_dashboard_settings_pod_tolerations.robot
Labels: new test, enhancements

#601 Save cluster details in file and add sshkey option in config yaml
  tasks/Resources/Provisioning/Hive/AWS/aws-cluster.yaml
  tasks/Resources/Provisioning/Hive/AWS/oc-provision.robot
Labels: verified

#599 Wait for cuda builds in Sanity
  tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
  tests/Tests/500__jupyterhub/test-folder-permissions.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-time.robot
  tests/Tests/500__jupyterhub/test-versions.robot
Labels: verified, enhancements

#596 Add test for unsupported environment variable names
  libs/Helpers.py
  tests/Tests/500__jupyterhub/test.robot
Labels: verified, new test

#595 Remove check on pachyderm secret creation
  tests/Tests/600__ai_apps/670__pachyderm/670__pachyderm.robot
Labels: enhancements

#581 Adapt ODS-488,1303,771 to account for dashboard differences in Self-managed
  tests/Resources/Common.robot
  tests/Resources/Files/AppsInfoDictionary.json
  tests/Resources/Files/AppsInfoDictionary_latest.json
  tests/Resources/OCP.resource
  tests/Resources/ODS.robot
  tests/Resources/Page/HybridCloudConsole/HCCLogin.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/100__deploy/100__installation/101__installation.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, enhancements

#593 Adapt API Access tests after new changes in dashboard endpoints
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboardAPI.resource
  tests/Resources/RHOSi.resource
  tests/Tests/400__ods_dashboard/414__ods_dashboard_api.robot
Labels: verified, enhancements

#333 Add test case to verify it is possible to create custom Dashboard items (Application,QuickStarts,HowTo,Tutorial,Documentation)
  tests/Resources/Files/CustomAppInfoDictionary.json
  tests/Resources/Files/custom_app.yaml
  tests/Resources/Files/custom_doc_howto.yaml
  tests/Resources/Files/custom_doc_tutorial.yaml
  tests/Resources/Files/custom_quickstart.yaml
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  tests/Resources/Page/ODH/ODHDashboard/ResourcesPage.resource
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/400__ods_dashboard/415__ods_custom_docs.robot
Labels: verified, new test

#602 Add test suite for gpu autoscaling
  tests/Resources/OCP.resource
  tests/Resources/Page/ODH/JupyterHub/GPU.resource
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Tests/500__jupyterhub/autoscaling-gpus.robot
Labels: verified, new test

#607 Disable XLarge test
  tests/Tests/500__jupyterhub/test.robot
Labels: verified, enhancements

#603 update model serving tests for ovms
  tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
Labels: enhancements

#611 Modify the image to Centos stream for terraform provisioning
  utils/scripts/terraform/openstack/provision.py
  utils/scripts/terraform/openstack/requirements.sh
  utils/scripts/terraform/openstack/variables.tf
Labels: verified, enhancements

#610 "Add support to perform OSD upgrade"
  utils/scripts/ocm/ocm.py
Labels: verified
