Repository red-hat-data-services/ods-ci, pull requests merged in 2022-12, with the labels that each got.

#639 Fix smoke failure due to cpu billing tests
  tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
Labels: enhancements

#637 Add notebook spawning with basic user in Smoke suite
  tests/Resources/Common.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, enhancements

#633 Add tasks for Managed Starburst and first tests
  libs/Helpers.py
  tasks/Resources/RedHatMarketplace.resource
  tasks/Resources/SERH_OLM/install.resource
  tasks/Tasks/deploy_managed_starburst.robot
  tasks/Tasks/rh_marketplace.robot
  tests/Resources/Page/ODH/AiApps/ManagedStarburst.resource
  tests/Resources/RHOSi.resource
  tests/Tests/600__ai_apps/680__starburst/681__managed_starburst.robot
  utils/scripts/ocm/ocm.py
  utils/scripts/ocm/templates/install_addon_starburst.jinja
  utils/scripts/testconfig/generateTestConfigFile.py
  utils/scripts/testconfig/test-variables.yml
Labels: verified, new test, :warning: high priority review

#635 Add more tests for Managed Starburst
  libs/Helpers.py
  tasks/Resources/SERH_OLM/install.resource
  tests/Resources/Page/ODH/AiApps/ManagedStarburst.resource
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Resources/RHOSi.resource
  tests/Tests/600__ai_apps/680__starburst/681__managed_starburst.robot
  utils/scripts/ocm/ocm.py
  utils/scripts/testconfig/generateTestConfigFile.py
  utils/scripts/testconfig/test-variables.yml
Labels: verified, new test, :warning: high priority review

#636 Add GCP provision
  .gitignore
  infrastructure_configuration.yaml.example
  tasks/Resources/Provisioning/Hive/AWS/aws-cluster.yaml
  tasks/Resources/Provisioning/Hive/AWS/oc-provision.robot
  tasks/Resources/Provisioning/Hive/GCP/gcp-cluster.yaml
  tasks/Resources/Provisioning/Hive/claim.yaml
  tasks/Resources/Provisioning/Hive/deprovision.robot
  tasks/Resources/Provisioning/Hive/gpu-provision.robot
  tasks/Resources/Provisioning/Hive/provision.robot
  tasks/Tasks/provision_aws_cluster.robot
  tasks/Tasks/provision_self_managed_cluster.robot
Labels: verified, new task

#643 Fix Dashboard XPaths for RHODS v1.20
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements

#632 Wait for a possible popup in "Spawn Notebook With Arguments"
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: needs testing, enhancements

#646 Skip the grafana Test case execution for RHODS 1.20
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/100__deploy/100__installation/103__grafana.robot
Labels: enhancements

#648 update utils files with S3 vars
  utils/scripts/testconfig/generateTestConfigFile.py
  utils/scripts/testconfig/test-variables.yml
Labels: needs testing, enhancements

#634 Restore ODS-293 test case
  tests/Tests/500__jupyterhub/jupyterhub-user-access.robot
Labels: needs testing, enhancements

#647 Fix Test Metric "Notebook CPU Usage" On ODS Prometheus
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
Labels: verified, enhancements

#644 Fix DS Projects tests for RHODS v1.20
  tests/Resources/Common.robot
  tests/Resources/OCP.resource
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, enhancements

#650 Fix expected error page in ODS-293
  tests/Tests/500__jupyterhub/jupyterhub-user-access.robot
Labels: needs testing, enhancements

#652 Fix test-versions tooltip xpath
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: enhancements

#630 In RHOSi Setup and Teardown, warn if alerts are firing or pending
  tests/Resources/Page/ODH/Monitoring/Monitoring.resource
  tests/Resources/Page/ODH/Prometheus/Prometheus.robot
Labels: verified, enhancements

#651 Add AutomationBug tag to failing tests. Prepare ods-ci 1.20 release
  tests/Tests/100__deploy/110__auth_providers_and_rbac/110__rbac.robot
  tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
Labels: enhancements

#653 Fix failures in T2 tests for RHODS 1.20
  tests/Resources/ODS.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-time.robot
  tests/Tests/500__jupyterhub/test.robot
Labels: enhancements

#656 Fix expected error page in ODS-572 plus add 1.19 compatibility in ODS-293
  tests/Tests/100__deploy/110__auth_providers_and_rbac/110__rbac.robot
  tests/Tests/500__jupyterhub/jupyterhub-user-access.robot
Labels: verified, enhancements

#655 Smarter comparison for model inference output
  libs/Helpers.py
  tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
Labels: enhancements

#654 Additional fixes for ods-ci 1.20
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/100__deploy/100__installation/104__dashboard.robot
Labels: enhancements

#657 Fix test of status API based on RHODS version
  tests/Tests/400__ods_dashboard/414__ods_dashboard_api.robot
Labels: needs testing, enhancements

#660 Restore ODS-1081 and fix Keyword to fetch cluster environment
  tests/Resources/ODS.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, enhancements

#661 Add teardown to autoscaling-gpus test suite
  tests/Tests/500__jupyterhub/autoscaling-gpus.robot
Labels: enhancements

#662 Fix keyword to check if RHODS is Self managed
  tests/Resources/OCP.resource
Labels: needs testing, enhancements

#663 bump cuda expected version to 12
  tests/Tests/500__jupyterhub/minimal-cuda-test.robot
  tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
Labels: enhancements

#665 Add some checks on RHODS Self-managed in Dashboard tests
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/600__ai_apps/640__rhoam/640__rhoam.robot
  tests/Tests/600__ai_apps/640__rhoam/640__rhoam_installation.robot
Labels: verified, enhancements

#658 Improve keyword to wait for dashboard and remove Seldon folder
  tests/Resources/Page/HybridCloudConsole/Rhosak.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  tests/Tests/500__jupyterhub/jupyterhub-user-access.robot
  tests/Tests/600__ai_apps/690__seldon/690__seldon.robot
Labels: verified, enhancements

#664 Upgrade to RF 5
  setup.py
  tasks/Resources/RHODS_OLM/install/install.robot
  tests/Resources/Page/OCPDashboard/InstalledOperators/InstalledOperators.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Resources/Page/ODH/JupyterHub/LaunchPython3.robot
  tests/Tests/500__jupyterhub/test-jupyterlab-time.robot
  tests/Tests/500__jupyterhub/test-minimal-image.robot
  tests/Tests/500__jupyterhub/test.robot
  tests/Tests/700__sandbox/701__performance_sandbox.robot
Labels: verified, enhancements
