Repository red-hat-data-services/ods-ci, pull requests merged in 2023-01, with the labels that each got.

#666 Misc fixes to Sanity and Smoke
  tests/Resources/Common.robot
  tests/Resources/ODS.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  tests/Resources/Page/ODH/ODHDashboard/ResourcesPage.resource
  tests/Tests/100__deploy/110__auth_providers_and_rbac/110__rbac.robot
  tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
  tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
  tests/Tests/400__ods_dashboard/415__ods_custom_docs.robot
Labels: verified, enhancements

#671 Run "Suite Availability Setup" only on RHODS Managed
  tests/Resources/Common.robot
  tests/Resources/Page/ODH/Monitoring/Monitoring.resource
  tests/Resources/RHOSi.resource
Labels: needs testing, verified

#668 Add infrastructure variables documentation
  docs/infrastructure_configuration_variables.md
Labels: documentation, verified

#672 Self-Managed: skip monitoring tests requiring RHODS prometheus
  tests/Tests/100__deploy/100__installation/102__post_install.robot
  tests/Tests/100__deploy/100__installation/105__prometheus.robot
  tests/Tests/100__deploy/100__installation/106__blackbox_exporter.robot
  tests/Tests/100__deploy/100__installation/107__alert_manager.robot
  tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
  tests/Tests/200__monitor_and_manage/200__metrics/204__check_pager_duty.robot
  tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
Labels: verified, enhancements, :warning: high priority review

#669 Fix dashboard broken tests in Sanity
  tests/Resources/Files/custom_app.yaml
  tests/Resources/Page/ODH/AiApps/Rhosak.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  tests/Resources/Page/ODH/ODHDashboard/ResourcesPage.resource
Labels: verified, enhancements

#670 Remove product bug from ODS-760 (AiKit)
  tests/Tests/600__ai_apps/620__intel_aikit/620__intel_aikit.robot
Labels: enhancements

#676 Fix unsupported env vars edge case
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: enhancements

#675 Add test for tolerations on workbeches
  tests/Resources/Page/OCPDashboard/Pods/Pods.robot
  tests/Resources/Page/ODH/JupyterHub/PVCChange.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHAdminUI.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  tests/Tests/400__ods_dashboard/410__ods_dashboard_settings.robot
  tests/Tests/400__ods_dashboard/411__ods_dashboard_settings_pvc_size.robot
  tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
  tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
  tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_additional.robot
  tests/Tests/400__ods_dashboard/415__ods_dashboard_settings_pod_tolerations.robot
  tests/Tests/500__jupyterhub/test-jupyterhub-api-telemetry.robot
  tests/Tests/800__culler/culler.robot
Labels: verified, new test, enhancements

#674 Add event log test plus refine data connection tests in DS Projects
  tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, new test

#679 Add test for Log Out options in workbenches
  tests/Resources/Page/LoginPage.robot
  tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, new test

#680 Fix sidebar checks for RHODS v1.22
  tests/Resources/Page/ODH/AiApps/Anaconda.resource
  tests/Resources/Page/ODH/AiApps/Rhosak.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements

#682 Bump upload-artifact to v3 in dryrun action
  .github/workflows/dry_run.yml
Labels: utils

#684 Fix "Save changes" keyword and ODS-488
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
Labels: verified, enhancements
