Repository red-hat-data-services/ods-ci, pull requests merged in 2023-04, with the labels that each got.

#735 Fix failures in 1.25 Sanity
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/500__jupyterhub/test-versions.robot
Labels: enhancements

#736 Fix user management sanity tests
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
Labels: needs testing, enhancements

#732 Added support to uninstall rhods for operatorhub installation
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: enhancements

#744 Add test to check access for "namespaces" API endpoint
  ods_ci/tests/Tests/400__ods_dashboard/414__ods_dashboard_api.robot
Labels: verified, new test

#743 fix for robocop action
  .robocop
Labels: enhancements

#742 Add library to resume osd cluster
  ods_ci/utils/scripts/ocm/ocm.py
Labels: verified, enhancements, utils

#739 update folder path xpath in Model Serving tests
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: enhancements

#741 Fix DS project Sanity test for 1.25
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#740 Bump jupyterlibrary to ^0.4.0
  poetry.lock
  pyproject.toml
Labels: enhancements

#738 [RHODS-7871] ODS-395 Verify App name
  ods_ci/tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
Labels: needs testing, new test

#746 Fix file path in ODS-1768
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_custom_docs.robot
Labels: verified, enhancements

#719 Hive tasks to provision clusters on openstack (PSI)
  .gitignore
  ods_ci/docs/infrastructure_configuration_variables.md
  ods_ci/tasks/Resources/Provisioning/Hive/AWS/aws-cluster.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GCP/gcp-cluster.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/create_fips.sh
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/hive_osp_cluster_template.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/claim.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/deprovision.robot
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
  ods_ci/tasks/Tasks/provision_self_managed_cluster.robot
  ods_ci/tests/Resources/Common.robot
  poetry.lock
  pyproject.toml
Labels: utils

#734 [RHODS-4116] Adding Quickstart test for restart functionality
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  ods_ci/tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
Labels: needs testing, enhancements

#709 Update to support PSAP notebook scale test
  ods_ci/test-variables.yml.example
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: needs testing, enhancements

#751 Fix perf regression tc in ods-ci
  ods_ci/tests/Tests/700__sandbox/701__performance_sandbox.robot
Labels: enhancements

#752 Add monitoring for other namespace
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: enhancements

#748 Refactor TC to check multiple RHODS admin groups and remove one ProductBug tag
  ods_ci/tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
Labels: verified, enhancements

#749 Add Tier1 tag to Smoke tests
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
  ods_ci/tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
  ods_ci/tests/Tests/500__jupyterhub/base-user-shutdown-test.robot
  ods_ci/tests/Tests/500__jupyterhub/multiple-image-tags.robot
  ods_ci/tests/Tests/500__jupyterhub/special-user-testing.robot
  ods_ci/tests/Tests/500__jupyterhub/test.robot
  ods_ci/tests/Tests/505__must_gather/test-must-gather-logs.robot
  ods_ci/tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
  ods_ci/tests/Tests/600__ai_apps/610__ibm_watson_studio/610__ibm_watson_studio.robot
  ods_ci/tests/Tests/600__ai_apps/620__intel_aikit/620__intel_aikit.robot
  ods_ci/tests/Tests/600__ai_apps/650__rhosak/650__rhosak.robot
  ods_ci/tests/Tests/600__ai_apps/660__openvino/660__openvino.robot
Labels: enhancements

#753 Fix broken links and format in readme docs
  ods_ci/docs/ODS-CI-IMAGE-README.md
  ods_ci/docs/RUN_ARGUMENTS.md
Labels: documentation

#755 Add ProductBug and AutomationBug tags
  ods_ci/tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
Labels: enhancements

#757 ODS-2015 - Verify DS Projects home page shows the right number of items the user has selected
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, new test

#756 Fix ods-1090 for rhods 1.26
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, enhancements

#759 Added monitoring of pod in each namespace
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/138__rhods_operator_oom_kill_verification.robot
Labels: verified, enhancements
