Repository red-hat-data-services/ods-ci, pull requests merged in 2023-11, with the labels that each got.

#995 Test Pipeline YAML context menu and verify read only
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
Labels: verified, new test

#996 Add support to create DSC without any conditon for rhods24
  ods_ci/tasks/Resources/Files/dsc_template.yml
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
Labels: needs testing, verified

#1004 FIx install issue for Beta channel for managed rhods
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: enhancements

#1001 [Fix] indentation of the robotframework keyword
  ods_ci/tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
Labels: enhancements

#1006 Add support for odh nightly with new changes
  ods_ci/tasks/Resources/Files/odh_catalogsource.yml
  ods_ci/tasks/Resources/Files/odh_nightly_sub.yml
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: verified, enhancements

#1005 Fix faulty kserve tests
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
  poetry.lock
  pyproject.toml
Labels: needs testing, enhancements

#1007 Fix uninstall for odh
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: verified, enhancements

#999 Wait pipeline server button be enabled
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: verified, enhancements

#1008 fix button for model serving in 2.4
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
Labels: verified, enhancements

#1012 Delete csv for odh-nightly
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: verified, enhancements

#1016 [Fix] Verify Elyra Pipelines In SDS-Based Images
  ods_ci/tests/Resources/Page/ODH/JupyterHub/Elyra.resource
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#1017 Fix monitoring tests in Smoke for RHODS 2.4.0
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
  ods_ci/tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  ods_ci/tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
  ods_ci/tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
Labels: verified, enhancements

#1015 [Fix] Tests.Jupyterhub.test-pipChanges-not-permanent
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Tests/500__jupyterhub/test-pipChanges-not-permanent.robot
Labels: verified, enhancements

#1018 fix capitalization of nvidia gpu accelerator
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/421__model_serving_gpu.robot
Labels: enhancements

#1019 [Fix] of the xpath for the jupyterlab workbench image version check
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: verified, enhancements

#1011 [Fix] test versions for the RHODS 2.4; add TrustyAI and HabanaAI
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Tests/500__jupyterhub/test-versions.robot
Labels: verified, enhancements

#1009 Update tests to use new Caikit + TGIS images
  ods_ci/tests/Resources/Files/llm/caikit_isvc.yaml
  ods_ci/tests/Resources/Files/llm/caikit_servingruntime.yaml
  ods_ci/tests/Resources/Files/llm/caikit_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/caikit_servingruntime_http.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardAPI.resource
  ods_ci/tests/Tests/100__deploy/100__installation/110__model_serving_watsonx.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, enhancements

#1020 [Fix] make dry-run happy again
  ods_ci/tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: enhancements

#1021 Update Monitoring tests for RHODS 2.4.0 RC2
  ods_ci/tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  ods_ci/tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  ods_ci/tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
Labels: verified, enhancements

#1023 [Fix] we should click on elements that have some size
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#1028 Increase pipeline run timeout
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
Labels: enhancements

#1024 Add tag with Polarion test case to DW test
  ods_ci/tests/Tests/650__distributed_workloads/test-run-dw-tests.robot
Labels: verified, enhancements

#1036 Check DS listed project by link instead of xpath
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
Labels: verified, enhancements

#1030 [Fix] custom image tests and one test removal
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Tests/500__jupyterhub/custom-image.robot
Labels: verified, enhancements

#1041 Temporally disable verifications of CodeFlare alerting and recording rules for 2.4
  ods_ci/tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
Labels: verified, enhancements

#1034 [Fix] test to check various user group access
  ods_ci/tests/Tests/500__jupyterhub/jupyterhub-user-access.robot
Labels: verified, enhancements

#1043 fix: Dashboards UI Tests 1775 and 1814
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
Labels: verified, enhancements

#1045 Update dsc default name
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, enhancements
