Repository red-hat-data-services/ods-ci, pull requests merged in 2023-09, with the labels that each got.

#894 fix: Inconsisten path in Readme
  README.md
Labels: documentation

#895 Wait 30 seconds to check if pods are equals to 0 when deleting pipeline server
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
Labels: verified, enhancements

#901 Update keyword to work with V1 and V2 operator
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: verified, enhancements, :warning: high priority review

#902 Check rhods-notebooks namespace only when needed after install
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: enhancements

#893 Add new tests for WatsonX serving stack
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, new test, :warning: high priority review

#917 [Fix] Update the expected CUDA version to 12.2
  ods_ci/tests/Tests/500__jupyterhub/minimal-cuda-test.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
Labels: enhancements

#913 Reduce number of IDE errors and wrong imports
  .gitignore
  ods_ci/tests/Resources/Page/HybridCloudConsole/HCCLogin.robot
  ods_ci/tests/Resources/Page/HybridCloudConsole/OCM.robot
  ods_ci/tests/Resources/Page/MarketplaceConsole/MarketplaceConsole.robot
  ods_ci/tests/Resources/Page/OCPDashboard/DeploymentConfigs/DeploymentConfigs.robot
  ods_ci/tests/Resources/Page/OCPDashboard/InstalledOperators/InstalledOperators.robot
  ods_ci/tests/Resources/Page/OCPDashboard/InstalledOperators/UninstallODH.robot
  ods_ci/tests/Resources/Page/OCPDashboard/Page.robot
  ods_ci/tests/Resources/Page/OCPDashboard/UserManagement/Groups.robot
  ods_ci/tests/Resources/Page/OCPLogin/OCPLogin.robot
  ods_ci/tests/Resources/Page/ODH/AiApps/Aikit.robot
  ods_ci/tests/Resources/Page/ODH/AiApps/ManagedStarburst.resource
  ods_ci/tests/Resources/Page/ODH/AiApps/Openvino.robot
  ods_ci/tests/Resources/Page/ODH/AiApps/Pachyderm.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/Elyra.resource
  ods_ci/tests/Resources/Page/ODH/JupyterHub/GPU.resource
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabSidebar.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/LaunchJupyterHub.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/LaunchPython3.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/PVCChange.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Permissions.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ResourcesPage.resource
  ods_ci/tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/100__deploy/100__installation/101__installation.robot
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/138__rhods_operator_oom_kill_verification.robot
  ods_ci/tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
  ods_ci/tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/421__model_serving_gpu.robot
  ods_ci/tests/Tests/500__jupyterhub/autoscaling-gpus.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-cuda-test.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
  ods_ci/tests/Tests/500__jupyterhub/plugin-verification.robot
  ods_ci/tests/Tests/500__jupyterhub/test-minimal-image.robot
  ods_ci/tests/Tests/500__jupyterhub/test-uninstall.robot
  ods_ci/tests/Tests/600__ai_apps/680__starburst/681__managed_starburst.robot
Labels: verified, enhancements

#918 [Fix] Update version of numpy to 1.24.4
  ods_ci/tests/Resources/Page/ODH/JupyterHub/GPU.resource
Labels: verified, enhancements

#921 fix culler suite git issues
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Tests/800__culler/culler.robot
Labels: verified, enhancements

#925 Add support to get the RHODS/ODH dashboard URL during run time
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: verified

#928 Remove the double quotes from dashboard URL in managed workflow
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: verified, utils

#905 Bump kfp-tekton to 1.5.8
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/libs/DataSciencePipelinesKfpTekton.py
  ods_ci/libs/ods-ci.log
  poetry.lock
  pyproject.toml
Labels: enhancements

#900 Use 'Create File From Template' KW in 'Compile Inference Service YAML'
  ods_ci/tests/Resources/Files/llm/caikit_isvc.yaml
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, enhancements

#903 Update global variables of Prometheus if required
  ods_ci/tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  ods_ci/tests/Resources/RHOSi.resource
Labels: verified

#932 Bump kfp-tekton to 1.5.9
  ods_ci/libs/DataSciencePipelinesKfpTekton.py
  poetry.lock
  pyproject.toml
Labels: verified, enhancements

#935 Data Science Pipeliens: fix Xpath for Get Workflow Name From Topology Page
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
Labels: enhancements

#939 Update expected external links for Starburst Enterprise test
  ods_ci/tests/Resources/Files/AppsInfoDictionary_latest.json
Labels: verified, enhancements

#940 increase scroll amount on env variables section
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: enhancements

#941 update the locator path for Container size drop down
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: enhancements

#938 Workaround for Import Pipeline button is ready
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: verified, enhancements

#945 Add support for model serving in upgrade suite
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/100__deploy/120__upgrades/120__pre_upgrades.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/122__post_ugrade.robot
  ods_ci/tests/Tests/505__must_gather/test-must-gather-logs.robot
Labels: verified, new test

#949 Add support to validate that image provide is based on digest not tags
  ods_ci/tests/Resources/Page/OCPDashboard/Pods/Pods.robot
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, new test

#950 Adding support to look only operator pod in operator namespace
  ods_ci/tests/Resources/Page/OCPDashboard/Pods/Pods.robot
Labels: verified, enhancements

#927 Add support for CodeFlare operator in RHODS task
  ods_ci/tasks/Resources/Files/codeflare_sub_template.yaml
  ods_ci/tasks/Resources/RHODS_OLM/RHODS_OLM.resource
  ods_ci/tasks/Resources/RHODS_OLM/install/codeflare_install.resource
  ods_ci/tasks/Resources/RHODS_OLM/install/install.robot
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/codeflare_uninstall.resource
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/oc_uninstall.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tasks/Tasks/rhods_olm.robot
  ods_ci/tests/Resources/Common.robot
Labels: verified

#923 Update to Robot Framework 6
  poetry.lock
  pyproject.toml
Labels: enhancements

#926 util.execute_command() real-time output and ocm.py verbosity level option
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/util.py
Labels: verified, enhancements

#946 Fix Openshift Pipelines installation in OCP 4.14 & fix timing issue
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/tests/Resources/Page/Operators/OpenShiftPipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/431__data-science-pipelines-api.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/432__data-science-pipelines-tekton.robot
Labels: verified, enhancements

#936 Small change in README + addition of a flag to open the test reports in a browser after test execution
  README.md
  ods_ci/docs/RUN_ARGUMENTS.md
  ods_ci/run_robot_test.sh
Labels: documentation, verified, enhancements

#948 Update Smoke Suite
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_settings.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
  ods_ci/tests/Tests/500__jupyterhub/test-minimal-image.robot
Labels: verified, enhancements

#954 fix namespace for odh-nightly
  ods_ci/tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
Labels: enhancements

#943 [Fix] run_robot_test.sh - OC login and return value
  ods_ci/run_robot_test.sh
Labels: verified, enhancements

#956 fix the machine pool exiting function
  ods_ci/utils/scripts/ocm/ocm.py
Labels: verified

#957 [Dockerfile] Add fix for using chromium with selenium 4.13
  ods_ci/build/Dockerfile
  ods_ci/test-variables.yml.example
Labels: verified, enhancements
