Repository red-hat-data-services/ods-ci, pull requests merged in 2023-07, with the labels that each got.

#838 update model label and pod verification for rhods installtion
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: enhancements

#839 Enhance OpenShift Pipelines installation depending on environment + pipeline route bugfix
  ods_ci/tests/Resources/Files/data-science-pipelines-sample.yaml
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Resources/Page/Operators/OpenShiftPipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/431__data-science-pipelines-api.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/432__data-science-pipelines-tekton.robot
Labels: verified, enhancements

#812 Delete pipeline
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
Labels: verified, new test

#842 Update model serving xpaths for RHODS 1.29
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
Labels: verified, enhancements

#845 Restructure robot xml output file for performing polarion update
  ods_ci/utils/scripts/polarion/xunit_add_properties.py
Labels: verified, utils

#843 Test data science pipeline deletion
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
Labels: new test

#846 ODS-1932 - Verify user can edit a S3 data connection
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: needs testing, new test

#849 Add teardown for uninstall
  ods_ci/tasks/Tasks/rhods_olm.robot
Labels: verified, enhancements

#850 Fix test using DataSciencePipelinesAPI.Delete *
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/431__data-science-pipelines-api.robot
Labels: enhancements

#852 Add out log console for clone repo keyword
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: enhancements

#851 Wait until pipeline route is ready to avoid firing pipeline alert
  ods_ci/libs/DataSciencePipelinesAPI.py
Labels: verified, enhancements

#854 fix uninstall issue with operatorhub
  ods_ci/tasks/Resources/RHODS_OLM/install/install.robot
Labels: enhancements

#841 Add option to use custom user settings in ods-ci image
  ods_ci/build/Dockerfile
  ods_ci/build/install_idp.sh
  ods_ci/configs/resources/oauth_htp_idp.json
  ods_ci/configs/templates/user_config.json
  ods_ci/docs/ODS-CI-IMAGE-README.md
  ods_ci/docs/ods-ci_pod_oc_idp.yaml
  ods_ci/docs/ods-ci_pod_ocm_idp.yaml
  ods_ci/test-variables.yml.example
  ods_ci/tests/Resources/Page/ODH/JupyterHub/jupyter-helper.py
Labels: verified, enhancements, utils

#847 Import ODHDataScienceProject/Pipelines.resource to fix dryrun
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
Labels: enhancements

#855 Increase workbench timeout in first Elyra test
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/435__data-science-pipelines-elyra.robot
Labels: verified, enhancements

#857 Disable sharing memory usage for temp file
  ods_ci/utils/scripts/testconfig/test-variables.yml
Labels: enhancements

#837 Add support for rosa cluster creation
  ods_ci/utils/scripts/awsOps.py
  ods_ci/utils/scripts/rosa/__init__.py
  ods_ci/utils/scripts/rosa/rosa.py
  ods_ci/utils/scripts/rosa/rosaOps.py
Labels: verified

#862 Fix model framework heading path for RHODS 1.30
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: enhancements
