Repository red-hat-data-services/ods-ci, pull requests merged in 2023-08, with the labels that each got.

#863 Fix rhods installation for build 1.31
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified

#867 First round of automation for new serving stack
  ods_ci/tests/Resources/Files/llm/caikit_servingruntime.yaml
  ods_ci/tests/Resources/Files/llm/gateways.yaml
  ods_ci/tests/Resources/Files/llm/knativeserving_istio.yaml
  ods_ci/tests/Resources/Files/llm/peer_auth.yaml
  ods_ci/tests/Resources/Files/llm/smcp.yaml
  ods_ci/tests/Resources/Files/llm/smmr.yaml
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/OCPDashboard/Pods/Pods.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Resources/Page/Operators/ISVs.resource
  ods_ci/tests/Tests/100__deploy/100__installation/110__model_serving_watsonx.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
  ods_ci/tests/Tests/600__ai_apps/680__starburst/682__starburst_enterprise_sm.robot
  ods_ci/utils/scripts/generate-wildcard-certs.sh
Labels: new test

#872 Use the 'Jump to section' links to scroll elements into view
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#868 Add test and keyword to deploy and query models
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Files/llm/bucket_sa.yaml
  ods_ci/tests/Resources/Files/llm/bucket_secret.yaml
  ods_ci/tests/Resources/Files/llm/caikit_isvc.yaml
  ods_ci/tests/Resources/Files/llm/caikit_servingruntime.yaml
  ods_ci/tests/Resources/Files/llm/smmr.yaml
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Resources/Page/Operators/ISVs.resource
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
  ods_ci/utils/scripts/clean_watsonx.sh
  ods_ci/utils/scripts/generate-wildcard-certs.sh
Labels: verified, new test, :warning: high priority review

#878 Improve the teardown not to fail for corner case scenario
  ods_ci/tasks/Resources/RHODS_OLM/install/install.robot
Labels: verified, enhancements

#876 Add test for multiple models served with WatsonX stack in the same namespace
  ods_ci/tests/Resources/Files/llm/caikit_servingruntime.yaml
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
  ods_ci/utils/scripts/clean_watsonx.sh
Labels: needs testing, new test, :warning: high priority review

#883 Add support for canary roll out
  ods_ci/tests/Resources/Files/llm/caikit_isvc.yaml
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, new test, :warning: high priority review

#884 Enhance the keyword and remove duplicate keyword call
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, enhancements

#881 Clean unused Floating IPs in Openstack, before creating new ones
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/create_fips.sh
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/hive_osp_cluster_template.yaml
Labels: verified, enhancements

#873 Add initial support for running tests on Open Data Hub
  README.md
  ods_ci/test-variables-odh-overwrite.yml
  ods_ci/test-variables.yml.example
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/OCPDashboard/InstalledOperators/InstalledOperators.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
  ods_ci/utils/scripts/testconfig/test-variables.yml
Labels: verified, enhancements

#889 Add test for auto scale using Concurrency
  ods_ci/tests/Resources/Files/llm/caikit_isvc.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, new test, :warning: high priority review

#885 Add tests for deploying models with multiple replicas
  ods_ci/tests/Resources/Files/llm/caikit_isvc.yaml
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, new test, :warning: high priority review

#892 Update the keyword for odh nightlies
  ods_ci/tests/Resources/Page/OCPDashboard/InstalledOperators/InstalledOperators.robot
Labels: verified, enhancements

#896 Add Test for scale to zero using kserve
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, new test, :warning: high priority review

#890 Modify DSC CR install for 1.32 RC4
  ods_ci/tasks/Resources/Files/dsc_template.yml
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/test-variables.yml.example
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/131__rhods_operatorv2.robot
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: verified, enhancements, :warning: high priority review

#888 fix uninstall for v2 operator
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: verified, enhancements
