Repository red-hat-data-services/ods-ci, pull requests merged in 2023-10, with the labels that each got.

#959 Add sanity tag to DS Project smoke tests
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: enhancements

#955 Revert "workaround for section header regression (#937)"
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, enhancements

#960 Fix xpath selectors for workbenches and model serving dropdowns in 1.34
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: needs testing, enhancements

#961 Fix for V2 operator install for rhods1.34
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: enhancements

#947 Add option to install KServe stack from Script instead of simulating step-by-step
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, new test

#958 Fix starburst enteprise tests
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Tests/600__ai_apps/680__starburst/682__starburst_enterprise_sm.robot
Labels: verified, enhancements

#962 Add version check on Elyra libraries
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
Labels: verified, enhancements

#967 Add support to deploy custom runtime for upgrade testing
  ods_ci/tests/Resources/Files/caikit_runtime_template.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/100__deploy/120__upgrades/120__pre_upgrades.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/122__post_ugrade.robot
Labels: verified, new test, enhancements

#942 [RHODS-11955] Verify user can edit name and description in a workbenc…
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_edit.robot
Labels: verified, new test

#973 Change the ns to have same config as documented
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, enhancements

#964 Add Custom Serving Runtime UI test suite
  ods_ci/tests/Resources/Files/ovms_servingruntime.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/423__model_serving_customruntimes.robot
Labels: verified, new test

#924 Automate embedded RHODS install
  ods_ci/libs/Helpers.py
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tests/Resources/Files/operatorV2/cs_template.yaml
  ods_ci/tests/Resources/Files/operatorV2/embedded.txt
  ods_ci/tests/Resources/Files/operatorV2/embedded_cs.txt
  ods_ci/tests/Resources/Files/operatorV2/operatorgroup_template.yaml
  ods_ci/tests/Resources/Files/operatorV2/subscription_template_21.yaml
  ods_ci/tests/Resources/Files/operatorV2/subscription_template_z.yaml
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/131__rhods_operatorv2.robot
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/133__embedded_operator.robot
Labels: verified, new test

#974 Add watsonx basic deployment tests for additional models
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, new test

#975 Add runtime image upgrade test
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, new test

#978 Make DS Project tests independent
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_edit.robot
Labels: verified, enhancements, :warning: high priority review

#982 Compiled upload download yaml for testing purpose
  ods_ci/libs/DataSciencePipelinesKfpTekton.py
  ods_ci/tests/Resources/Files/pipeline-samples/upload_download-compiled.yaml
Labels: enhancements

#986 Restore two tensor flow tests into sanity
  ods_ci/tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
Labels: enhancements

#985 Add WatsonX metrics test
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/Files/llm/uwm_cm_conf.yaml
  ods_ci/tests/Resources/Files/llm/uwm_cm_enable.yaml
  ods_ci/tests/Resources/Page/ODH/Monitoring/Monitoring.resource
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, new test

#989 Changed oc command to get RHODS version on Common.robot
  ods_ci/tests/Resources/Common.robot
Labels: verified, enhancements

#990 Make the ht password shorter
  ods_ci/build/install_idp.sh
Labels: needs testing, enhancements, :warning: high priority review

#971 fix: Jupyuterhub, workbench and model serving related tests
  ods_ci/tasks/Resources/Provisioning/GPU/gpu_deploy.sh
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/500__jupyterhub/autoscaling-gpus.robot
Labels: verified, :warning: high priority review

#993 [Stabilize] Let's wait for DOM ready before we start to edit workbenches
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_edit.robot
Labels: verified, enhancements

#998 [Fix] name of the robotframework keyword `Set NVidia GPU Accelerator`
  ods_ci/tests/Tests/500__jupyterhub/autoscaling-gpus.robot
Labels: enhancements

#988 Fix custom image tests
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Tests/500__jupyterhub/custom-image.robot
Labels: verified, new test, enhancements
