Repository red-hat-data-services/ods-ci, pull requests merged in 2023-05, with the labels that each got.

#712 Fix Pachyderm links
  ods_ci/tests/Resources/Files/AppsInfoDictionary_latest.json
  ods_ci/tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, enhancements

#764 Add dependency kfp-tekton = "==1.5.3"
  poetry.lock
  pyproject.toml
Labels: enhancements

#761 Upgrade ODS-CI image to centos stream 9
  ods_ci/build/Dockerfile
  ods_ci/build/run.sh
  ods_ci/run_robot_test.sh
Labels: verified, enhancements

#762 Added options for Openstack Cloud and OCP CNI
  ods_ci/tasks/Resources/Provisioning/Hive/AWS/aws-cluster.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GCP/gcp-cluster.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/create_fips.sh
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/hive_osp_cluster_template.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
Labels: needs testing, utils

#765 Update robotidy.toml change to AlignTestCasesSection
  ods_ci/robotidy.toml
Labels: enhancements

#770 Added support to install rhods from different update channels
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Tasks/rhods_olm.robot
Labels: verified, enhancements

#773 Fix apply command in Starburst tests
  ods_ci/tests/Tests/600__ai_apps/680__starburst/681__managed_starburst.robot
Labels: verified, enhancements

#774 Update must-gather image tag according to RHODS-8050
  ods_ci/tests/Tests/505__must_gather/get-must-gather-logs.sh
Labels: verified, enhancements

#768 Add test to check if user can set environment variables by uploading a YAML file
  ods_ci/tests/Resources/Files/env_vars_cm.yaml
  ods_ci/tests/Resources/Files/env_vars_secret.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, new test

#779 Automate Upgrade Test Case
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  ods_ci/tests/Tests/100__deploy/120__upgrades/120__pre_upgrades.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/121__during_upgrade.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/122__post_ugrade.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/custome_image.yaml
Labels: verified, new test

#778 Remove ProductBug from ODS-909 and ODS-507
  ods_ci/tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
  ods_ci/tests/Tests/500__jupyterhub/test-pipChanges-not-permanent.robot
Labels: enhancements

#782 Fix jupyterlab test removing .z stream from kernel argument
  ods_ci/tests/Tests/500__jupyterhub/test.robot
Labels: enhancements

#777 Add first 3 test cases for Project Sharing
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Permissions.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_permissions_mgmt.robot
Labels: verified, new test

#783 Remove rhosak e2e test
  ods_ci/tests/Resources/Page/HybridCloudConsole/HCCLogin.robot
  ods_ci/tests/Resources/Page/HybridCloudConsole/Rhosak.robot
  ods_ci/tests/Resources/Page/ODH/AiApps/Rhosak.robot
  ods_ci/tests/Tests/600__ai_apps/650__rhosak/650__rhosak.robot
Labels: enhancements

#772 Improve uninstallation process (waiting until a project is deleted)
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/oc_uninstall.robot
Labels: verified, enhancements

#785 Fixes for model serving test suite and DSP project creation keyword in 1.27
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
Labels: verified, enhancements

#784 Update Resourcename to fix test [RHODS-8159]
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, enhancements

#788 Update xpath of PV input for 1.27
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
Labels: verified, enhancements

#769 Support multiple files and methods for kfp_tekton
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/libs/DataSciencePipelinesKfpTekton.py
  ods_ci/tests/Resources/Files/pipeline-samples/flip_coin.py
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/431__data-science-pipelines-api.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/432__data-science-pipelines-tekton.robot
Labels: verified, enhancements

#789 fix Launch Jupyterhub via App keyword and rename it
  ods_ci/tests/Resources/Page/ODH/JupyterHub/LaunchJupyterHub.robot
  ods_ci/tests/Tests/500__jupyterhub/test.robot
Labels: verified, enhancements

#791 Projects.Create Data Science Project: give more time for the page to reload
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
Labels: enhancements

#787 Set RHODS_OSD_INSTALL_REPO directory as a suite variable
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
  ods_ci/tasks/Resources/RHODS_OLM/install/install.robot
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tasks/Tasks/rhods_olm.robot
Labels: verified, enhancements

#776 Add option RETURN_PW (for debug purposes)
  ods_ci/build/Dockerfile
  ods_ci/build/install_idp.sh
Labels: verified, enhancements

#796 Add first test and keywords for pipeline creation and execution via UI
  ods_ci/tests/Resources/Files/pipeline-samples/iris-pipeline-compiled.yaml
  ods_ci/tests/Resources/Page/ODH/JupyterHub/HighAvailability.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
Labels: verified, new test
