Repository red-hat-data-services/ods-ci, pull requests merged in 2023-06, with the labels that each got.

#802 Move ODS-2201 to sanity
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_permissions_mgmt.robot
Labels: enhancements

#800 Remove remaining RHOSAK files
  ods_ci/tests/Resources/Files/AppsInfoDictionary.json
  ods_ci/tests/Resources/Files/AppsInfoDictionary_latest.json
  ods_ci/tests/Resources/Page/HybridCloudConsole/HCCLogin.robot
  ods_ci/tests/Resources/Page/ODH/AiApps/Rhosak.resource
  ods_ci/tests/Resources/Page/ODH/AiApps/Rhosak.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/120__pre_upgrades.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/122__post_ugrade.robot
  ods_ci/tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  ods_ci/tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
  ods_ci/tests/Tests/400__ods_dashboard/414__ods_dashboard_api.robot
  ods_ci/tests/Tests/600__ai_apps/650__rhosak/650__rhosak.robot
Labels: needs testing, do not merge

#803 Change images URL in pipeline sample to test on disconnected clusters
  ods_ci/tests/Resources/Files/pipeline-samples/iris-pipeline-compiled.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: verified, enhancements

#797 Add tests for model serving with gpus
  ods_ci/libs/Helpers.py
  ods_ci/tests/Resources/Page/OCPDashboard/Pods/Pods.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/421__model_serving_gpu.robot
Labels: verified, new test, enhancements

#794 Refactor Project Sharing tests and add a test for user group access
  ods_ci/tests/Resources/Page/OCPDashboard/UserManagement/Groups.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Permissions.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_permissions_mgmt.robot
Labels: verified, new test, enhancements

#804 Verify Ods Users Can Do Http Request That Must Be Redirected to Https
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/431__data-science-pipelines-api.robot
Labels: verified, new test

#806 Fallback related to SSL for TektonClient
  ods_ci/libs/DataSciencePipelinesKfpTekton.py
Labels: verified, enhancements

#805 Bump kfp-tekton 1.5.4
  poetry.lock
  pyproject.toml
Labels: verified, enhancements

#811 Select Pipeline name (if applicable) when navigating to Create Run page
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: verified, enhancements

#814 Fix BYON Endpoint test
  ods_ci/tests/Tests/400__ods_dashboard/414__ods_dashboard_api.robot
Labels: verified, enhancements

#822 Add Starburst Enterprise expected data and new fetch logic based on RHODS type
  ods_ci/tests/Resources/Files/AppsInfoDictionary_latest.json
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements

#810 Fix ODS-489 to account for Starburst enteprise and RHOSAK changes
  ods_ci/tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
Labels: verified, enhancements

#819 Fix false positive result in install teardown
  ods_ci/tasks/Resources/RHODS_OLM/install/install.robot
Labels: verified, enhancements

#818 Add verification of more pod during rhods install
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified, enhancements

#830 Fix capitalization of page title in custom images test
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: enhancements

#832 Add duration flag to create token commands
  ods_ci/run_robot_test.sh
  ods_ci/test-variables.yml.example
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/421__model_serving_gpu.robot
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: enhancements

#831 Enable FIPS validation in Hive deployments
  ods_ci/tasks/Resources/Provisioning/Hive/AWS/aws-cluster.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GCP/gcp-cluster.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/create_fips.sh
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/hive_osp_cluster_template.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
  ods_ci/tests/Resources/Common.robot
Labels: verified

#825 Add tests for integration test btw RHODS and Starburst Enterprise Operator
  ods_ci/tasks/Resources/SERH_OLM/install.resource
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Files/isv-operator-group.yaml
  ods_ci/tests/Resources/Files/isv-operator-subscription.yaml
  ods_ci/tests/Resources/Files/starburst-enterprise-cr.json
  ods_ci/tests/Resources/Files/starburst-template-secret.yaml
  ods_ci/tests/Resources/Page/ODH/AiApps/ManagedStarburst.resource
  ods_ci/tests/Resources/Page/Operators/ISVs.resource
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/600__ai_apps/680__starburst/680__starburst_galaxy.robot
  ods_ci/tests/Tests/600__ai_apps/680__starburst/682__starburst_enterprise_sm.robot
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
  ods_ci/utils/scripts/testconfig/test-variables.yml
Labels: verified, new test

#833 Remove workaround for DS Project creation RHODS-8477
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
Labels: verified, enhancements

#813 ods_ci/build/Dockerfile: update to give HOME read/write access to the user
  ods_ci/build/Dockerfile
Labels: verified, enhancements

#836 fix SSL validation for model serving tests in self-managed clusters
  ods_ci/libs/Helpers.py
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
Labels: verified, enhancements
