Repository red-hat-data-services/ods-ci, pull requests merged in 2023-12, with the labels that each got.

#1058 Keep ReadWriteOnce as a default for storage class
  ods_ci/libs/DataSciencePipelinesKfpTekton.py
  ods_ci/tests/Resources/Files/pipeline-samples/upload_download-compiled.yaml
Labels: verified, enhancements

#1060 Enable Ray and Codeflare for DW tests
  ods_ci/tests/Tests/650__distributed_workloads/test-run-dw-tests.robot
Labels: verified, enhancements

#1044 Update Model Serving tests for 2.5
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/423__model_serving_customruntimes.robot
Labels: verified, enhancements

#1056 Always describe clusters with ID
  ods_ci/utils/scripts/ocm/ocm.py
Labels: enhancements

#1061 Adding keywords for kserve UI testing
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
Labels: enhancements

#1054 [RHOAIENG-136] ODS CI tests which run Codeflare E2E
  ods_ci/tests/Tests/650__distributed_workloads/test-run-codeflare-tests.robot
Labels: verified, new test

#1066 Add dependency operators for deploying RHOAI addon
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/ocm/templates/resource.jinja
Labels: verified, utils

#1062 Add Kserve UI tests
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm_UI.robot
Labels: verified, new test

#1057 Ray and Pipelines integration test
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/libs/DataSciencePipelinesKfpTekton.py
  ods_ci/tests/Resources/Files/pipeline-samples/ray_integration.py
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/432__data-science-pipelines-tekton.robot
Labels: verified, new test

#1073 [Fix] References to RHOAI in Explore page in our tests
  ods_ci/tests/Resources/Files/AppsInfoDictionary_latest.json
Labels: verified, enhancements

#1070 [Fix] to distinguish between PVC in pending and PVC in bound status
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
Labels: verified, enhancements

#1074 [Fix] The test for the expected error message to be shown to the user
  ods_ci/tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
Labels: verified, enhancements

#1014 [Fix] the Tests.Jupyterhub.Test-Jupyterlab-Git-Notebook
  ods_ci/tests/Tests/500__jupyterhub/test-jupyterlab-git.robot
Labels: verified, enhancements

#1064 [Fix] the test that checks the User/Group privileges permissions
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  ods_ci/tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
  ods_ci/tests/Tests/500__jupyterhub/jupyterhub-user-access.robot
Labels: verified, enhancements

#1077 After installation, verify the monitoring stack only for managed
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified, enhancements

#1083 Pass Execution at the end of 'Provision Self-Managed Cluster'
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
  ods_ci/tasks/Tasks/provision_self_managed_cluster.robot
Labels: needs testing, enhancements

#1082 Remove SMMR clean up from KServe test teardown
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: verified, enhancements

#1081 Add edit/admin permissions tests for Kserve UI
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm_UI.robot
Labels: verified, new test
