Repository red-hat-data-services/ods-ci, pull requests merged in 2024-03, with the labels that each got.

#1235 Stabilize Dashboard Test Suite (415)
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, enhancements

#1244 Add TGIS test for bigscience/mt0-xxl model
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/download_model_in_pvc.yaml
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: needs testing, new test

#1252 Add support for flan-t5-xl model
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: verified, new test

#1254 Add test for flant5-xxl
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: verified, new test

#1209 Feat: Accelerators Profile Administration UI e2e Tests
  ods_ci/tests/Resources/CLI/AcceleratorProfiles/AcceleratorProfiles.resource
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Files/accelerator/accelerator-profile-3349-2.yaml
  ods_ci/tests/Resources/Files/accelerator/accelerator-profile-3349-3.yaml
  ods_ci/tests/Resources/Files/accelerator/accelerator-profile-3349-4.yaml
  ods_ci/tests/Resources/Files/accelerator/accelerator-profile-3349-5.yaml
  ods_ci/tests/Resources/Files/accelerator/accelerator-profile-3349-6.yaml
  ods_ci/tests/Resources/Files/accelerator/accelerator-profile-3349-7.yaml
  ods_ci/tests/Resources/Files/accelerator/accelerator-profile-3349-8.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsAcceleratorProfiles.resource
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_settings.robot
  ods_ci/tests/Tests/400__ods_dashboard/416__ods_dashboard_settings_accelerator_profiles.robot
Labels: verified, new test

#1256 Set namespace for dummy-storage-creds.yaml
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/431__data-science-pipelines-api.robot
Labels: verified, enhancements

#1253 Add test for ELYZA-japanese-Llama-2-7b-instruct
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Files/llm/download_model_in_pvc.yaml
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: verified, new test

#1257 fix: New xpath on model serving runtime selection dropdown
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
Labels: verified

#1261 Add flan-ul test case
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: verified, new test

#1265 For purley Kserv raw deployment teardown will fail when OSSM operator and resources are not deployed
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: enhancements

#1263 add codellama-34b-instruct-hf test
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: verified, new test

#1268 Fix for Multi-Attach error PVC
  ods_ci/tests/Resources/Files/llm/download_model_in_pvc.yaml
Labels: enhancements

#1267 adding TC for llama-2-13b-chat
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: verified, new test

#1274 FIx: Automation Issues from 2.8 RC1 Sanity execution
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsAcceleratorProfiles.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
  ods_ci/tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/423__model_serving_customruntimes.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_other_runtimes_UI.robot
Labels: verified, enhancements

#1272 Add test for deploying and querying a prompt-tuned google/flan-t5-xl LLM
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/download_prompts_in_pvc.yaml
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/Files/llm/serving_runtimes/base/isvc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/base/kustomization.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/overlay/prompt-tuned/kustomization.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/overlay/prompt-tuned/prompt_tuned.yaml
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: verified, new test

#1280 fix: ODS-282 Verify Content In RHODS Explore Section
  ods_ci/tests/Resources/Files/AppsInfoDictionary_latest.json
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements

#1281 adding model-info and tokenize to the TC RHOAIENG-3483
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: verified

#1282 fix: ODS-1226 Open links
  ods_ci/tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, enhancements

#1286 fix: ODS-1718 update endpoint
  ods_ci/tests/Tests/400__ods_dashboard/414__ods_dashboard_api.robot
Labels: verified, enhancements

#1292 fix: get started and cards related tests
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements

#1277 Make feature tests running on GPU and Default Raw
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_tgis.robot
Labels: verified, enhancements

#1294 Fix for model response file
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
Labels: verified, enhancements

#1245 [Fix] Uninstallation of the RHOAI operator
  ods_ci/tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
  ods_ci/tests/Resources/Files/operatorV2/embedded.txt
  ods_ci/tests/Resources/Files/operatorV2/embedded_cs.txt
Labels: verified, enhancements

#1303 fix: Verify successful pipeline via UI from Pipelines->Runs view
  ods_ci/tests/Resources/Page/ODH/JupyterHub/Elyra.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/435__data-science-pipelines-elyra.robot
Labels: verified, enhancements

#1285 Enforce the client to use a valid certificate
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/libs/DataSciencePipelinesKfpTekton.py
Labels: verified, enhancements

#1304 fix: Add productBug tag to ODS-282
  ods_ci/tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, enhancements

#1289 Install Authorino Operator as a prerequisite for RHOAI 2.9+
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Resources/Page/Operators/ISVs.resource
Labels: verified, enhancements

#1301 Fix deletion confirmation message change in RHOAI 2.9.0 Dashboard
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: enhancements

#1307 update ods-ci to use the new hive server
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/create_fips.sh
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/hive_osp_cluster_template.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
  ods_ci/tasks/Tasks/provision_self_managed_cluster.robot
Labels: do not merge

#1308 Fix Dashboard Tests for ODH and RHOAI 2.9
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Page/LoginPage.robot
  ods_ci/tests/Resources/Page/OCPDashboard/Builds/Builds.robot
  ods_ci/tests/Resources/Page/OCPDashboard/OCPMenu.robot
  ods_ci/tests/Resources/Page/OCPDashboard/Pods/Pods.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
  ods_ci/tests/Tests/100__deploy/100__installation/104__dashboard.robot
  ods_ci/tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
  ods_ci/tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  ods_ci/tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
  ods_ci/tests/Tests/500__jupyterhub/image-iteration.robot
  ods_ci/tests/Tests/500__jupyterhub/jupyterhub-user-access.robot
  ods_ci/tests/Tests/500__jupyterhub/multiple-gpus.robot
  ods_ci/tests/Tests/500__jupyterhub/special-user-testing.robot
  ods_ci/tests/Tests/500__jupyterhub/test-jupyterlab-flask-notebook.robot
  ods_ci/tests/Tests/500__jupyterhub/test-jupyterlab-git-notebook.robot
  ods_ci/tests/Tests/500__jupyterhub/test-jupyterlab-notebook.robot
  ods_ci/tests/Tests/500__jupyterhub/test-minimal-image.robot
  ods_ci/tests/Tests/500__jupyterhub/test-pipChanges-not-permanent.robot
  ods_ci/tests/Tests/500__jupyterhub/test-s3-cc-fraud.robot
  ods_ci/tests/Tests/500__jupyterhub/test.robot
  ods_ci/tests/Tests/600__ai_apps/610__ibm_watson_studio/610__ibm_watson_studio.robot
  ods_ci/tests/Tests/600__ai_apps/620__intel_aikit/620__intel_aikit.robot
  ods_ci/tests/Tests/600__ai_apps/640__rhoam/640__rhoam.robot
  ods_ci/tests/Tests/600__ai_apps/660__openvino/660__openvino.robot
Labels: verified, enhancements

#1316 [Fix] request body logged content
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardAPI.resource
Labels: verified, enhancements

#1306 [Fix] Notebook API test
  ods_ci/tests/Tests/400__ods_dashboard/414__ods_dashboard_api.robot
Labels: verified, enhancements

#1322 Migrate to pipeline v2
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/436__test-run-data-science-pipelines-operator-e2e-tests.robot
Labels: enhancements

#1321 Reuse KW `Wait For Dashboard Page Title` in more tests
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsAcceleratorProfiles.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: needs testing, verified, enhancements

#1325 Fix linter errors in DataSciencePipelinesKfp.py and ray_integration.py
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/libs/DataSciencePipelinesKfp.py
  ods_ci/tests/Resources/Files/pipeline-samples/v1/flip_coin.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/ray_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/upload_download.py
Labels: verified, enhancements

#1310 RHOAIENG-3425 - Validate Trusted CA Bundle
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/139__trusted_ca_bundles.robot
Labels: verified, new test

#1328 Migrate to pipeline v2 (DataSciencePipelinesKfp)
  ods_ci/libs/DataSciencePipelinesKfp.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/flip_coin.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/flip_coin_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/ray_integration_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/upload_download_compiled.yaml
Labels: verified, enhancements

#1319 Add support to open also ODH via application list
  ods_ci/tests/Resources/Page/ODH/JupyterHub/LaunchJupyterHub.robot
  ods_ci/tests/Tests/500__jupyterhub/test.robot
Labels: verified, enhancements

#1329 remove clean all unused floating ips
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/create_fips.sh
Labels: verified

#1338 Exclude AI apps tests on ODH since these are irrelevant there
  ods_ci/tests/Tests/600__ai_apps/600__anaconda_commercial_edition/600__anaconda_commercial_edition.robot
  ods_ci/tests/Tests/600__ai_apps/610__ibm_watson_studio/610__ibm_watson_studio.robot
  ods_ci/tests/Tests/600__ai_apps/620__intel_aikit/620__intel_aikit.robot
  ods_ci/tests/Tests/600__ai_apps/640__rhoam/640__rhoam.robot
  ods_ci/tests/Tests/600__ai_apps/640__rhoam/640__rhoam_installation.robot
  ods_ci/tests/Tests/600__ai_apps/660__openvino/660__openvino.robot
  ods_ci/tests/Tests/600__ai_apps/670__pachyderm/670__pachyderm.robot
  ods_ci/tests/Tests/600__ai_apps/680__starburst/680__starburst_galaxy.robot
  ods_ci/tests/Tests/600__ai_apps/680__starburst/682__starburst_enterprise_sm.robot
Labels: enhancements

#1337 Replace black and isort with ruff
  .github/workflows/code_quality.yaml
  ods_ci/selftests/utils/scripts/test_util.py
  ods_ci/utils/scripts/ocm/ocm.py
  poetry.lock
  pyproject.toml
Labels: verified, enhancements
