Repository red-hat-data-services/ods-ci, pull requests merged in 2024-10, with the labels that each got.

#1867 New KW `Wait For Deployment Replica To Be Ready` for oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/OCP.resource
Labels: verified, enhancements, do not merge

#1862 Add ModelRegistry Namespace Check
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: verified, enhancements

#1869 Add initial upgrade testing for Data Science Pipelines
  ods_ci/libs/DataSciencePipelinesKfp.py
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesUpgradeTesting.resource
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Files/pipeline-samples/v2/gpu/pytorch/pytorch_verify_gpu_availability.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/gpu/pytorch/pytorch_verify_gpu_availability_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/take_nap_pipeline_root.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/take_nap_pipeline_root_compiled.yaml
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: new test

#1875 add pre/during/post upgrade tags to be able to use it more efficientl…
  ods_ci/tests/Tests/100__deploy/120__upgrades/120__pre_upgrade.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/121__during_upgrade.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/122__post_ugrade.robot
Labels: verified

#1876 add pre/during/post upgrade tags to be able to use it more efficientl…
  ods_ci/tests/Tests/100__deploy/120__upgrades/120__pre_upgrade.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/121__during_upgrade.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/122__post_ugrade.robot
Labels: verified

#1871 Fix check for nvidia-device-plugin-daemonset when deploying NVIDIA operator stack
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
  ods_ci/tasks/Resources/Provisioning/GPU/provision-gpu.sh
Labels: verified, enhancements

#1881 Shorten the name of a project resource name to pass the check
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects_additional.robot
Labels: verified, enhancements

#1879 Model Registry e2e UI test + breaking ui changes
  ods_ci/tests/Resources/CLI/ModelRegistry/serviceMeshMember_template.yaml
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/1300__model_registry/1302_model_registry_model_serving.robot
Labels: verified, enhancements

#1884 Status for the starting workbench doesn't contain three dots anymore
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#1888 Patch kustomize for GPUs to provision in regions without zones on Azure
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/AZURE/gpu-remove-zone.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/AZURE/gpu.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/AZURE/kustomization.yaml
Labels: verified

#1889 Add 2.14 tgis runtime image
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
Labels: verified, enhancements

#1894 Add new runtime image for vllm
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
Labels: verified, enhancements

#1897 Increase timeout when saving permissions in Dashboard
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Permissions.resource
Labels: verified, enhancements

#1899 Fix the workbench start for the Jupyter 4 (images 2024.2)
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#1898 Dynamically change python target version for MR dependencies
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Tests/1300__model_registry/1301_model_registry_model_serving.robot
Labels: enhancements

#1901 Fix; 11846 user can start stop launch delete workbench
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified

#1904 fix: increase logo's timeout
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements

#1905 [Fix] partially reverts #1901 as we should keep using the library keyword
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
Labels: verified, enhancements

#1906 Backport fix in "Is OpenShift Login Visible" kw to releases/2.11.0
  ods_ci/tests/Resources/Page/LoginPage.robot
Labels: verified, enhancements

#1909 [Fix] the Jupyter tests for working with git repository
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-git.robot
Labels: verified, enhancements

#1908 enhancement: reordering the Operator tests to make sure the disruptive tests are executed at the last place
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0110__service_mesh.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2002__dsc_negative_dependant_operators_not_installed.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: verified

#1916 [Fix] test that checks that Notebook resource has expected size
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/notebook_size_verification.robot
Labels: verified, enhancements

#1912 Fix suite `0401__ods_dashboard` Tests and Keywords
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Files/AppsInfoDictionary_latest.json
  ods_ci/tests/Resources/Page/Components/Menu.robot
  ods_ci/tests/Resources/Page/OCPDashboard/Builds/Builds.robot
  ods_ci/tests/Resources/Page/OCPDashboard/ConfigMaps/ConfigMaps.robot
  ods_ci/tests/Resources/Page/OCPDashboard/ImageStream/ImageStream.robot
  ods_ci/tests/Resources/Page/OCPDashboard/InstalledOperators/InstalledOperators.robot
  ods_ci/tests/Resources/Page/OCPDashboard/InstalledOperators/UninstallODH.robot
  ods_ci/tests/Resources/Page/OCPDashboard/OperatorHub/InstallODH.robot
  ods_ci/tests/Resources/Page/OCPDashboard/OperatorHub/OperatorHub.robot
  ods_ci/tests/Resources/Page/OCPDashboard/Pods/Pods.robot
  ods_ci/tests/Resources/Page/OCPDashboard/Secrets/Secrets.robot
  ods_ci/tests/Resources/Page/ODH/AiApps/Anaconda.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0401__ods_dashboard.robot
Labels: verified, enhancements

#1920 [Fix] the tests for custom image import
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/custom-image.robot
Labels: verified, enhancements

#1922 Fix: Dashboard UI tests
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#1923 [Fix] the test for the package versions on images
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
Labels: verified, enhancements

#1925 fix: skip disruptive operator tests in disconnected environments
  ods_ci/tests/Tests/2001__disruptive_tests/2002__dsc_negative_dependant_operators_not_installed.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: verified

#1929 [Fix] the project selector on the pipelines page
  ods_ci/tests/Tests/0500__ide/0502__ide_elyra.robot
Labels: verified, enhancements

#1924 Remove Deprovision on failure from OCP provisioning task
  ods_ci/tasks/Resources/Provisioning/Hive/deprovision.robot
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
  ods_ci/tasks/Tasks/provision_self_managed_cluster.robot
Labels: verified, enhancements

#1935 Increase timeout for Iris Pipeline
  ods_ci/tests/Tests/1100__data_science_pipelines/1101__data-science-pipelines-kfp.robot
Labels: verified

#1936 Only upload the openshift CA cert if the cluster is self-managed in MR test
  ods_ci/tests/Tests/1300__model_registry/1301_model_registry_model_serving.robot
Labels: enhancements

#1932 Automated test to verify AMD GPU's can be used in Data Science Pipelines
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_amd_gpu_availability.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_amd_gpu_availability_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_nvidia_gpu_availability.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_nvidia_gpu_availability_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_verify_gpu_availability.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_verify_gpu_availability_compiled.yaml
  ods_ci/tests/Tests/1100__data_science_pipelines/1105__data-science-pipelines-gpu.robot
Labels: verified

#1947 Increase timeout when running iris-pipeline in releases/2.13.0
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-kfp.robot
Labels: verified

#1953 Fix: new start and stop wb buttons
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#1954 RHOAIENG-14857 Update the test to implement data-testids
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
Labels: verified, enhancements

#1957 Adds a new tests to check the notebook controllers deployments
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Tests/0500__ide/0500__ide_deployment_cr_checks.robot
Labels: verified, new test

#1955 Remove generation validation from Pipelines Test
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
Labels: verified

#1956 enhancement: adding trustyai coverage for it to be GA in 2.15
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: verified

#1840 Added Tensorflow model REST protocol test on triton for Modelmesh
  ods_ci/tests/Resources/Files/triton/modelmesh-triton-tensorflow-input.json
  ods_ci/tests/Resources/Files/triton/modelmesh-triton-tensorflow-output.json
  ods_ci/tests/Resources/Files/triton/triton_tensorflow_modelmesh_runtime.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/1000__model_serving/1010__model_serving_triton_on_modelmesh/1010__model_serving_triton_on_modelmesh.robot
Labels: verified, new test

#1962 fix: minor fix in deployment command to find replicas
  ods_ci/tests/Resources/OCP.resource
Labels: verified

#1970 Add pre/post upgrade test for Model Registry
  ods_ci/tests/Resources/Page/ModelRegistry/ModelRegistry.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
  ods_ci/tests/Tests/1300__model_registry/1301_model_registry_model_serving.robot
Labels: verified, new test, enhancements

#1971 Fix Pipelines upgrade test
  ods_ci/libs/DataSciencePipelinesKfp.py
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesUpgradeTesting.resource
Labels: verified, enhancements

#1972 Fix Pipelines upgrade test (backport to 2.14.0)
  ods_ci/libs/DataSciencePipelinesKfp.py
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesUpgradeTesting.resource
Labels: enhancements

#1973 Change pipeline in order to make the test also working on airgap environment
  ods_ci/tests/Tests/1100__data_science_pipelines/1102__data-science-pipelines-api.robot
Labels: verified, enhancements

#1937 cherry pick PR #1936 into 2.14 branch
  ods_ci/tests/Tests/1300__model_registry/1301_model_registry_model_serving.robot
Labels: misc

#1978 Fix Pipelines upgrade test (backport to 2.15)
  ods_ci/libs/DataSciencePipelinesKfp.py
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesUpgradeTesting.resource
Labels: verified, enhancements

#1977 Increase timeout when waiting for pipeline server to be created (backport 2.15)
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
Labels: verified, enhancements

#1976 Increase timeout when waiting for pipeline server to be created
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
Labels: verified, enhancements

#1963 fix: add statement to approve the installplan when a new operator is being installed
  ods_ci/tests/Resources/Page/Operators/ISVs.resource
  ods_ci/tests/Tests/2001__disruptive_tests/2002__dsc_negative_dependant_operators_not_installed.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: verified

#1979 Add checks for RHOAIENG-15033 bug in post upgrade scenario
  ods_ci/tests/Resources/Page/ModelRegistry/ModelRegistry.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified, enhancements

#1933 Fix `0410__ods_dashboard_projects` Suite Setup and Tags
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects.robot
Labels: verified, enhancements

#1984 enhancement: move dsc keywords to separate robot file
  ods_ci/tests/Resources/Page/Components/Components.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: verified

#1985 update vllm cuda runtime image based on rc2
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
Labels: verified, enhancements

#1988 cherry pick Model Registry upgrade scenario into releases/2.14.0
  ods_ci/tests/Resources/Page/ModelRegistry/ModelRegistry.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
  ods_ci/tests/Tests/1300__model_registry/1301_model_registry_model_serving.robot
Labels: new test, enhancements

#1989 Increase timeout when waiting for pipeline server to be created (backport to 2.14.0)
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
Labels: enhancements

#1964 RHOAIENG-11849 Refactor is required for edit DSP form
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
Labels: verified, enhancements

#1993 Update images used in the pipeline GPU tests to use RHOAI 2.15 workbench runtimes
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_amd_gpu_availability.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_amd_gpu_availability_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_nvidia_gpu_availability.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_nvidia_gpu_availability_compiled.yaml
Labels: verified, enhancements

#1994 Update images used in the pipeline GPU tests to use RHOAI 2.15 workbench runtimes (backport to releases/2.15.0)
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_amd_gpu_availability.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_amd_gpu_availability_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_nvidia_gpu_availability.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/gpu/pytorch/pytorch_nvidia_gpu_availability_compiled.yaml
Labels: enhancements
