Repository red-hat-data-services/ods-ci, pull requests merged in 2024-12, with the labels that each got.

#2098 [fix] This bumps the expected CUDA version for the workbench images
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-cuda-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-pytorch-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-tensorflow-test.robot
Labels: enhancements

#2099 [fix] This bumps the expected CUDA version for the workbench images
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-cuda-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-pytorch-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-tensorflow-test.robot
Labels: enhancements

#2018 Added FIL model REST protocol test on triton for Kserve
  ods_ci/tests/Resources/Files/triton/kserve-triton-fil-rest-input.json
  ods_ci/tests/Resources/Files/triton/kserve-triton-fil-rest-output.json
  ods_ci/tests/Resources/Files/triton/kserve-triton-keras-rest-input.json
  ods_ci/tests/Resources/Files/triton/triton_onnx_rest_servingruntime.yaml
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve.robot
Labels: verified, new test

#2102 [fix] of the GPU tests for the IDE module
  ods_ci/tests/Resources/Page/ODH/JupyterHub/GPU.resource
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: verified, enhancements

#2105 [fix] of the GPU tests for the IDE module
  ods_ci/tests/Resources/Page/ODH/JupyterHub/GPU.resource
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: verified, enhancements

#2028 Added FIL model GRPC protocol test on triton for Kserve
  ods_ci/tests/Resources/Files/triton/kserve-triton-fil-grpc-input.json
  ods_ci/tests/Resources/Files/triton/kserve-triton-fil-grpc-output.json
  ods_ci/tests/Resources/Files/triton/triton_onnx_gRPC_servingruntime.yaml
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve.robot
Labels: verified, new test

#2134 Replace AMD GPU community operator with RH certified one
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_gpu_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/blacklist_driver.yaml
Labels: verified

#2140 Replace all Xpaths with `pf-v5` to `pf-v6`
  ods_ci/tests/Resources/Page/DistributedWorkloads/WorkloadMetricsUI.resource
  ods_ci/tests/Resources/Page/HybridCloudConsole/HCCLogin.robot
  ods_ci/tests/Resources/Page/OCPDashboard/Page.robot
  ods_ci/tests/Resources/Page/OCPDashboard/Pods/Pods.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0102__billing_metrics.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0404__ods_dashboard_resources.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-distributed-workloads-metrics-ui.robot
  ods_ci/tests/Tests/2000__other_components/600__ai_apps/680__starburst/680__starburst_galaxy.robot
  ods_ci/tests/Tests/2000__other_components/700__sandbox/700__sandbox.robot
Labels: verified, :warning: high priority review

#2142 Fix Dashboard Smoke Tests for RHOAI 2.17
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Permissions.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/0400__ods_dashboard/0401__ods_dashboard.robot
  ods_ci/tests/Tests/1000__model_serving/1003__model_serving_customruntimes.robot
Labels: verified, enhancements

#2144 update the install type to Cli instead of CLi
  ods_ci/rhods_install_configuration.yaml.example
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0110__service_mesh.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: verified

#2152 Fix Dashboard Suites 0408, 0409, 0410 Tests and Keywords
  ods_ci/tests/Resources/CLI/AcceleratorProfiles/AcceleratorProfiles.resource
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Page/Components/Menu.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/Elyra.resource
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/LoginJupyterHub.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsAcceleratorProfiles.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Permissions.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0101__post_install.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0101__metrics.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0102__billing_metrics.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0408__ods_dashboard_settings_pod_tolerations.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0409__ods_dashboard_settings_accelerator_profiles.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects_permissions_mgmt.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/autoscaling-gpus.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/image-iteration.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/long-running-test-generic-ds.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/networkpolicy-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/plugin-verification.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-flask-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-git-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-time.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-minimal-image.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-s3-cc-fraud.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test.robot
Labels: verified, enhancements
