Repository red-hat-data-services/ods-ci, pull requests merged in 2024-11, with the labels that each got.

#1968 Don't fail GPU Operators install script if RHOAI is not present
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
Labels: verified, enhancements

#2010 Add TC Check value for serverless cert on CSV
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0105__serverless_operator/0105__serverless_operator.robot
Labels: needs testing, new test

#2013 [Fix] the modal window checks when stopping a workbench
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#2017 Fix: Dashboard ODS-2206 and ODS-1814
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified

#2004 [2.10.z][fix] Expected string of the final results
  ods_ci/tests/Tests/500__jupyterhub/test-minimal-image.robot
Labels: enhancements

#2003 [2.8.z][fix] Expected string of the final results
  ods_ci/tests/Tests/500__jupyterhub/test-minimal-image.robot
Labels: enhancements

#2019 Update DW-Rocm tag
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-distributed-workloads-tests.robot
Labels: enhancements

#2021 RHAOIENG-15527: enhance ODS-1877 to use data-testid
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
Labels: enhancements

#2022 Fix: Dashboard related model serving issues
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: verified

#2024 Hotfix/validate service mesh control plane already created
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: needs testing, enhancements

#2029 Chore: Added sleep and timeout for while loop
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/Operators/ISVs.resource
Labels: enhancements

#2016 enhancement: improve component readiness check when operator is being installed
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified

#2026 Fix dashboard RBAC issue, fix cli timing issue for Model Registry smoke tests
  ods_ci/tests/Resources/Page/ModelRegistry/ModelRegistry.resource
  ods_ci/tests/Tests/1300__model_registry/1301_model_registry_model_serving.robot
  ods_ci/tests/Tests/1300__model_registry/1302_model_registry_smoke.robot
Labels: verified, enhancements

#2034 fix: new Connection Types feature issues
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects_edit.robot
  ods_ci/tests/Tests/1000__model_serving/1003__model_serving_customruntimes.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1150__data-science-pipelines-ui.robot
Labels: verified, enhancements

#2044 post upgrade starting version check for Model Registry
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: enhancements

#2049 Add new image for runtime in regards to 2.15
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
Labels: verified

#2057 Fix model serving issues in 2.15
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: verified, enhancements

#2039 Add negative test for dashboard RBAC on Model Registry
  ods_ci/tests/Resources/Page/ModelRegistry/ModelRegistry.resource
  ods_ci/tests/Tests/1300__model_registry/1301_model_registry_model_serving.robot
Labels: verified, new test

#2059 RHOAIENG-15919 Refactor to reflect 'create workbench' UI changes
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: enhancements

#2068 Update the way how to remove environment variables for Jupyter ntb
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: verified, enhancements

#2071 fix: use cleanup.sh script to uninstall in sm clusters
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: verified

#2069 Update new runtime imaged based on RC2
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
Labels: verified, enhancements

#2073 Fix dsp post upgrade. Add keyword "Skip If Operator Starting Version Is Not Supported"
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesUpgradeTesting.resource
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified, enhancements

#2072 Add Operator DSC Workbenches Component Tests
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: verified, new test

#2077 RHOAIENG-15919 Refactor to reflect 'create workbench' UI changes (#2059)
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: enhancements

#2070 Added Python model REST protocol test on triton for Modelmesh
  ods_ci/tests/Resources/Files/triton/modelmesh-triton-python-input.json
  ods_ci/tests/Resources/Files/triton/modelmesh-triton-python-output.json
  ods_ci/tests/Resources/Files/triton/triton_onnx_modelmesh_runtime.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/1000__model_serving/1010__model_serving_triton_on_modelmesh/1010__model_serving_triton_on_modelmesh.robot
Labels: verified, new test

#2025 Added Python model gRPC protocol test on triton for Kserve
  ods_ci/tests/Resources/Files/triton/kserve-triton-python-gRPC-input.json
  ods_ci/tests/Resources/Files/triton/kserve-triton-python-gRPC-output.json
  ods_ci/tests/Resources/Files/triton/triton_onnx_gRPC_servingruntime.yaml
  ods_ci/tests/Resources/Page/Components/Menu.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve.robot
Labels: verified, new test

#2009 Added Python model REST protocol test on triton for Kserve
  ods_ci/tests/Resources/Files/triton/kserve-triton-python-rest-input.json
  ods_ci/tests/Resources/Files/triton/kserve-triton-python-rest-output.json
  ods_ci/tests/Resources/Files/triton/triton_onnx_rest_servingruntime.yaml
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve.robot
Labels: verified, new test
