Repository red-hat-data-services/ods-ci, pull requests merged in 2024-05, with the labels that each got.

#1418 [Fix] check for the CUDA version installed on image
  ods_ci/tests/Resources/Page/ODH/JupyterHub/GPU.resource
  ods_ci/tests/Tests/500__jupyterhub/minimal-cuda-test.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
Labels: verified, enhancements

#1417 Update the tgis runtime for rhoai_2_8_z
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
Labels: verified, enhancements, 2.8.z

#1421 Add support to uninstall odh-nightly from managed cluster
  ods_ci/tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/oc_uninstall.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: verified, enhancements

#1420 [fix] Update image used for must-gather test
  ods_ci/tests/Tests/505__must_gather/get-must-gather-logs.sh
Labels: verified, enhancements

#1422 Increase the dsci timeout
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified

#1423 Fix "PLC0415", # `import` should be at the top-level of a file
  ods_ci/libs/Helpers.py
  ods_ci/utils/scripts/read_pr.py
  pyproject.toml
Labels: verified, enhancements

#1434 Include Git mirror details into test-variables.yaml
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: verified

#1424 Fix "F403", # `from python_terraform import *` used; unable to detect undefined names
  ods_ci/utils/scripts/terraform/openstack/provision.py
  pyproject.toml
Labels: verified, enhancements

#1440 Properly set multiline custom CA Bundle
  ods_ci/libs/Helpers.py
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/139__trusted_ca_bundles.robot
Labels: verified

#1447 Parameterize the model deployment for tgis and using ratio to match model response
  ods_ci/libs/Helpers.py
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/serving_runtimes/base/isvc.yaml
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
  poetry.lock
  pyproject.toml
Labels: verified, enhancements

#1448 Add prod bug to tgis metrics test cases
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_UI.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_tgis.robot
Labels: enhancements

#1458 [fix] disable the custom manifest support temporarily
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified

#1456 [fix] two test that starts Standard Data Science workbench on ODH
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#1457 [fix] expected title of the browser window when running with ODH
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, enhancements

#1454 [fix] the expected network policy content for the ODH execution
  ods_ci/tests/Resources/Files/expected_ctrl_np_template.txt
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, enhancements

#1438 Add base test for vLLM and its metrics
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/Files/llm/runtime_query_formats.json
  ods_ci/tests/Resources/Files/llm/vllm/download_model.yaml
  ods_ci/tests/Resources/Files/llm/vllm/vllm-gpt2_inferenceservice.yaml
  ods_ci/tests/Resources/Files/llm/vllm/vllm_servingruntime.yaml
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/ODH/Monitoring/Monitoring.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/vllm/426__model_serving_vllm_metrics.robot
Labels: new test, enhancements

#1459 Add script to fetch new test cases
  ods_ci/utils/scripts/fetch_tests.py
Labels: verified, utils

#1475 [Backport 2.9] Bumping default retry to 150 in Wait Until Operator Subscription Last Condition Is
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Resources/Page/Operators/ISVs.resource
Labels: enhancements

#1474 Add option in fetch_new_test.py to automatically fetch previous release branch
  ods_ci/utils/scripts/fetch_tests.py
Labels: verified, utils

#1480 Moved API to v2beta1
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/431__data-science-pipelines-api.robot
Labels: verified, enhancements

#1478 RHOAIENG-7580 - Add Pod Ready Check
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/142__dsc_components.robot
Labels: enhancements

#1483 Fix "E402", # Module level import not at top of file
  ods_ci/selftests/utils/scripts/conftest.py
  ods_ci/utils/scripts/awsOps.py
  ods_ci/utils/scripts/fetch_tests.py
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/openshift/openshift.py
  ods_ci/utils/scripts/reportportal/rp_uploader.py
  ods_ci/utils/scripts/rosa/rosa.py
  ods_ci/utils/scripts/rosa/rosaOps.py
  ods_ci/utils/scripts/terraform/openstack/provision.py
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
  ods_ci/utils/scripts/util.py
  pyproject.toml
Labels: verified, enhancements

#1481 Refactor Data Science Pipelines to slim down sanity (Sanity on a diet)
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/431__data-science-pipelines-api.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/432__data-science-pipelines-kfp.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/433__data-science-pipelines-general.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/435__data-science-pipelines-elyra.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/436__test-run-data-science-pipelines-operator-e2e-tests.robot
Labels: verified, enhancements

#1492 feat: metrics visualization pipeline
  ods_ci/tests/Resources/Files/pipeline-samples/v2/metrics/metrics_visualization.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/metrics/metrics_visualization_compiled.yaml
Labels: verified
