Repository red-hat-data-services/ods-ci, pull requests merged in 2024-06, with the labels that each got.

#1489 Fix iris-pipeline sample to use the standard_scaler parameter in step normalize_dataset
  ods_ci/tests/Resources/Files/pipeline-samples/v2/iris_pipeline.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/iris_pipeline_compiled.yaml
Labels: enhancements

#1498 Add support for amd operator installation
  ods_ci/tasks/Resources/Provisioning/GPU/amd_operator/amd_gpu_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/amd_operator/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/amd_operator/blacklist_driver.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/amd_operator/kmm_operator_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/gpu_deploy.sh
  ods_ci/tasks/Resources/Provisioning/GPU/nfd_deploy.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/nfd_operator.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/AWS/provision-gpu.sh
Labels: misc

#1502 RHOAIENG-7181 Check DW Components are Enabled by Default
  ods_ci/tests/Tests/100__deploy/100__installation/101__installation.robot
Labels: needs testing, new test

#1496 Fix missing `poetry run` in run_robot_test.sh
  ods_ci/run_robot_test.sh
Labels: enhancements

#1504 [2.8] Add tagger date and version:refname sort attribute for fetching releases branches
  ods_ci/utils/scripts/fetch_tests.py
Labels: utils

#1506 [2.9] Add tagger date and version:refname sort attribute for fetching releases branches
  ods_ci/utils/scripts/fetch_tests.py
Labels: utils

#1510 [fix] must-gather test to use the image targeted for 2.8.3
  ods_ci/tests/Tests/505__must_gather/get-must-gather-logs.sh
Labels: enhancements

#1500 Expanded vLLM metrics test
  ods_ci/libs/Helpers.py
  ods_ci/tests/Resources/Files/llm/vllm/vllm_servingruntime.yaml
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/vllm/426__model_serving_vllm_metrics.robot
Labels: new test, enhancements

#1507 Modify Pipeline UI test in Smoke to use pip_index_url (making it compatible with disconnected clusters)
  ods_ci/test-variables.yml.example
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/configmap-ds-pipeline-custom-env-vars.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/hello_world_pip_index_url.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/hello_world_pip_index_url_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/iris_pipeline_pip_index_url.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/iris_pipeline_pip_index_url_compiled.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
  poetry.lock
  pyproject.toml
Labels: verified, enhancements

#1509 RHOAIENG-7298 - New DSC Component Dashboard and Datasciencepipelines Test Cases
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/142__dsc_components.robot
Labels: verified, new test

#1514 Update installation channel for the authorino dependency operator
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/utils/scripts/ocm/ocm.py
Labels: enhancements

#1511 Add support for embedded endpoint for vllm
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/Files/llm/runtime_query_formats.json
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/vllm/vllm_servingruntime.yaml
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: verified, new test

#1518 fix: wait for kserve inference host via cli
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
Labels: verified, utils

#1515 RHOAIENG-6517 Automate support for configuration of controller resources
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/142__dsc_components.robot
Labels: needs testing, new test

#1523 Small two DS project test fixes/stabilization
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, enhancements

#1524 [fix] close browser after each test in 415__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, enhancements

#1526 [fix] stabilize the ODS-1864 test by scrolling button into view
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#1528 fix: use activeModelState to wait ISVC status
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
Labels: verified, enhancements

#1529 Add Dashboard tag to Dashboard related suites
  ods_ci/tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_settings.robot
  ods_ci/tests/Tests/400__ods_dashboard/411__ods_dashboard_settings_pvc_size.robot
  ods_ci/tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
  ods_ci/tests/Tests/400__ods_dashboard/414__ods_dashboard_api.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_edit.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_notebook_images.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_permissions_mgmt.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_settings_pod_tolerations.robot
  ods_ci/tests/Tests/400__ods_dashboard/416__ods_dashboard_settings_accelerator_profiles.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/423__model_serving_customruntimes.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/424__model_serving_bias_metrics.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_caikit_py_client.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/436__test-run-data-science-pipelines-operator-e2e-tests.robot
Labels: verified, utils

#1531 Add Support for vllm model deployment from UI
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_other_runtimes_UI.robot
Labels: verified, new test

#1482 Remove auth from ray
  ods_ci/tests/Resources/Files/pipeline-samples/v2/ray_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/ray_integration_compiled.yaml
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/432__data-science-pipelines-kfp.robot
Labels: verified, enhancements

#1534 fix: 30s sleep when ISVC is loaded in order to avoid polling treshold
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
Labels: verified, enhancements

#1535 [fix] Update must-gather image reference for the RHOAI 2.10
  ods_ci/tests/Tests/505__must_gather/get-must-gather-logs.sh
Labels: enhancements

#1539 fix: ODS-2574 wrong xpaths
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/424__model_serving_cluster_setting.robot
Labels: verified, enhancements

#1541 fix: Model serving LLM UI tests
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_UI.robot
Labels: verified, enhancements

#1487 ODS-2584 Create DSCI and DSC with Service Mesh operator NOT installed
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/test-variables.yml.example
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/DistributedWorkloads/WorkloadMetricsUI.resource
  ods_ci/tests/Resources/Page/Operators/ISVs.resource
  ods_ci/tests/Resources/ServiceMesh.resource
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/140__service_mesh.robot
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/143__dsc_negative_no_servicemesh_op.robot
  ods_ci/utils/scripts/fetch_tests.py
Labels: needs testing, new test

#1546 Fixed minor typo in the pipelines path
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
Labels: enhancements

#1547 granite and llam3 model
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
Labels: verified

#1549 Simplify pipeline setting pip_index_url and pip_trusted_host
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/flip_coin_pip_index_url.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/flip_coin_pip_index_url_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/hello_world_pip_index_url.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/hello_world_pip_index_url_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/iris_pipeline_pip_index_url.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/iris_pipeline_pip_index_url_compiled.yaml
Labels: verified, enhancements

#1533 Add SeaLights integration files and deps. Configure SonarCloud inclusions/exclusions
  .sonarcloud.properties
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/utils/scripts/sealights/README.md
  ods_ci/utils/scripts/sealights/SLListener.py
  ods_ci/utils/scripts/sealights/SLTagsListener.py
  poetry.lock
  pyproject.toml
Labels: verified, misc

#1551 Fix: Wait properly for KServe models (backport from Master)
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
Labels: verified, enhancements

#1548 Add embedding model deployment from ui for vllm
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_http.yaml
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_other_runtimes_UI.robot
Labels: verified, new test

#1552 fix: Dashboard tests diet
  ods_ci/tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  ods_ci/tests/Tests/400__ods_dashboard/411__ods_dashboard_settings_pvc_size.robot
  ods_ci/tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
  ods_ci/tests/Tests/400__ods_dashboard/413__ods_dashboard_user_mgmt.robot
  ods_ci/tests/Tests/400__ods_dashboard/414__ods_dashboard_api.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_permissions_mgmt.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/423__model_serving_customruntimes.robot
Labels: verified, enhancements

#1557 Add sleep to ovms test, skip fail if UWM configmaps already present
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/425__model_serving_ovms_on_kserve.robot
Labels: enhancements

#1558 Set default SR for Kserve to Caikit+TGIS
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: enhancements

#1559 Force Caikit TGIS SR in UI tests
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_UI.robot
Labels: enhancements

#1553 Move Serving and Pipelines suites out of Dashboard folder
  ods_ci/tests/Tests/1000__model_serving/1001__model_serving_modelmesh.robot
  ods_ci/tests/Tests/1000__model_serving/1002__model_serving_modelmesh_gpu.robot
  ods_ci/tests/Tests/1000__model_serving/1003__model_serving_customruntimes.robot
  ods_ci/tests/Tests/1000__model_serving/1004__model_serving_bias_metrics.robot
  ods_ci/tests/Tests/1000__model_serving/1005__model_serving_cluster_setting.robot
  ods_ci/tests/Tests/1000__model_serving/1006__model_serving_ovms_on_kserve.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_caikit_py_client.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_UI.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_other_runtimes_UI.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_tgis.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_tgis_object_storages.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1008__model_serving_vllm/1008__model_serving_vllm_metrics.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-api.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-elyra.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-general.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-kfp.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-ui.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__test-run-data-science-pipelines-operator-e2e-tests.robot
  ods_ci/tests/Tests/400__ods_dashboard/401__ods_dashboard.robot
  ods_ci/tests/Tests/400__ods_dashboard/402__ods_dashboard_settings.robot
  ods_ci/tests/Tests/400__ods_dashboard/403__ods_dashboard_settings_pvc_size.robot
  ods_ci/tests/Tests/400__ods_dashboard/404__ods_dashboard_resources.robot
  ods_ci/tests/Tests/400__ods_dashboard/405__ods_dashboard_user_mgmt.robot
  ods_ci/tests/Tests/400__ods_dashboard/406__ods_dashboard_api.robot
  ods_ci/tests/Tests/400__ods_dashboard/407__ods_custom_docs.robot
  ods_ci/tests/Tests/400__ods_dashboard/408__ods_dashboard_settings_pod_tolerations.robot
  ods_ci/tests/Tests/400__ods_dashboard/409__ods_dashboard_settings_accelerator_profiles.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_edit.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_notebook_images.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_permissions_mgmt.robot
Labels: verified, misc, :warning: high priority review

#1540 Update amd script
  ods_ci/tasks/Resources/Provisioning/GPU/amd_operator/amd_operator.sh
Labels: verified, utils

#1530 RHOAIENG-8546 - Platform DSC Modelmeshserving Test Case
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/142__dsc_components.robot
Labels: verified, new test

#1564 [vllm/tgis]Add support for amd for model deployment
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
Labels: verified, enhancements

#1556 RHOAIENG-3472: Added test to validate the DSC without dependant operator when kserver is unmanaged
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/143__dsc_negative_dependant_operators_not_installed.robot
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/143__dsc_negative_no_servicemesh_op.robot
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/144_dsc_negative_no_dependant_op.robot
Labels: verified

#1576 Adapt Data Science Pipelines tests to changes introduced by Pipeline Experiments
  ods_ci/libs/DataSciencePipelinesKfp.py
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Tests/500__ide/502__ide_elyra.robot
Labels: verified, enhancements
