Repository red-hat-data-services/ods-ci, pull requests merged in 2024-01, with the labels that each got.

#1089 Workaround for old Hive with Openstack
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
Labels: verified, enhancements

#1085 Keywords for management of components
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Tests/650__distributed_workloads/test-run-codeflare-tests.robot
  ods_ci/tests/Tests/650__distributed_workloads/test-run-dw-tests.robot
Labels: verified, enhancements

#1098 Add `__init__.py` files in `utils/` to mark directories as Python packages in PyCharm
  ods_ci/__init__.py
  ods_ci/utils/__init__.py
  ods_ci/utils/scripts/Sender/__init__.py
  ods_ci/utils/scripts/__init__.py
  ods_ci/utils/scripts/ocm/__init__.py
  ods_ci/utils/scripts/openshift/__init__.py
  ods_ci/utils/scripts/polarion/__init__.py
  ods_ci/utils/scripts/reportportal/__init__.py
  ods_ci/utils/scripts/terraform/__init__.py
  ods_ci/utils/scripts/terraform/openstack/__init__.py
  ods_ci/utils/scripts/testconfig/__init__.py
Labels: utils

#1090 Add support to validate gpu driver ,demonset etc validator pod verifcation after NFD resource are created
  ods_ci/tasks/Resources/Provisioning/GPU/gpu_deploy.sh
Labels: verified

#1097 RHODS-13159: Use the new parameter 'base_domain' in ods-ci
  ods_ci/docs/infrastructure_configuration_variables.md
  ods_ci/tasks/Resources/Provisioning/Hive/AWS/aws-cluster.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GCP/gcp-cluster.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/create_fips.sh
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/hive_osp_cluster_template.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
Labels: verified, enhancements

#1101 New Test ODS-2223
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Resources/Page/OCPDashboard/UserManagement/Groups.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Permissions.resource
  ods_ci/tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_permissions_mgmt.robot
Labels: verified, new test

#1103 Verify GPU AcceleratorProfile is created after restarting Dashboard
  ods_ci/tasks/Resources/Provisioning/GPU/gpu_deploy.sh
Labels: verified, new test

#1104 ODS-1975 - Verify user can cancel workbench start from event log [AUTOMATION]
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, new test

#1046 [RHOAIENG-125] ODS CI tests which run Kuberay E2E
  ods_ci/tests/Tests/650__distributed_workloads/test-run-kuberay-e2e.robot
Labels: verified

#1109 Flip coin pipeline compiled
  ods_ci/tests/Resources/Files/pipeline-samples/flip_coin_compiled.py.yaml
Labels: enhancements

#1108 Wait for GPU Operator Subscription, InstallPlan & Deployment
  ods_ci/tasks/Resources/Provisioning/GPU/gpu_deploy.sh
Labels: verified

#1114 Fix: 2.6 xpath fixes
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#1117 Fix "Click Action From Actions Menu" and CustomServingRuntime test
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: needs testing, enhancements

#1075 Add e2e test for Caikit Nlp Client
  ods_ci/tests/Resources/CLI/ModelServing/caikit-py-query.ipynb
  ods_ci/tests/Resources/CLI/ModelServing/gen_client_certs.sh
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_caikit_py_client.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm_UI.robot
Labels: verified, new test

#1123 Patternfly changes for gpu model serving
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/421__model_serving_gpu.robot
Labels: verified, enhancements

#1113 Fix ODS-2206, ODS-2226 for ODH 2.6
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: verified, enhancements

#1119 Improve the code quality ruff action
  .github/workflows/code_quality.yaml
Labels: verified, utils

#1107 Test Automation ODS-2173 Verify user can create a workbench using Intel AiKit image
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_notebook_images.robot
Labels: needs testing, new test

#1126 Fix pf5 xpaths for `Verify User Can Create And Start A Workbench Adding A New PV Storage`
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
Labels: verified, enhancements

#1127 Move LLM CLI tests from Smoke to Sanity
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
Labels: enhancements

#1125 Fix model serving tests in 2.6
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/422__model_serving_llm_UI.robot
Labels: verified, enhancements

#1130 Fix projects page selector path
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
Labels: verified, enhancements

#1129 Remove ODS-1005(KFDEF) TC from the repo
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/139__rhods_kfdef_event.robot
Labels: verified, enhancements

#1112 [RHOAIENG-1574] - Add codeflare-sdk e2e tests
  ods_ci/tests/Tests/650__distributed_workloads/test-run-codeflare-sdk-e2e-tests.robot
Labels: verified, new test

#1128 Check for pre-created virtual environment to save time on repeated poetry installs
  ods_ci/run_robot_test.sh
Labels: verified, utils, do not merge

#1138 Update RHOAI display name
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified

#1131 Enhance "Verify That XXXXXX Image Is A CPaaS Built Image" tests
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
Labels: verified, enhancements

#1124 Add automated test for TGIS Standalone serving runtime (gRPC CLI)
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/Files/llm/runtime_query_formats.json
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/isvc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_caikit_py_client.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_UI.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422_model_serving_llm_other_runtimes.robot
Labels: verified, new test

#1142 Add javascrit to click the radio button
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified

#1134 Rename `Force Tags` to `Test Tags` due to deprecation
  ods_ci/tests/Tests/500__jupyterhub/custom-image.robot
  ods_ci/tests/Tests/500__jupyterhub/image-iteration.robot
  ods_ci/tests/Tests/500__jupyterhub/jupyterhub-user-access.robot
  ods_ci/tests/Tests/500__jupyterhub/long-running-test-generic-ds.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-cuda-test.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-pytorch-test.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-tensorflow-test.robot
  ods_ci/tests/Tests/500__jupyterhub/multiple-gpus.robot
  ods_ci/tests/Tests/500__jupyterhub/multiple-image-tags.robot
  ods_ci/tests/Tests/500__jupyterhub/networkpolicy-test.robot
  ods_ci/tests/Tests/500__jupyterhub/notebook_size_verification.robot
  ods_ci/tests/Tests/500__jupyterhub/plugin-verification.robot
  ods_ci/tests/Tests/500__jupyterhub/special-user-testing.robot
  ods_ci/tests/Tests/500__jupyterhub/test-filling-pvc.robot
  ods_ci/tests/Tests/500__jupyterhub/test-jupyterlab-flask-notebook.robot
  ods_ci/tests/Tests/500__jupyterhub/test-jupyterlab-git-notebook.robot
  ods_ci/tests/Tests/500__jupyterhub/test-jupyterlab-notebook.robot
  ods_ci/tests/Tests/500__jupyterhub/test-pipChanges-not-permanent.robot
  ods_ci/tests/Tests/500__jupyterhub/test-s3-cc-fraud.robot
  ods_ci/tests/Tests/500__jupyterhub/test-versions.robot
  ods_ci/tests/Tests/500__jupyterhub/test.robot
  ods_ci/tests/Tests/800__culler/culler.robot
Labels: misc

#1135 Add support for self-signed certificates
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: verified, enhancements

#1147 Fix for RHOAM check of the tile on the Explore page
  ods_ci/tests/Tests/600__ai_apps/640__rhoam/640__rhoam.robot
Labels: verified, enhancements

#1145 Give a bit more time to load the UI elements for DS project page tests
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
Labels: verified, enhancements

#1133 Add RHOSi Setup and RHOSi Teardown in all test suites of distributed workloads
  ods_ci/tests/Tests/650__distributed_workloads/test-run-codeflare-tests.robot
  ods_ci/tests/Tests/650__distributed_workloads/test-run-dw-tests.robot
  ods_ci/tests/Tests/650__distributed_workloads/test-run-kuberay-e2e.robot
Labels: verified, enhancements

#1141 Add test to verify Dashboard detects OpenShift Pipelines operator
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/Operators/OpenShiftPipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/430__data-science-pipelines-operator-dependency.robot
Labels: verified, new test

#1137 Declare and use `currentpath` and `basepath` constants in shell script
  ods_ci/run_robot_test.sh
Labels: verified, utils

#1152 Remove busybox workaround for ray
  ods_ci/tests/Resources/Files/pipeline-samples/ray_integration.py
Labels: enhancements

#1132 Fix: Dashboard automation errors for 2.6 pt1
  ods_ci/tests/Resources/Page/OCPDashboard/UserManagement/Groups.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Permissions.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ResourcesPage.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, enhancements

#1150 Adjust tests for Kuberay 1.0
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Tests/650__distributed_workloads/test-run-kuberay-e2e.robot
Labels: verified, enhancements

#1154 Fix timing issue when logging into OpenShift. Remove deprecated jupyter test
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Page/LoginPage.robot
  ods_ci/tests/Resources/Page/OCPDashboard/OCPMenu.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Tests/500__jupyterhub/test.robot
Labels: verified, enhancements

#1143 Fix library versions tests
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
Labels: verified, enhancements

#1155 Trivial logging update attempt and increase of timeout
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
Labels: enhancements, do not merge

#1151 Add UI testing for TGIS Standalone
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/ODH/Monitoring/Monitoring.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_other_runtimes_UI.robot
Labels: verified, new test

#1153 Update CA_BUNDLE whenever we create DS pipeline server
  ods_ci/libs/Helpers.py
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: verified, enhancements

#1159 Fix the broken dryrun tests with Trusty deployment
  ods_ci/tests/Tests/100__deploy/100__installation/111__trustyai.robot
  ods_ci/tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
Labels: enhancements

#1164 Revert "[Fix] attempt to stabilize the `Logged Into OpenShift` test (…
  ods_ci/tests/Resources/Page/LoginPage.robot
Labels: verified, enhancements

#1163 Increase timeout for DSPO reconciliation retry
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/431__data-science-pipelines-api.robot
Labels: verified, enhancements

#1162 Add take-nap example pipeline
  ods_ci/tests/Resources/Files/pipeline-samples/take_nap.py
  ods_ci/tests/Resources/Files/pipeline-samples/take_nap_compiled.yaml
Labels: verified, misc

#1157 Fix broken sanity tests + Add skip wait option in test teardown in model serving
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/423__model_serving_customruntimes.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/424_model_serving_bias_metrics.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm.robot
Labels: verified, enhancements

#1166 Fix CI ruff check for the `take_nap.py` file recently added
  ods_ci/tests/Resources/Files/pipeline-samples/take_nap.py
Labels: enhancements

#1167 Updating incorrect variable syntax metrics
  ods_ci/tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
Labels: enhancements

#1148 Add Kueue tests
  ods_ci/tests/Tests/650__distributed_workloads/test-run-kueue-e2e-tests.robot
Labels: verified, new test

#1169 Use must-gather with sha256 digest
  ods_ci/tests/Tests/505__must_gather/get-must-gather-logs.sh
Labels: verified, enhancements

#1172 Enhancements for Trusty Tests
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/424__model_serving_bias_metrics.robot
Labels: enhancements
