Repository red-hat-data-services/ods-ci, pull requests merged in 2024-08, with the labels that each got.

#1677 RHOAIENG-10534: make branch name determination in run_robot_test.sh more reliable
  ods_ci/run_robot_test.sh
Labels: verified

#1672 Fix Python selftests on macOS by using portable shell commands only
  ods_ci/selftests/utils/scripts/test_util.py
Labels: verified

#1684 Enable public endpoint by default for kserve models deployed via UI
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: verified, enhancements

#1666 Add data science project creation deletion keywords. Modify Elyra test suite to use them
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Tests/500__ide/502__ide_elyra.robot
Labels: verified, enhancements

#1688 [releases/2.10.0] RHOAIENG-10534: look for branch-specific poetry .venv (#1669) (cherry picked from commit d09c4d3)
  .editorconfig
  ods_ci/run_robot_test.sh
  ods_ci/selftests/utils/scripts/conftest.py
  ods_ci/selftests/utils/scripts/test_util.py
Labels: verified

#1686 [releases/2.8.0] RHOAIENG-10534: look for branch-specific poetry .venv (#1669) (cherry picked from commit d09c4d3)
  .editorconfig
  ods_ci/run_robot_test.sh
  ods_ci/selftests/utils/scripts/test_util.py
Labels: verified, 2.8.z

#1689 [releases/2.11.0] RHOAIENG-10534: look for branch-specific poetry .venv (#1669) (cherry picked from commit d09c4d3)
  .editorconfig
  ods_ci/run_robot_test.sh
  ods_ci/selftests/utils/scripts/conftest.py
  ods_ci/selftests/utils/scripts/test_util.py
Labels: verified

#1690 Add support for rhelai granite-7b-redhat-lab
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
Labels: verified, new test

#1691 Add azure among supported test env for rhoai install
  ods_ci/tasks/Tasks/rhods_olm.robot
Labels: verified, enhancements

#1695 Make memory request tunable for pvc download pod
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/download_model_in_pvc.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/1000__model_serving/1006__model_serving_ovms_on_kserve_cli.robot
Labels: verified, enhancements

#1697 First step to fixing Model Serving Llm/ Verify User Can Serve And Query A Model With Token and Model Serving Llm Tgis/ Verify User Can Serve And Query A Model With Token
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_tgis.robot
Labels: enhancements

#1703 fix: Component Status kw tolerant to not present components
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified

#1707 Add automationBug tag to ODS2206
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-ui.robot
Labels: enhancements

#1710 fix: solve issue with flaky test about serverless resources
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0105__serverless_operator/0105__serverless_operator.robot
Labels: verified

#1709 Fix Dashboard Sanity and Tier1 Tests on RHOAI 2.12
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Files/AppsInfoDictionary_latest.json
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Resources/Page/Components/Menu.robot
  ods_ci/tests/Resources/Page/LoginPage.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsAcceleratorProfiles.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Permissions.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Tests/400__ods_dashboard/401__ods_dashboard.robot
  ods_ci/tests/Tests/400__ods_dashboard/402__ods_dashboard_settings.robot
  ods_ci/tests/Tests/400__ods_dashboard/404__ods_dashboard_resources.robot
  ods_ci/tests/Tests/400__ods_dashboard/405__ods_dashboard_user_mgmt.robot
  ods_ci/tests/Tests/400__ods_dashboard/407__ods_custom_docs.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_edit.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_notebook_images.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_permissions_mgmt.robot
Labels: verified, enhancements

#1713 update new runtime images based on Rc2
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/ovms_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_http.yaml
Labels: enhancements

#1717 fix: add pod ready conditions when installing dependant operators to solve flaky issues in SNO scenarios
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0114__dsc_negative_dependant_operators_not_installed.robot
Labels: verified

#1716 General fixes for UI Keywords in RHOAI 2.12
  ods_ci/tests/Resources/Page/LoginPage.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/1000__model_serving/1002__model_serving_modelmesh_gpu.robot
  ods_ci/tests/Tests/1000__model_serving/1003__model_serving_customruntimes.robot
  ods_ci/tests/Tests/1000__model_serving/1004__model_serving_cluster_setting.robot
  ods_ci/tests/Tests/1000__model_serving/1005__model_serving_ovms_on_kserve.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_other_runtimes_UI.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-ui.robot
  ods_ci/tests/Tests/1200__ai_explainability/1201__model_serving_bias_metrics.robot
  ods_ci/tests/Tests/1200__ai_explainability/1202__saliency_explainers.robot
  ods_ci/tests/Tests/400__ods_dashboard/405__ods_dashboard_user_mgmt.robot
  ods_ci/tests/Tests/400__ods_dashboard/406__ods_dashboard_api.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_edit.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_notebook_images.robot
  ods_ci/tests/Tests/400__ods_dashboard/410__ods_dashboard_projects/410__ods_dashboard_projects_permissions_mgmt.robot
  ods_ci/tests/Tests/500__ide/502__ide_elyra.robot
  ods_ci/tests/Tests/600__ai_apps/680__starburst/682__starburst_enterprise_sm.robot
  ods_ci/tests/Tests/650__distributed_workloads/test-distributed-workloads-metrics-ui.robot
Labels: verified, enhancements

#1719 fix: solve service mesh state unmanaged test failures
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0110__service_mesh.robot
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0111__trusted_ca_bundles.robot
Labels: verified

#1729 [fix] Expected string of the final results
  ods_ci/tests/Tests/500__ide/501__ide_jupyterhub/test-minimal-image.robot
Labels: verified, enhancements

#1732 fix the deployment parameter for Model serving
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: enhancements

#1720 fix: solve must gather test issues
  ods_ci/tests/Resources/CLI/MustGather/MustGather.resource
  ods_ci/tests/Resources/CLI/MustGather/get-must-gather-logs.sh
  ods_ci/tests/Tests/0100__platform/0103__must_gather/test-must-gather-logs.robot
Labels: verified

#1722 RHOAIENG-10404 - Add Operator ModelRegistry Component Test Cases
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: needs testing, new test

#1731 Fix Test `Verify Documentation Links HTTP Status Code`
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  ods_ci/tests/Tests/400__ods_dashboard/401__ods_dashboard.robot
Labels: verified, enhancements

#1734 Rename some root suite directories to reflect new scrum org
  ods_ci/tests/Tests/0400__ods_dashboard/0401__ods_dashboard.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0402__ods_dashboard_settings.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0403__ods_dashboard_settings_pvc_size.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0404__ods_dashboard_resources.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0405__ods_dashboard_user_mgmt.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0406__ods_dashboard_api.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0407__ods_custom_docs.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0408__ods_dashboard_settings_pod_tolerations.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0409__ods_dashboard_settings_accelerator_profiles.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects_edit.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects_notebook_images.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects_permissions_mgmt.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/autoscaling-gpus.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/base-user-shutdown-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/custom-image.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/image-iteration.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/jupyterhub-user-access.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/long-running-test-generic-ds.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-cuda-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-pytorch-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-tensorflow-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-vscode-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/multiple-gpus.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/multiple-image-tags.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/networkpolicy-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/notebook_size_verification.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/odh_jh_global_profile.sh
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/plugin-verification.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/special-user-testing.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-filling-pvc.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-folder-permissions.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-flask-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-git-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-git.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-time.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-minimal-image.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-pipChanges-not-permanent.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-s3-cc-fraud.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-uninstall.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-versions.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test.robot
  ods_ci/tests/Tests/0500__ide/0502__ide_elyra.robot
  ods_ci/tests/Tests/0500__ide/0503__ide_anaconda_professional.robot
  ods_ci/tests/Tests/0500__ide/0504__ide_intel_aikit.robot
  ods_ci/tests/Tests/0500__ide/0505__ide_openvino.robot
  ods_ci/tests/Tests/0500__ide/0506__ide_ibm_watson_studio.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-distributed-workloads-metrics-ui.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-codeflare-sdk-e2e-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-codeflare-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-kuberay-e2e.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-kueue-e2e-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-tuning-stack-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-smoke.robot
Labels: verified, enhancements

#1738 Fix "SKIPPED" status in Post upgrade suite
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: needs testing, enhancements

#1740 Add support for provisioning GPUs on Azure
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/AZURE/gpu.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/AZURE/kustomization.yaml
Labels: verified, new task

#1736 RHOAIENG-7217 KServe and KServe.Serving management states
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0105__serverless_operator/0105__serverless_operator.robot
Labels: new test, enhancements

#1741 v2.12 Disable Platform ModeRegistry Tests On RHOAI
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: enhancements

#1743 Create root suite directory for unassigned components and move culler suite under IDE
  ods_ci/tests/Tests/0500__ide/0507__culler/culler.robot
  ods_ci/tests/Tests/2000__other_components/600__ai_apps/640__rhoam/640__rhoam.robot
  ods_ci/tests/Tests/2000__other_components/600__ai_apps/640__rhoam/640__rhoam_installation.robot
  ods_ci/tests/Tests/2000__other_components/600__ai_apps/670__pachyderm/670__pachyderm.robot
  ods_ci/tests/Tests/2000__other_components/600__ai_apps/680__starburst/680__starburst_galaxy.robot
  ods_ci/tests/Tests/2000__other_components/600__ai_apps/680__starburst/682__starburst_enterprise_sm.robot
  ods_ci/tests/Tests/2000__other_components/700__sandbox/700__sandbox.robot
  ods_ci/tests/Tests/2000__other_components/700__sandbox/701__performance_sandbox.robot
  ods_ci/tests/Tests/2000__other_components/700__sandbox/olm.yaml
  ods_ci/tests/Tests/2000__other_components/900__high_availability/900__openshift/900__openshift.robot
Labels: enhancements

#1747 Disable Platform ModeRegistry Tests On RHOAI - Fix Tag Name
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: enhancements

#1749 Disable ModelRegistry Tests On RHOAI
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: verified, enhancements

#1751 Check KServer Managment State To Ensure That It Is Not Empty
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0105__serverless_operator/0105__serverless_operator.robot
Labels: enhancements

#1756 [fix] xpaths to couple of elements in dashboard data science projects
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#1754 Fix keyword to watch SM cluster provisioning logs and increase timeout
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
Labels: verified, enhancements

#1755 Fix "Verify User Can Access Model Metrics From UWM" test in "Model Serving Llm" suite
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/serving_runtimes/base/isvc.yaml
Labels: verified

#1750 Added new tests to validate release.name and release.version attributes of a dsc/dsci
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0108__operator.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified

#1737 Added onnx model REST protocol test on triton
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Files/triton/kserve-triton-onnx-rest-input.json
  ods_ci/tests/Resources/Files/triton/kserve-triton-onnx-rest-output.json
  ods_ci/tests/Resources/Files/triton/triton_onnx_rest_servingruntime.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/1000__model_serving/1001__model_serving_modelmesh.robot
  ods_ci/tests/Tests/1000__model_serving/1003__model_serving_customruntimes.robot
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve.robot
Labels: verified, new test

#1763 [fix] xPaths with regards the change in RHOAI 2.13
  ods_ci/tests/Resources/Page/DistributedWorkloads/WorkloadMetricsUI.resource
  ods_ci/tests/Tests/0500__ide/0502__ide_elyra.robot
Labels: verified, enhancements
