Repository red-hat-data-services/ods-ci, pull requests merged in 2024-02, with the labels that each got.

#1170 Fix test some LLM UI tests from Smoke
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_other_runtimes_UI.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422_model_serving_llm_other_runtimes.robot
Labels: verified, enhancements

#1173 [Fix] Workbenches - fix file upload for env variables section
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
Labels: verified, enhancements

#1050 [Fix] for the window title to accomodate with RHOAI 2.5
  ods_ci/tests/Tests/700__sandbox/700__sandbox.robot
Labels: enhancements

#1096 Update defaults for test variables generation.
  ods_ci/utils/scripts/testconfig/README.md
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: verified, utils

#1179 Add log gather when pod doesn't get ready by timeout
  ods_ci/tests/Resources/OCP.resource
Labels: verified, enhancements

#1177 [Fix] wait for the RHOAI/ODH operator CSV to be in state condition Su…
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified, enhancements

#1187 Fix for the wait of the CatalogSource to be in Ready state
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified, enhancements

#1185 New Tests in Model Serving: Verify changes to existing model resources
  ods_ci/tests/Resources/Page/Components/Menu.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/100__deploy/120__upgrades/120__pre_upgrades.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/122__post_ugrade.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/421__model_serving_gpu.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/424__model_serving_bias_metrics.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_UI.robot
Labels: verified, new test, enhancements

#1189 Fix data science pipeline tests in Smoke due to changes related to pipeline versions
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/430__data-science-pipelines-operator-dependency.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/431__data-science-pipelines-api.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/432__data-science-pipelines-tekton.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/433__data-science-pipelines-general.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/435__data-science-pipelines-elyra.robot
Labels: verified, enhancements

#1190 Remove managed starburst files
  ods_ci/tasks/Resources/SERH_OLM/install.resource
  ods_ci/tasks/Tasks/deploy_managed_starburst.robot
  ods_ci/tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/600__ai_apps/680__starburst/681__managed_starburst.robot
  ods_ci/tests/Tests/600__ai_apps/680__starburst/681__managed_starburst_monitoring.robot
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
  ods_ci/utils/scripts/testconfig/test-variables.yml
Labels: verified, enhancements

#1144 Run pipeline upstream tests in ods-ci
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/436__test-run-data-science-pipelines-operator-e2e-tests.robot
Labels: verified, new test

#1195 Another fix to `Wait Until Csv Is Ready` keyword
  ods_ci/tests/Resources/Common.robot
Labels: verified, :warning: high priority review

#1118 Pin Python version to 3.11
  .github/workflows/code_quality.yaml
  .github/workflows/dry_run.yml
  README.md
  ods_ci/run_robot_test.sh
  ods_ci/utils/scripts/Sender/EmailSender.py
  ods_ci/utils/scripts/Sender/Sender.py
  poetry.lock
  pyproject.toml
Labels: needs testing, utils

#1182 Update runtime yamls
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
Labels: verified, enhancements

#1202 remove managed starburst
  ods_ci/tasks/Resources/SERH_OLM/install.resource
  ods_ci/tasks/Tasks/deploy_managed_starburst.robot
  ods_ci/tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/600__ai_apps/680__starburst/681__managed_starburst.robot
  ods_ci/tests/Tests/600__ai_apps/680__starburst/681__managed_starburst_monitoring.robot
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
  ods_ci/utils/scripts/testconfig/test-variables.yml
Labels: enhancements

#1194 Add tests for OVMS on Kserve
  ods_ci/libs/Helpers.py
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/421__model_serving_gpu.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/425__model_serving_ovms_on_kserve.robot
Labels: verified, new test

#1200 Revert "Add support for kueue component whihc got added in 2.7"
  ods_ci/tasks/Resources/Files/dsc_template.yml
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: do not merge

#1205 Verify Pipeline Run Is Completed
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
Labels: needs testing, enhancements

#1203 Fix 'Clean All Models Of Current User' KW
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: verified, enhancements

#1211 Fix modelmesh suite, add test for productbug RHOAIENG-2869
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
Labels: needs testing, new test, enhancements

#1216 Update ODS-CI image with Python version arg = 3.11
  ods_ci/build/Dockerfile
Labels: verified, enhancements

#1212 Add OVMS on Kserve GPU test
  ods_ci/tests/Resources/Page/ODH/Monitoring/Monitoring.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/421__model_serving_gpu.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/425__model_serving_ovms_on_kserve.robot
Labels: verified, new test

#1102 [RHOAIENG-223] Test VSCode - add checks for VS Code image
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_notebook_images.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-vscode-test.robot
Labels: verified, new test

#1226 Fix Custom Serving Runtime sanity tests
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/423__model_serving_customruntimes.robot
Labels: needs testing, enhancements

#1220 Automated test for checking the input for duplicated pipeline run
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
Labels: verified, new test

#1225 Add error message and continue on failure of bug RHOAIENG-404
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements

#1228 [Fix] jupyter notebook spawn checks
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
Labels: verified, enhancements

#1180 RHOAIENG-23 - Cleanup CodeFlare installation code
  ods_ci/tasks/Resources/Files/codeflare_sub_template.yaml
  ods_ci/tasks/Resources/RHODS_OLM/RHODS_OLM.resource
  ods_ci/tasks/Resources/RHODS_OLM/install/codeflare_install.resource
  ods_ci/tasks/Resources/RHODS_OLM/install/install.robot
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/codeflare_uninstall.resource
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tasks/Tasks/rhods_olm.robot
  ods_ci/tests/Tests/650__distributed_workloads/test-run-dw-tests.robot
Labels: enhancements

#1231 Add TGIS test for fetching model from Minio object storage
  ods_ci/tests/Resources/CLI/Minio.resource
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/minio/minio.yaml
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_tgis_object_storages.robot
Labels: verified, new test

#1232 fix rosa deployment
  ods_ci/libs/Helpers.py
  ods_ci/utils/scripts/awsOps.py
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/rosa/rosa.py
  ods_ci/utils/scripts/rosa/rosaOps.py
Labels: utils
