Repository red-hat-data-services/ods-ci, pull requests merged in 2024-04, with the labels that each got.

#1333 `Open Data Science Project Details Page` also switch to a requested tab
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Permissions.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_edit.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_notebook_images.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_permissions_mgmt.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/423__model_serving_customruntimes.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/424__model_serving_cluster_setting.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_caikit_py_client.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/435__data-science-pipelines-elyra.robot
Labels: verified, enhancements

#1340 Update new runtime image for tgis with snyk fixes
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
Labels: verified, enhancements

#1343 [RHOAIENG-5073] Add pod port fowarding for raw due to headless service
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_tgis.robot
Labels: verified, enhancements

#1344 Update dashboard tests "415"
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_permissions_mgmt.robot
Labels: verified, enhancements

#1336 RHOAIENG-2519 Service Mesh Test Case
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/139__trusted_ca_bundles.robot
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/140__service_mesh.robot
Labels: verified, new test

#1259 RHOAIENG-2508 ODS-2600 Validate DSC creates all Serverless CRs
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/130__rhods_operator.robot
  ods_ci/tests/Tests/100__deploy/130__operators/140__serverless_operator/140__serverless_operator.robot
  ods_ci/tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: needs testing, new test

#1346 RHOAIENG-5092 - Validate Authorino Resources
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/140__service_mesh.robot
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/141__authorino.robot
Labels: verified, new test

#1345 Update Keywords for the new UI: Test suite 420__model_serving.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: verified, enhancements

#1348 Another 2.8 backport changes
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/create_fips.sh
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/139__trusted_ca_bundles.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_tgis.robot
  ods_ci/tests/Tests/650__distributed_workloads/test-run-codeflare-tests.robot
Labels: 2.8.z

#1350 Update Xpath data-testid for Jupyter Explorer Card
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements

#1335 Add Provisioning ability for IBM Cloud Self-managed
  ods_ci/infrastructure_configuration.yaml.example
  ods_ci/tasks/Resources/Provisioning/Hive/IBM/ibmcloud-cluster.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/deprovision.robot
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
  ods_ci/tasks/Tasks/provision_self_managed_cluster.robot
Labels: verified, new task

#1353 Fix "F811", # Redefinition of unused `hide_values_in_op_json` from line 565
  ods_ci/utils/scripts/ocm/ocm.py
  pyproject.toml
Labels: enhancements

#1354 Fix "W605", # Invalid escape sequence: `\d`
  ods_ci/libs/Helpers.py
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/openshift/openshift.py
  pyproject.toml
Labels: enhancements

#1352 Add common KW `Open "Get Started" For App Name`
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements

#1359 Configure include and exclude paths for ruff linter
  .github/workflows/code_quality.yaml
  pyproject.toml
Labels: utils

#1357 Fix "RET503", # Missing explicit `return` at the end of function able to return non-`None` value
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/utils/scripts/awsOps.py
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/rosa/rosaOps.py
  pyproject.toml
Labels: enhancements

#1360 Revert "Fix "RET503", # Missing explicit `return` at the end of funct…
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/utils/scripts/awsOps.py
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/rosa/rosaOps.py
  pyproject.toml
Labels: enhancements, misc, :warning: high priority review

#1358 Enhance Pipelines UI tests for DSPv2 and add some example pipelines
  ods_ci/tests/Resources/Files/pipeline-samples/v1/pipeline-versions/version_test.py
  ods_ci/tests/Resources/Files/pipeline-samples/v1/pipeline-versions/version_test_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v1/pipeline-versions/version_test_v2.py
  ods_ci/tests/Resources/Files/pipeline-samples/v1/pipeline-versions/version_test_v2_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v1/pipeline-versions/version_test_v3.py
  ods_ci/tests/Resources/Files/pipeline-samples/v1/pipeline-versions/version_test_v3_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/iris_pipeline.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/iris_pipeline_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pipeline-versions/version_test.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pipeline-versions/version_test_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pipeline-versions/version_test_v2.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pipeline-versions/version_test_v2_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pipeline-versions/version_test_v3.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pipeline-versions/version_test_v3_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/take_nap.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/take_nap_compiled.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/433__data-science-pipelines-general.robot
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
Labels: verified, enhancements

#1341 Add ruff to pre-commit
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: utils

#1362 fix: Delete outdated skipped tests
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
  ods_ci/tests/Tests/100__deploy/100__installation/103__grafana.robot
  ods_ci/tests/Tests/100__deploy/100__installation/103__post_install_monitoring_port_forwarding.robot
  ods_ci/tests/Tests/100__deploy/100__installation/108__jupyterhub.robot
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/132__traefik-proxy_restart_verification.robot
  ods_ci/tests/Tests/200__monitor_and_manage/200__metrics/200__metrics.robot
  ods_ci/tests/Tests/200__monitor_and_manage/210__alerts/210__alerts.robot
  ods_ci/tests/Tests/400__ods_dashboard/400__ods_dashboard.robot
Labels: verified, enhancements

#1361 fix: Delete AutomationBug tag from ODS-2379
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_tgis.robot
Labels: verified, enhancements

#1366 Speed-up execution of keyword "Is RHODS Self-Managed" in local
  ods_ci/tests/Resources/OCP.resource
Labels: verified, enhancements

#1349 Fail fast for `poetry install` command
  ods_ci/run_robot_test.sh
Labels: misc

#1364 Add ibmcloud among supported platform for RHOAI install task
  ods_ci/tasks/Tasks/rhods_olm.robot
Labels: verified, enhancements

#1371 In RHOAI 2.9, the number of containers for envoy increased
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: enhancements

#1369 Fix "RET503", # Missing explicit return at the end of function able…
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/utils/scripts/awsOps.py
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/rosa/rosaOps.py
  pyproject.toml
Labels: verified, enhancements

#1374 "B007", # Loop control variable `retry` not used within loop body
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/polarion/xunit_add_properties.py
  pyproject.toml
Labels: verified, enhancements

#1372 Change `IBM Watson Studio` to `IBM watsonx.ai` title in 2.9+
  ods_ci/tests/Tests/600__ai_apps/610__ibm_watson_studio/610__ibm_watson_studio.robot
Labels: verified, enhancements

#1363 Dashboard Sanity tests fixes for RHOAI 2.9
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardResources.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Storages.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ResourcesPage.resource
  ods_ci/tests/Tests/400__ods_dashboard/412__ods_dashboard_resources.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_custom_docs.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_notebook_images.robot
Labels: verified, enhancements

#1375 Fix "PLR5501", # Use `elif` instead of `else` then `if`, to reduce indentation
  ods_ci/libs/Helpers.py
  ods_ci/utils/scripts/ocm/ocm.py
  pyproject.toml
Labels: verified, enhancements

#1379 Refine `execute_command` function for printing aligned tabbed tables
  ods_ci/selftests/utils/scripts/test_util.py
  ods_ci/utils/scripts/util.py
Labels: verified, utils

#1383 fix: ODS-1814 wrong xpath
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, enhancements

#1378 Migrate pipelines tests to DSPv2
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/433__data-science-pipelines-general.robot
Labels: verified, enhancements

#1384 fix: ODS-2054 issues
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: verified, enhancements

#1380 Adapt Trusted CA bundles tests to ODH
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/139__trusted_ca_bundles.robot
  ods_ci/tests/Tests/100__deploy/130__operators/140__serverless_operator/140__serverless_operator.robot
Labels: needs testing, enhancements

#1368 Verify That There Are No Sample Pipelines After Creating Pipeline Server in RHOAI
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/434__data-science-pipelines-ui.robot
Labels: verified, enhancements

#1387 Fix required xpaths for the selection of the model server template
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: enhancements

#1388 fix: ODS-2276 and ODS-2279 issues
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
Labels: verified, enhancements

#1381 Fix and exclude some tests in smoke for odh compatibility
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Tests/100__deploy/100__installation/102__post_install.robot
  ods_ci/tests/Tests/200__monitor_and_manage/200__metrics/201__billing_metrics.robot
  ods_ci/tests/Tests/505__must_gather/test-must-gather-logs.robot
Labels: verified, enhancements

#1390 Fix Canary rollout and non-admin test case in Caikit+TGIS suite (Sanity)
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm.robot
Labels: verified, enhancements

#1393 Fix expected version of Jupyterhub-git package for 2024.1 images
  ods_ci/tests/Tests/500__jupyterhub/test-versions.robot
Labels: verified, enhancements

#1391 Add self-signed CA bundle support for kserve grpc/http requests
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
Labels: needs testing, enhancements

#1394 Fixing Automation For Elyra Test in Dspv2
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/430__data_science_pipelines/435__data-science-pipelines-elyra.robot
Labels: verified, enhancements

#1398 Rhoaieng 6358 restore custom ca bundle
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/139__trusted_ca_bundles.robot
Labels: enhancements

#1313 Add ODH support in ODS_CI tests
  ods_ci/tasks/Resources/Files/dsci_template.yml
  ods_ci/tasks/Resources/Files/odh_catalogsource.yml
  ods_ci/tasks/Resources/Files/odh_nightly_sub.yml
  ods_ci/tasks/Resources/RHODS_OLM/install/cs_template.yaml
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/oc_uninstall.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tasks/Tasks/rhods_olm.robot
  ods_ci/test-variables.yml.example
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/OCP.resource
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
  ods_ci/utils/scripts/testconfig/test-variables.yml
Labels: needs testing

#1403 fix: ODS-2542 outdated xpaths
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettingsRuntimes.resource
Labels: verified, enhancements

#1405 Fix odh-nightly on managed cluster
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified

#1401 RHOAIENG-6358 custom ca bundle save
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/139__trusted_ca_bundles.robot
Labels: verified

#1400 Add check on containers list for KServe model deployments
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/runtime_query_formats.json
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_UI.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_models.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_other_runtimes_UI.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422__model_serving_llm_tgis.robot
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/LLMs/422_model_serving_llm_other_runtimes.robot
Labels: verified, new test, enhancements

#1406 Update Serving Runtime images for API testing
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
Labels: verified, enhancements

#1402 Fix/420 model serving dashboard tests
  ods_ci/tests/Resources/CLI/DSProjects/DSProjects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/400__ods_dashboard/420__model_serving/420__model_serving.robot
Labels: verified, enhancements

#1407 Remove workaround needed for self-signed S3
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: enhancements

#1410 Migrate the code to the latest changes in DW
  ods_ci/tests/Resources/Files/pipeline-samples/v2/ray_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/ray_integration_compiled.yaml
Labels: verified, enhancements

#1295 RHOAIENG-4500 Model registry Operator Deployment
  ods_ci/tests/Tests/100__deploy/100__installation/112__model_registry.robot
Labels: verified, new test

#1413 Fix: GPU related tests
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/400__ods_dashboard/415__ods_dashboard_projects/415__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/500__jupyterhub/minimal-cuda-test.robot
Labels: verified, enhancements
