Repository red-hat-data-services/ods-ci, pull requests merged in 2024-09, with the labels that each got.

#1768 Backport ROSA HCP support in releases/2.10.0
  ods_ci/tasks/Tasks/rhods_olm.robot
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
  ods_ci/utils/scripts/util.py
Labels: enhancements

#1639 Allow to install gpu-operator-certified in disconnected env
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/nfd_deploy.yaml
Labels: verified

#1770 Fix for Authorino TC
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_tgis.robot
Labels: verified

#1767 Refactor Data Science Pipelines Backend Tests introducing new keywords
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
  ods_ci/tests/Resources/Files/pipeline-samples/v2/dspa/data-science-pipelines-reconciliation.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/dspa/data-science-pipelines-sample.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/dspa/dspa-template.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/dspa/dummy-storage-creds.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
  ods_ci/tests/Tests/0500__ide/0502__ide_elyra.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-api.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-general.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-kfp.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-ui.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__test-run-data-science-pipelines-operator-e2e-tests.robot
Labels: verified, enhancements

#1765 Fix `Verify User Can Change The Minimum Number Of Replicas For A Model` test case in ods-ci
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_tgis.robot
Labels: enhancements

#1773 Fix variable evaluation in "Verify Model Inference" and associated keywords
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/1000__model_serving/1001__model_serving_modelmesh.robot
Labels: verified, enhancements

#1771 Fix JupyterHub tag in special-user-testing test suite
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/special-user-testing.robot
Labels: enhancements

#1744 caikit standalone embeddings test endpoints for kserve
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/runtime_query_formats.json
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_standalone_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_standalone_servingruntime_http.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_caikit_embeddings.robot
Labels: verified, new test

#1782 Fix wrong argument in test case, missing argument in keyword call (deployment_mode)
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/1000__model_serving/1006__model_serving_ovms_on_kserve_cli.robot
Labels: verified, enhancements

#1785 fix: add rhosi setup as a requirement for post-upgrade setup
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified

#1781 Add additional params for object storage configuration in CreatePipelineServer, fixing tests on disconnected
  ods_ci/libs/DataSciencePipelinesKfp.py
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
  ods_ci/tests/Resources/Files/pipeline-samples/v2/dspa/dspa-template.yaml
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-api.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-general.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-kfp.robot
Labels: verified, enhancements

#1778 Use single tier/gate tag, fix robocop complaints in Model Serving Test Suites
  ods_ci/tests/Tests/1000__model_serving/1001__model_serving_modelmesh.robot
  ods_ci/tests/Tests/1000__model_serving/1002__model_serving_modelmesh_gpu.robot
  ods_ci/tests/Tests/1000__model_serving/1003__model_serving_customruntimes.robot
  ods_ci/tests/Tests/1000__model_serving/1004__model_serving_cluster_setting.robot
  ods_ci/tests/Tests/1000__model_serving/1005__model_serving_ovms_on_kserve.robot
  ods_ci/tests/Tests/1000__model_serving/1006__model_serving_ovms_on_kserve_cli.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_caikit_py_client.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_kserve_metrics.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_UI.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_other_runtimes_UI.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_tgis.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_tgis_object_storages.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1008__model_serving_vllm/1008__model_serving_vllm_metrics.robot
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve.robot
Labels: enhancements

#1791 Fix pipeline server creation when url ends with /
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
Labels: verified, enhancements

#1777 Added onnx model Modelmesh test on triton
  ods_ci/tests/Resources/Files/triton/kserve-triton-onnx-rest-output.json
  ods_ci/tests/Resources/Files/triton/modelmesh-triton-onnx-rest-output.json
  ods_ci/tests/Resources/Files/triton/triton_onnx_modelmesh_runtime.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/1000__model_serving/1010__model_serving_triton_on_modelmesh/1010__model_serving_triton_on_modelmesh.robot
Labels: verified, new test

#1796 Increase Trusted CA Bundle Resource Check Timeouts
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0111__trusted_ca_bundles.robot
Labels: enhancements

#1799 fix: remove flaky condition to avoid false negative results for the rhods log test
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0108__rhods_operator_logs_verification.robot
Labels: verified

#1801 fix: DSProjects view wrong xpath
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
Labels: verified, enhancements

#1797 RHOAIENG-12725 - Trusted CA Bundle Namespace Exclusion
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0111__trusted_ca_bundles.robot
Labels: verified, new test

#1795 Bump kfp to 2.9.0 and kfp-kubernetes to 1.3.0
  ods_ci/libs/DataSciencePipelinesKfp.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/flip_coin.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/flip_coin_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/importer_pipeline_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/iris_pipeline.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/iris_pipeline_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/iris_pipeline_without_cache.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/iris_pipeline_without_cache_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/metrics/metrics_visualization.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/metrics/metrics_visualization_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/flip_coin_pip_index_url.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/flip_coin_pip_index_url_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/hello_world_pip_index_url.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/hello_world_pip_index_url_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/iris_pipeline_pip_index_url.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/iris_pipeline_pip_index_url_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pipeline-versions/version_test_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pipeline-versions/version_test_v2_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pipeline-versions/version_test_v3_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/ray_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/ray_integration_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/take_nap_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/take_nap_pipeline_root_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/upload_download.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/upload_download_compiled.yaml
  poetry.lock
  pyproject.toml
Labels: needs testing, do not merge

#1816 Add test for CVE-2024-7557
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/ModelServer.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/1000__model_serving/1008_model_serving_cross_auth.robot
Labels: verified, new test, enhancements

#1808 (2.13 backport) RHOAIENG-12725 - Trusted CA Bundle Namespace Exclusion
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0111__trusted_ca_bundles.robot
Labels: verified

#1809 RHOAIENG-12833 - Validate Image Pull Path Is From registry.redhat.io
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: verified, enhancements

#1820 Increase cluster provisioning timeout
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
Labels: enhancements

#1827 (2.13 backport) RHOAIENG-12833 - Validate Image Pull Path Is From registry.redhat.io
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: verified

#1828 Enhance kfp client keywords and add basic DSP acceptance test suite
  ods_ci/libs/DataSciencePipelinesAPI.py
  ods_ci/libs/DataSciencePipelinesKfp.py
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesBackend.resource
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/hello_world_pip_index_url.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/pip_index_url/hello_world_pip_index_url_compiled.yaml
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-acceptance.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1101__data-science-pipelines-kfp.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1102__data-science-pipelines-api.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1103__data-science-pipelines-project-sharing.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1110__test-run-data-science-pipelines-operator-e2e-tests.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1150__data-science-pipelines-ui.robot
Labels: verified, enhancements

#1837 Update button xpath to work with latest ODH
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
Labels: enhancements

#1822 RHOAIENG-13014 - Rewrite Verify RHODS Operator Logs test
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0108__rhods_operator_logs_verification.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1102__data-science-pipelines-api.robot
Labels: verified

#1838 Updating Model Registry E2E Test to Use the Latest Python Client
  ods_ci/tests/Resources/CLI/ModelRegistry/MRMS_TEST_RUNNER.ipynb
  ods_ci/tests/Tests/1300__model_registry/1302_model_registry_model_serving.robot
Labels: verified, enhancements

#1847 add pre/during/post upgrade tags to be able to use it more efficientl…
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified

#1848 add pre/during/post upgrade tags to be able to use it more efficientl…
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified

#1849 add pre/during/post upgrade tags to be able to use it more efficientl…
  ods_ci/tests/Tests/100__deploy/120__upgrades/120__pre_upgrade.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/121__during_upgrade.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/122__post_ugrade.robot
Labels: verified

#1850 add pre/during/post upgrade tags to be able to use it more efficientl…
  ods_ci/tests/Tests/100__deploy/120__upgrades/120__pre_upgrade.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/121__during_upgrade.robot
  ods_ci/tests/Tests/100__deploy/120__upgrades/122__post_ugrade.robot
Labels: verified

#1855 fix: include model registry condition to wait for ready
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified

#1762 Automate Validate ServiceMeshControlPlaneAlreadyCreated Test Case
  ods_ci/tasks/Resources/Files/smcp_template.yml
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0110__service_mesh.robot
Labels: needs testing, new test

#1859 Introduce support for the Jupyter/Elyra 4.
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/Elyra.resource
  ods_ci/tests/Resources/Page/ODH/JupyterHub/Icons.resource
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/PageInfo.resource
  poetry.lock
  pyproject.toml
Labels: verified, enhancements

#1831 RHOAIENG-12022 - Enable DSC Modelregistry Tests To Run On RHOAI
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: enhancements
