Repository red-hat-data-services/ods-ci, pull requests merged in 2024-07, with the labels that each got.

#1568 Generalize GPU provisioning script to ease the addition of new providers
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_gpu_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/blacklist_driver.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/kmm_operator_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/provision-gpu.sh
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/base/kustomization.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/base/source-machineset.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/AWS/gpu.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/AWS/kustomization.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/IBM/gpu.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/IBM/kustomization.yaml
Labels: verified, utils

#1575 Move ai explainability suite in dedicated directory
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Tests/1000__model_serving/1004__model_serving_cluster_setting.robot
  ods_ci/tests/Tests/1000__model_serving/1005__model_serving_ovms_on_kserve.robot
  ods_ci/tests/Tests/1200__ai_explainability/1201__model_serving_bias_metrics.robot
Labels: verified, misc

#1585 Update rhoai 2.11 runtime images
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/vllm/vllm_servingruntime.yaml
Labels: verified

#1584 Check that the URL list is not empty before verifying HTTP status
  ods_ci/tests/Resources/Common.robot
Labels: verified, enhancements

#1578 Backport GPU provisioning updates to releases/2.10.0
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_gpu_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/blacklist_driver.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/kmm_operator_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/provision-gpu.sh
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/base/kustomization.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/base/source-machineset.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/AWS/gpu.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/AWS/kustomization.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/IBM/gpu.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/IBM/kustomization.yaml
Labels: enhancements

#1587 Update NFD operator files in releases/2.8.0
  ods_ci/tasks/Resources/Provisioning/GPU/nfd_deploy.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/nfd_operator.yaml
Labels: verified

#1320 [RHOAIENG-4501] Model Registry Integration Tests with Jupyter Notebook
  ods_ci/tests/Resources/CLI/ModelRegistry/NotebookIntegration.ipynb
  ods_ci/tests/Resources/CLI/ModelRegistry/mnist.onnx
  ods_ci/tests/Resources/CLI/ModelRegistry/samples/mysql/kustomization.yaml
  ods_ci/tests/Resources/CLI/ModelRegistry/samples/mysql/modelregistry_v1alpha1_modelregistry.yaml
  ods_ci/tests/Resources/CLI/ModelRegistry/samples/mysql/mysql-db.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/1300__model_registry/1301__model_registry_jupyter_notebook.robot
Labels: needs testing, new test, do not merge

#1574 RHOAIENG-2512: Added test to validate the DSC and DSCI when Serverless operator is not installed
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/143__dsc_negative_dependant_operators_not_installed.robot
Labels: verified

#1583 RHOAIENG-7919 Istio Kserve Gateway For Internal Endpoint
  ods_ci/tests/Tests/100__deploy/130__operators/140__serverless_operator/140__serverless_operator.robot
Labels: verified

#1591 [releases/2.10.0] RHOAIENG-2512: Added test to validate the DSC and DSCI when Serverless operator is not installed
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/143__dsc_negative_dependant_operators_not_installed.robot
Labels: verified

#1600 Use installer container to retrieve hive logs
  ods_ci/tasks/Resources/Provisioning/Hive/provision.robot
Labels: verified

#1595 KFP as a smoke test
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-kfp.robot
Labels: enhancements

#1586 Add new vllm runtime to fix RHOAIENG-9343
  ods_ci/tests/Resources/Files/llm/serving_runtimes/overlay/vllm/env_param.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/vllm/vllm_servingruntime.yaml
Labels: verified

#1605 No cache for iris pipelines steps and pipeline_root
  ods_ci/tests/Resources/Files/pipeline-samples/v2/iris_pipeline_without_cache.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/iris_pipeline_without_cache_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/take_nap_pipeline_root.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/take_nap_pipeline_root_compiled.yaml
Labels: enhancements

#1604 RHOAIENG-9488 - Add support for control plane node count and flavour …
  ods_ci/tasks/Resources/Provisioning/Hive/OSP/hive_osp_cluster_template.yaml
Labels: do not merge

#1622 Fix relative path for robot test script in Dockerfile
  ods_ci/build/Dockerfile
Labels: verified

#1627 Fix relative path for REDHAT_OPENSHIFT_PIPELINES_YAML
  ods_ci/tests/Resources/Page/Operators/OpenShiftPipelines.resource
Labels: verified, enhancements

#1563 Add support for ovms cli test-case
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/serving_runtimes/ovms_servingruntime_http.yaml
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/1000__model_serving/1006__model_serving_ovms_on_kserve_cli.robot
Labels: verified

#1642 Fix fetching of Dashboard URL
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: verified, enhancements

#1644 Backport Fix fetching of Dashboard URL to releases/2.8.0
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: enhancements

#1645 Backport Fix fetching of Dashboard URL to releases/2.10.0
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: enhancements

#1648 Add annotation so that model can be downloaded without any issue
  ods_ci/tests/Resources/Files/llm/bucket_secret.yaml
Labels: enhancements

#1649 Fix snyk ignore configuration
  .snyk
Labels: misc

#1646 Backport Fix fetching of Dashboard URL to releases/2.11.0
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: enhancements

#1650 update TGIS image for 2.8.4
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
Labels: verified

#1656 [vLLM] Add test for speculative decoding [ngram]
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/Files/llm/serving_runtimes/isvc/kustomization.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/overlay/speculative/kustomization.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/overlay/speculative/patch.yaml
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
Labels: verified

#1658 [vLLM] Add support for multi modal inference (vision language models)
  ods_ci/tests/Resources/Files/llm/model_expected_responses.json
  ods_ci/tests/Resources/Files/llm/serving_runtimes/overlay/vision/kustomization.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/overlay/vision/patch.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_http.yaml
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
Labels: verified, new test

#1663 Add basic TC for kserve Perf metrics
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_kserve_metrices.robot
Labels: verified

#1662 Fix: ODS 2206 wrong xpaths
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: verified, enhancements

#1667 Fix KW `Clean Up DSP Page`
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
Labels: verified, enhancements

#1660 fix: remove warns from rosa list versions command to avoid issues
  ods_ci/utils/scripts/rosa/rosa.py
Labels: verified

#1668 Workaround for Poetry urllib3 connection error
  ods_ci/run_robot_test.sh
Labels: verified

#1673 fix: use common vars in the operator dependant tests to be able to run in both ODH/RHOAI
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/100__deploy/130__operators/130__rhods_operator/143__dsc_negative_dependant_operators_not_installed.robot
Labels: verified

#1676 Update oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: enhancements

#1678 Add support for llama3.1 and rhel ai model
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/vllm_servingruntime_http.yaml
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
Labels: verified, new test
