Repository red-hat-data-services/ods-ci, pull requests merged in 2025-01, with the labels that each got.

#2158 Skip FMS Training operator tests for version less than 2.12.0
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2161 [2.16] Skip FMS Training operator tests for version less than 2.12.0
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2163 Add Monitoring Tag to Test Cases
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0101__metrics.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0102__billing_metrics.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0103__check_pager_duty.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
Labels: lgtm

#2139 Update AMD Operator and NFD install scripts
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/install_nfd.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/nfd_deploy.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/nfd_operator.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
Labels: verified, enhancements

#2165 enhancement: add monitoring test to check targets are up and running
  ods_ci/tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0101__metrics.robot
Labels: verified, lgtm, approved

#2160 Update DW UI tests to align with the latest Dashboard UI improvements
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Page/DistributedWorkloads/WorkloadMetricsUI.resource
  ods_ci/tests/Tests/0600__distributed_workloads/test-distributed-workloads-metrics-ui.robot
Labels: lgtm

#2168 Backport "Update AMD Operator and NFD install scripts (#2139)" in releases/2.16.0
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/install_nfd.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/nfd_deploy.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/nfd_operator.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
Labels: enhancements, lgtm

#2170 Backport "Update AMD Operator and NFD install scripts (#2139)" in releases/2.8.0
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/install_nfd.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/nfd_deploy.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/nfd_operator.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
Labels: enhancements, lgtm

#2171 Backport "Update AMD Operator and NFD install scripts (#2139)" in releases/2.10.0
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/install_nfd.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/nfd_deploy.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/nfd_operator.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
Labels: enhancements, lgtm

#2155 Migration of Python model kserve grpc testcase UI -> API
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Files/llm/serving_runtimes/triton_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/triton/kserve-triton-python-grpc-input.json
  ods_ci/tests/Resources/Files/triton/kserve-triton-python-grpc-output.json
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve_api.robot
Labels: lgtm

#2176 Migration of Onnx model kserve Rest testcase UI -> API
  ods_ci/tests/Resources/Files/triton/kserve-triton-onnx-rest-output.json
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve.robot
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve_api.robot
Labels: lgtm

#2177 [fix] tests for the BYON feature
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/custom-image.robot
Labels: verified, enhancements, lgtm

#2172 Migration of Pytorch Rest Protocol test on triton for Kserve (UI -> API)
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve_api.robot
Labels: lgtm

#2167 Default GPU node replicas to 1 avoiding 0 nodes in SNO clusters
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/install_nfd.sh
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/AWS/gpu.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/GCP/attach-gpu-to-n1/gpu.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/GCP/gpu.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GPU/overlays/IBM/gpu.yaml
Labels: verified, enhancements, lgtm

#2180 update text-generation-inference image sha
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
Labels: verified, lgtm

#2174 [2.16][fix] the Verify Notebook Has Not Restarted upgrade test
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2173 [fix] the Verify Notebook Has Not Restarted upgrade test
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified, enhancements, lgtm

#2175 enhancement: add monitoring test to check rhoai dashboard metrics by code
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0101__metrics.robot
Labels: lgtm

#2182 Migration of Keras Rest Protocol test on triton for Kserve (UI -> API)
  ods_ci/tests/Resources/Files/triton/kserve-triton-keras-rest-input.json
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve_api.robot
Labels: lgtm

#2184 Update Codeflare SDK release tag for 2.17 release
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration_compiled.yaml
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2185 [2.12][fix] the Verify Notebook Has Not Restarted upgrade test
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified, enhancements, lgtm

#2188 [2.15][fix] the Verify Notebook Has Not Restarted upgrade test
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified, enhancements, lgtm

#2187 [2.14][fix] the Verify Notebook Has Not Restarted upgrade test
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified, enhancements, lgtm

#2186 [2.13][fix] the Verify Notebook Has Not Restarted upgrade test
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterLabLauncher.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified, enhancements, lgtm

#2164 Update KFTO multi-node test names according to recent updates in orig…
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-training-stack-tests.robot
Labels: lgtm

#2193 Migration of Dali model kserve Rest testcase UI -> API
  ods_ci/tests/Resources/Files/triton/kserve-triton-dali-rest-input.json
  ods_ci/tests/Resources/Files/triton/kserve-triton-dali-rest-output.json
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve_api.robot
Labels: lgtm

#2189 Onboard ODS-CI testing on OpenShift CI
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2195 Upgrade fms-hf-tuning image to 2.5.0
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2196 Add option in ocm.py script to just check if the cluster exists
  ods_ci/utils/scripts/ocm/ocm.py
Labels: lgtm

#2198 update KFTO tests to utilise storage bucket in case of disconnected e…
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-training-stack-tests.robot
Labels: lgtm
