Repository red-hat-data-services/ods-ci, pull requests merged in 2025-04, with the labels that each got.

#2333 model server: move to backend tests in pre/post upgrade
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified, lgtm, approved

#2348 model server: move to backend tests in pre/post upgrade
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified, lgtm

#2346 model server: move to backend tests in pre/post upgrade
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified, lgtm

#2351 Skip Training operator smoke check for RHOAI < 2.19.0
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-smoke.robot
Labels: lgtm

#2354 Implement additional waiting for Kueue deployment
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kuberay-e2e.robot
Labels: lgtm

#2349 model server: move to backend tests in pre/post upgrade
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: verified, lgtm

#2355 RHOAIENG-22958 - Remove DW downstream tests for Python 3.9
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0600__distributed_workloads/0601__workloads_orchestration/test-run-codeflare-sdk-e2e-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-distributed-workloads-tests_3.9.robot
Labels: lgtm

#2359 [2.19] RHOAIENG-22958 - Remove DW downstream tests for Python 3.9
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0600__distributed_workloads/0601__workloads_orchestration/test-run-codeflare-sdk-e2e-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-distributed-workloads-tests_3.9.robot
Labels: lgtm

#2352 Install Authorino from stable channel for both RHOAI (>= 2.20) and ODH
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified, lgtm

#2363 [2.19.0] Use latest CUDA Training image
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2360 Add Auth CRD Test Case
  ods_ci/tests/Tests/0100__platform/0101__deploy/0102__auth_providers_and_rbac/0103__auth_crd.robot
Labels: lgtm

#2358 Update the connection creation based on the UI changes in RHOAI 2.19
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/0500__ide/0502__ide_elyra.robot
Labels: verified, enhancements, lgtm, approved

#2365 Backport/add auth crd tc
  ods_ci/tests/Tests/0100__platform/0101__deploy/0102__auth_providers_and_rbac/0103__auth_crd.robot
Labels: lgtm

#2366 [2.19] Update the connection creation based on the UI changes in RHOAI 2.19
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/0500__ide/0502__ide_elyra.robot
Labels: lgtm

#2356 fix: add some fixes to the kserve serving remove test to match new conditions
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0105__serverless_operator/0105__serverless_operator.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2002__dsc_negative_dependant_operators_not_installed.robot
Labels: verified, lgtm

#2371 cherry-pick: Add separate tags for Training Ray and Training kubeflow team
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kft-sdk.robot
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kuberay-e2e.robot
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-training-stack-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-tuning-stack-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-smoke.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-distributed-workloads-metrics-ui.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-distributed-workloads-tests.robot
Labels: lgtm

#2368 Add new images for ovms and caikit tgis runtime for 2.19
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/ovms_servingruntime_http.yaml
Labels: verified, lgtm

#2374 Improve Component Should Be Enabled robustness
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: lgtm

#2375 Added Vllm image for RHOAI 2.19
  ods_ci/tests/Resources/Files/llm/vllm/vllm_servingruntime.yaml
Labels: verified, lgtm, approved

#2377 Fix pipeline ui test for changes introduced in RHOAI 2.19
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: verified, enhancements, lgtm

#2378 Fix pipeline ui test for changes introduced in RHOAI 2.19 (backport)
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: verified, enhancements, lgtm

#2380 patch ODS_VENV variable for Openshift-CI testing - RHOAI 2.8
  ods_ci/build/Dockerfile_interop
Labels: lgtm

#2383 Add Kubeflow training image env variable in KFTO-SDK test
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kft-sdk.robot
Labels: lgtm

#2385 Add debugging kws to randomly failig trusted ca bundles managed tc
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0111__trusted_ca_bundles.robot
Labels: lgtm

#2376 Backport : Added Vllm image for RHOAI 2.19
  ods_ci/tests/Resources/Files/llm/vllm/vllm_servingruntime.yaml
Labels: verified

#2384 fix: Verify Dashbord has no message with NO Component Found
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0101__post_install.robot
Labels: lgtm

#2379 patch ODS_VENV variable for Openshift-CI testing - RHOAI 2.16
  ods_ci/build/Dockerfile_interop
Labels: lgtm

#2392 fix the data id selector for the connection selection for RHOAI 2.20+
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: verified, enhancements, lgtm

#2395 [model server]Fix test for upgrade
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm, approved

#2274 enhancement: add new feastoperator component as part of ODH and rhoai 2.20
  ods_ci/tasks/Resources/Files/dsc_template.yml
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/test-variables.yml.example
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: verified, lgtm

#2394 RHOAIENG-23478:Fix 'Verify Auth Crd' test to pass on ODH
  ods_ci/tests/Tests/0100__platform/0101__deploy/0102__auth_providers_and_rbac/0103__auth_crd.robot
Labels: lgtm, jira/valid-reference

#2398 Fixes for Interop testing - Release 2.8
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2396 Fixes for Interop testing - Release 2.18
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2397 Fixes for Interop testing - Release 2.16
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2386 [RHOAIENG-12693] Validate DSC Component Names and Versions
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0101__post_install.robot
Labels: lgtm

#2400 Updating Interop files for RHOAI 2.19 testing
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2388 Add Feature Store smoke tests
  ods_ci/tests/Resources/Page/FeatureStore/FeatureStore.resource
  ods_ci/tests/Tests/0700__feature_store/test-smoke.robot
Labels: lgtm

#2190 RHOAIENG-17979: feat(tests/ide): assert that "authorize access" oauth page is not present after RHOAIENG-11155 got into the product
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/Elyra.resource
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/JupyterHub/LoginJupyterHub.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0101__post_install.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0101__metrics.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0102__billing_metrics.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/autoscaling-gpus.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/image-iteration.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/long-running-test-generic-ds.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/networkpolicy-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/plugin-verification.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-flask-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-git-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-time.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-minimal-image.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-s3-cc-fraud.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test.robot
Labels: verified, enhancements, lgtm, jira/valid-reference

#2403 Fix for upgrade testing 2.16
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHModelServing.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm, approved

#2404 Fix model server upgrade testing 2.13
  ods_ci/tests/Resources/CLI/ModelServing/llm.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2405 fix MR UI tests, add RoleBinding due to RBAC bug fix
  ods_ci/tests/Resources/CLI/ModelRegistry/rolebinding_template.yaml
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/ModelRegistry/ModelRegistry.resource
  ods_ci/tests/Tests/1300__model_registry/1301_model_registry_model_serving.robot
Labels: verified, lgtm

#2406 fix MR UI tests, add RoleBinding due to RBAC bug fix (#2405)
  ods_ci/tests/Resources/CLI/ModelRegistry/rolebinding_template.yaml
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/ModelRegistry/ModelRegistry.resource
  ods_ci/tests/Tests/1300__model_registry/1301_model_registry_model_serving.robot
Labels: lgtm

#2409 RHOAIENG-13263: add new monitoring test case to check DSP Operator rules
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0101__metrics.robot
Labels: verified, jira/valid-reference

#2410 Update Feast Smoke Test Image Validation reference condition check for ROSA HCP clusters
  ods_ci/tests/Tests/0700__feature_store/test-smoke.robot
Labels: lgtm

#2411 Add AutomationBug to failing Momnitoring TCs
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0102__billing_metrics.robot
Labels: lgtm

#2413 DW: Update release tag for 2.19
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2414 Update training tests and images for different pytorch versions
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kft-sdk.robot
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-training-stack-tests.robot
Labels: lgtm

#2401 Use 4.16 catalog source for installing AMD Certified Operator on yet uncertified OCP versions
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
Labels: verified, lgtm

#2417 Fix DistributedWorkloads UI failures in 2.20
  ods_ci/tests/Resources/Page/DistributedWorkloads/WorkloadMetricsUI.resource
Labels: lgtm

#2420 fix: add automationbug tag to a monitoring case that takes 1h to finish
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
Labels: lgtm

#2421 Add missing Alerts Verifications
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
Labels: lgtm

#2423 Interop tests - update exclude args
  ods_ci/run_interop.sh
Labels: lgtm

#2416 Add Feature Store upgrade test
  ods_ci/tests/Resources/Page/FeatureStore/FeatureStore.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
  ods_ci/tests/Tests/0700__feature_store/test-run-feast-operator-e2e.robot
Labels: lgtm
