Repository red-hat-data-services/ods-ci, pull requests merged in 2025-02, with the labels that each got.

#2206 Update dry_run.yml upload artifact action from version v3 -> v4
  .github/workflows/dry_run.yml
Labels: lgtm

#2204 Migration of FIL Rest Protocol test on triton for Kserve (UI -> API)
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve_api.robot
Labels: lgtm

#2207 [2.16.0] Add image references to the Distributed Workload image digests
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0600__distributed_workloads/0601__workloads_orchestration/test-run-codeflare-sdk-e2e-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kuberay-e2e.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-distributed-workloads-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-distributed-workloads-tests_3.9.robot
Labels: lgtm

#2212 Update odh generic notebook images for RHOAI 2.17.0
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2211 Backport "Add option in ocm.py script to just check if the cluster exists #2196" in releases/2.13.0
  ods_ci/utils/scripts/ocm/ocm.py
Labels: lgtm

#2210 Backport "Add option in ocm.py script to just check if the cluster exists #2196" in releases/2.16.0
  ods_ci/utils/scripts/ocm/ocm.py
Labels: lgtm

#2209 Backport "Add option in ocm.py script to just check if the cluster exists #2196" in releases/2.8.0
  ods_ci/utils/scripts/ocm/ocm.py
Labels: lgtm

#2203 Backport "Replace AMD GPU community operator with RH certified one (#2134)" in releases/2.8.0
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_gpu_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/blacklist_driver.yaml
Labels: lgtm

#2202 Backport "Replace AMD GPU community operator with RH certified one (#2134)" in releases/2.13.0
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_gpu_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/blacklist_driver.yaml
Labels: lgtm

#2201 Backport "Replace AMD GPU community operator with RH certified one (#2134)" in releases/2.16.0
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_gpu_install.yaml
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/blacklist_driver.yaml
Labels: lgtm

#2215 post_upgrade: Add ExcludeOnDisconnected tag to the must-gather test
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm, approved

#2218 Set parameter as_user when creating projects for DSP (backport to 2.16)
  .github/workflows/dry_run.yml
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesUpgradeTesting.resource
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-acceptance.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1101__data-science-pipelines-kfp.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1102__data-science-pipelines-api.robot
  ods_ci/utils/scripts/ocm/ocm.py
Labels: verified, enhancements, lgtm

#2219 Fix dsp tests on interop 2.17 & fix variable conflict in Permissions provoking xpath issue
  ods_ci/tests/Resources/CLI/DataSciencePipelines/DataSciencePipelinesUpgradeTesting.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Permissions.resource
  ods_ci/tests/Tests/1100__data_science_pipelines/1100__data-science-pipelines-acceptance.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1101__data-science-pipelines-kfp.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1102__data-science-pipelines-api.robot
Labels: enhancements, lgtm

#2220 RHOAIENG-18519 - Add KFTO SDK test to downstream automation
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0600__distributed_workloads/0601__workloads_orchestration/test-run-kft-sdk.robot
Labels: lgtm

#2225 Fix DSP dashboard test for xpath changes introduced in RHOAI 2.17 (backport to releases/2.17.0)
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Pipelines.resource
Labels: verified, enhancements, lgtm

#2227 KubeRay: Sleep for 3 seconds after disabling Kueue
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kuberay-e2e.robot
Labels: lgtm

#2228 [2.17.0] KubeRay: Sleep for 3 seconds after disabling Kueue
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kuberay-e2e.robot
Labels: lgtm

#2229 Add new image for tgis and caikit tgis runtime for 2.18
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_grpc.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/caikit_tgis_servingruntime_http.yaml
  ods_ci/tests/Resources/Files/llm/serving_runtimes/tgis_servingruntime_grpc.yaml
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm.robot
Labels: verified, lgtm

#2230 Use OCP_API_URL parameter for Login To OCP function
  ods_ci/tests/Resources/Page/OCPLogin/OCPLogin.robot
Labels: lgtm

#2234 Add ProductBug Tag to Validate SMCP Already created and negative TC
  ods_ci/tests/Tests/2001__disruptive_tests/2002__dsc_negative_dependant_operators_not_installed.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: lgtm

#2235 Add ProductBug Tag to Validate SMCP Already created and negative TC
  ods_ci/tests/Tests/2001__disruptive_tests/2002__dsc_negative_dependant_operators_not_installed.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: lgtm

#2226 Fix Post Upgrade Test: Verify RHODS User Groups
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
Labels: verified, enhancements, lgtm

#2236 Add vllm image for 218
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_models.robot
Labels: verified, enhancements, lgtm

#2231 [2.17.x] Use OCP_API_URL parameter for Login To OCP function
  ods_ci/tests/Resources/Page/OCPLogin/OCPLogin.robot
Labels: lgtm

#2232 [2.16.x] Use OCP_API_URL parameter for Login To OCP function
  ods_ci/tests/Resources/Page/OCPLogin/OCPLogin.robot
Labels: lgtm

#2237 Update Ray and Training images with rocm 6.2.4 version
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2238 [2.17.0] enhancement: add new logic to support custom namespaces for both operator and applications
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tasks/Tasks/rhods_olm.robot
  ods_ci/tests/Resources/CLI/MustGather/MustGather.resource
  ods_ci/tests/Resources/CLI/MustGather/get-must-gather-logs.sh
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: lgtm

#2192 RHOAIENG-14731 - Run ValidatingAdmissionPolicy test downstream
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-distributed-workloads-tests.robot
Labels: lgtm

#1815 Added support env variables to run Codeflare and Codeflare-SDK tests …
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-codeflare-sdk-e2e-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-codeflare-tests.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-run-kueue-e2e-tests.robot
  ods_ci/utils/scripts/ocm/ocm.py
Labels: lgtm

#2233 Wait for Training operator Deployment to be available
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2241 Update Ray cluster upgrade tests to align with the latest UI changes
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2239 Update ods-ci branch name
  ods_ci/docs/release.md
  ods_ci/tests/Resources/Common.robot
  ods_ci/utils/scripts/fetch_tests.py
Labels: lgtm

#2243 Update KFTO tags for manual execution
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-training-stack-tests.robot
Labels: lgtm

#2213 Add RHOAI Upgrade Testing on OpenShift CI
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2248 Update Codeflare SDK release tag for 2.18 release
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration_compiled.yaml
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2252 add teams tag for upgrade tests
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2253 Backport: Fix locators on Verify RHODS Accept Multiple Admin Groups And CRD Get…
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
Labels: lgtm

#2251 Fix PreUpgrade testing return code to always return 0
  ods_ci/configs/templates/user_config.json
  ods_ci/run_interop.sh
Labels: lgtm
