Repository red-hat-data-services/ods-ci, pull requests merged in 2025-07, with the labels that each got.

#2523 [2.19] create different upgrade configmap for user groups to avoid co…
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: enhancements, lgtm

#2535 Backport tech preview features enablement for GCP provisioning in releases-2.21 branch
  ods_ci/tasks/Resources/Provisioning/Hive/GCP/gcp-cluster.yaml
Labels: lgtm

#2546 remove kueue operator stuff from master to make not available for 2.22
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: lgtm

#2548 Deprecate KFTO tests migrated to the shift left
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kft-sdk.robot
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-training-stack-tests.robot
Labels: lgtm

#2552 update the instructions on how to create an ods-ci release
  ods_ci/docs/release.md
Labels: lgtm

#2540 Kueue followup: including state transition tests
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/Components/Components.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: lgtm

#2556 2.22 - Update DW Release asset
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2557 RHOAIENG-26513: update test suite to use new rhoai-2.23 image naming convention with Python 3.11
  ods_ci/tests/Resources/Page/ModelRegistry/ModelRegistry.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects_additional.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects_edit.robot
  ods_ci/tests/Tests/0400__ods_dashboard/0410__ods_dashboard_projects/0410__ods_dashboard_projects_permissions_mgmt.robot
  ods_ci/tests/Tests/0500__ide/0502__ide_elyra.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_caikit_py_client.robot
  ods_ci/tests/Tests/1300__model_registry/1301_model_registry_model_serving.robot
  ods_ci/tests/Tests/2000__other_components/600__ai_apps/680__starburst/682__starburst_enterprise_sm.robot
Labels: verified, enhancements, lgtm, jira/valid-reference, tide/merge-method-squash

#2544 Add NFD CR image for 4.19
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/install_nfd.sh
Labels: verified, lgtm

#2534 Update Ray image references
  ods_ci/tests/Resources/Files/pipeline-samples/v1/ray_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration.py
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2561 Add Image Digest check for Feast instance Image verification test
  ods_ci/tests/Resources/Page/FeatureStore/FeatureStore.resource
Labels: lgtm

#2559 enhancement: add support for kueue and observability stuff in ods-ci
  ods_ci/tasks/Resources/Files/dsci_template.yml
  ods_ci/tasks/Resources/Files/dsci_template_raw.yml
  ods_ci/tasks/Resources/Files/monitoring-patch-payload.json
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: lgtm

#2570 [backport 2.23] enhancement: add support for kueue and observability stuff in ods-ci
  ods_ci/tasks/Resources/Files/dsci_template.yml
  ods_ci/tasks/Resources/Files/dsci_template_raw.yml
  ods_ci/tasks/Resources/Files/monitoring-patch-payload.json
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
Labels: lgtm

#2571 Make controller resources configuration test more stable
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: lgtm

#2573 enhancement: support deletion of cma dependent operator
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: lgtm

#2576 conf: update kuberay version to 1.4.0
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kuberay-e2e.robot
Labels: lgtm

#2574 Use full machineset CRD name when provisioning GPUs
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
  ods_ci/tasks/Resources/Provisioning/GPU/provision-gpu.sh
Labels: verified, lgtm

#2575 increase ROCm driver version + extend sleep for cs check
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
Labels: verified, lgtm

#2564 Backport "Add NFD CR image for 4.19 " to release-2.8
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/install_nfd.sh
Labels: lgtm

#2563 Backport "Add NFD CR image for 4.19 " to release-2.16
  ods_ci/tasks/Resources/Provisioning/GPU/NFD/install_nfd.sh
Labels: lgtm

#2566 Backport "Move to OCM post + add support for team label and fips" to release-2.8
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/ocm/templates/create-cluster.jinja
  ods_ci/utils/scripts/rosa/rosa.py
  ods_ci/utils/scripts/rosa/rosaOps.py
Labels: lgtm

#2578 Backport GPU provisioning patches to release-2.8
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
  ods_ci/tasks/Resources/Provisioning/GPU/provision-gpu.sh
Labels: lgtm

#2579 Backport GPU provisioning patches to release-2.16
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
  ods_ci/tasks/Resources/Provisioning/GPU/provision-gpu.sh
Labels: lgtm

#2580 Backport GPU provisioning patches to release-2.19
  ods_ci/tasks/Resources/Provisioning/GPU/AMD/amd_operator.sh
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
  ods_ci/tasks/Resources/Provisioning/GPU/provision-gpu.sh
Labels: lgtm

#2584 Omit image check for Unmanaged Kueue
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
Labels: lgtm
