Repository red-hat-data-services/ods-ci, pull requests merged in 2025-10, with the labels that each got.

#2659 fix: minor typo in the auth detection call
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: lgtm, approved

#2661 fix: add rolebinding setup/ teardown for distributed workloads tests
  ods_ci/tests/Resources/Files/kueue-batch-user-rolebinding.yaml
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2663 fix: add rolebinding setup/ teardown for distributed workloads tests
  ods_ci/tests/Resources/Files/kueue-batch-user-rolebinding.yaml
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2648 [2.19] chore(guidedTour): disable guided tour via CLI if possible
  ods_ci/tests/Resources/Page/LoginPage.robot
  ods_ci/tests/Resources/Page/OCPDashboard/OCPMenu.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
Labels: lgtm

#2647 [2.16] chore(guidedTour): disable guided tour via CLI if possible
  ods_ci/tests/Resources/Page/LoginPage.robot
  ods_ci/tests/Resources/Page/OCPDashboard/OCPMenu.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
Labels: lgtm

#2631 fix(upgrade ide): clean eventual existing Jupyter workbench before test
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
Labels: verified, enhancements, lgtm, approved

#2650 [2.22] chore(guidedTour): disable guided tour via CLI if possible
  ods_ci/tests/Resources/Page/LoginPage.robot
  ods_ci/tests/Resources/Page/OCPDashboard/OCPMenu.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
Labels: lgtm

#2675 update kueue channel to 1.1, as this version has ARM support
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: lgtm

#2677 fix wait for pods condition to make it more robust
  ods_ci/tests/Resources/OCP.resource
Labels: lgtm
