Repository red-hat-data-services/ods-ci, pull requests merged in 2025-06, with the labels that each got.

#2483 create different upgrade configmap for user groups to avoid collisions
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2487 fix: Remove wait for NFD in nvidia ns
  ods_ci/tasks/Resources/Provisioning/GPU/NVIDIA/gpu_deploy.sh
Labels: verified, lgtm

#2490 RHOAIENG-23490 - Create test to verify images used by RHOAI are corre…
  ods_ci/tests/Resources/Page/Components/Components.resource
Labels: lgtm

#2491 Adjust KFTO MNIST SDK test for env variable change
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kft-sdk.robot
Labels: lgtm

#2492 [2.20.0] Training operator upgrade - remove version limit
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2493 Training operator upgrade - remove version limit
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2450 Update multi-arch must-gather image
  ods_ci/tests/Resources/CLI/MustGather/get-must-gather-logs.sh
Labels: lgtm, needs-ok-to-test

#2499 Modify sample pipeline used for kfp test for compatibility with disconnected clusters
  ods_ci/tests/Tests/1100__data_science_pipelines/1101__data-science-pipelines-kfp.robot
Labels: verified, lgtm

#2501 fix: add hack to add the default groups in the auth cr
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Resources/RHOSi.resource
Labels: lgtm

#2496 conf: bump ray image sha to match latest version
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration_compiled.yaml
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Resources/Page/DistributedWorkloads/ray_cluster_cr.yaml
Labels: lgtm

#2478 Deprecate 'Verify Dashboard Is Shipped And Enabled Within ODS'
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0103__dashboard.robot
Labels: lgtm

#2507 enhancement: revert auth hack as the bug is not present anymore in devel
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: lgtm

#2509 Fix Auth CR expected values to be in array
  ods_ci/tests/Resources/ODS.robot
Labels: lgtm

#2513 Fix the check of the workbench size GiB vs Gi
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/notebook_size_verification.robot
Labels: verified, enhancements, lgtm

#2482 add support to install the Kueue operator if OCP >= 4.18
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
  ods_ci/tests/Resources/OCP.resource
Labels: verified, lgtm

#2520 Update notebook image to 2.22 digest
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2514 Add feast upgrade tests
  ods_ci/tests/Resources/Page/FeatureStore/FeatureStore.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
  ods_ci/tests/Tests/0700__feature_store/test-run-feast-operator-e2e.robot
Labels: lgtm

#2521 [2.21] Add feast upgrade tests
  ods_ci/tests/Resources/Page/FeatureStore/FeatureStore.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
  ods_ci/tests/Tests/0700__feature_store/test-run-feast-operator-e2e.robot
Labels: lgtm

#2516 Backport #2510 to release-2.19
  ods_ci/tasks/Resources/Provisioning/Hive/AWS/aws-cluster.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/AZURE/azure-cluster.yaml
  ods_ci/tasks/Resources/Provisioning/Hive/GCP/gcp-cluster.yaml
Labels: lgtm

#2519 RHOAIENG-13268:Add verification of deadmansnitch configuration
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0101__post_install.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0103__check_alertmanager_config.robot
Labels: lgtm, jira/valid-reference
