Repository red-hat-data-services/ods-ci, pull requests merged in 2025-09, with the labels that each got.

#2613 fix: add needed keyword for uninstall variables
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: lgtm

#2615 fix: minor fix about unknown output variable
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: lgtm

#2614 test: ray python 3.12
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kuberay-e2e.robot
Labels: lgtm

#2617 conf: unify timeout with the e2e source code
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2625 fix: incorrect string in the dashboard
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
  ods_ci/tests/Tests/0600__distributed_workloads/test-distributed-workloads-metrics-ui.robot
Labels: lgtm

#2626 fix ods-ci Upgrade stuff version comparison
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
Labels: lgtm

#2627 task(RHOAIENG-33492): Add CUDA 128 Ray image
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2634 add the upgrade option to our tests (#2518)
  ods_ci/tasks/Resources/RHODS_OLM/install/cs_template.yaml
  ods_ci/tasks/Resources/RHODS_OLM/install/install.robot
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Resources/RHODS_OLM/pre-tasks/oc_is_operator_installed.robot
  ods_ci/tasks/Tasks/rhods_olm.robot
  ods_ci/tests/Resources/Common.robot
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/Operators/ISVs.resource
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0107__kservewaw_rhoai_installation.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0202__during_upgrade.robot
  ods_ci/utils/scripts/ocm/ocm.py
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
  ods_ci/utils/scripts/testconfig/test-variables.yml
Labels: verified, lgtm

#2623 fix: update new monitoring payload for the dsci
  ods_ci/tasks/Resources/Files/monitoring-patch-payload.json
Labels: lgtm

#2607 fix servicemesh negative condition
  ods_ci/tests/Tests/2001__disruptive_tests/2002__dsc_negative_dependant_operators_not_installed.robot
Labels: do-not-merge/hold

#2639 Added deprecatedTests Tag to Model Serving Runtimes Testcases
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
  ods_ci/tests/Tests/1000__model_serving/1003__model_serving_customruntimes.robot
  ods_ci/tests/Tests/1000__model_serving/1005__model_serving_ovms_on_kserve.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_caikit_py_client.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_kserve_metrics.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_UI.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_other_runtimes_UI.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_tgis.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1008__model_serving_vllm/1008__model_serving_vllm_metrics.robot
  ods_ci/tests/Tests/1000__model_serving/1009__model_serving_triton_on_kserve/1009__model_serving_triton_on_kserve_api.robot
Labels: lgtm

#2646 Use correct Ray release asset for 2.16
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-kuberay-e2e.robot
Labels: lgtm
