Repository red-hat-data-services/ods-ci, pull requests merged in 2025-05, with the labels that each got.

#2425 RHOAIENG-12886 - ODS-2170: Verify Data Science Pipelines Application …
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Resources/Page/ODH/Prometheus/Prometheus.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
Labels: lgtm

#2430 Fix DSC Component version verification
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0101__post_install.robot
Labels: lgtm

#2431 [2.20] Fix DSC Component version verification
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0101__post_install.robot
Labels: lgtm

#2433 [2.20] Adjust Training images to latest ones
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2428 Workbenches fixes for RHOAI 2.21
  ods_ci/tests/Resources/Page/Components/Menu.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboardSettings.resource
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Workbenches.resource
Labels: verified, lgtm

#2434 post_install: Remove Tier1 and Monitoring tags from DeadManSnitch sce…
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0101__post_install.robot
Labels: lgtm

#2435 [2.20] post_install: Remove Tier1 and Monitoring tags from DeadManSnitch scenario
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0101__post_install.robot
Labels: lgtm

#2437 fix: use opendatahub as default ns for workbenches in odh
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: lgtm

#2438 fix: add new test to check pagerduty secret
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0101__post_install.robot
Labels: verified

#2440 Remove PyTorch 2.4.1 upgrade tests for Training component
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2441 [2.20] Remove PyTorch 2.4.1 upgrade tests for Training component
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2439 Add RHOAI startingCSV after installation
  ods_ci/tasks/Resources/RHODS_OLM/install/add_starting_csv.sh
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: verified, enhancements, lgtm

#2442 Backport "Add RHOAI startingCSV after RHOAI SM installation" to 2.19
  ods_ci/tasks/Resources/RHODS_OLM/install/add_starting_csv.sh
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: lgtm

#2278 Changed admin and allowed groups to lists and check post upgrade matc…
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2445 Get original value of defaultDeploymentMode from status
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0105__serverless_operator/0105__serverless_operator.robot
Labels: lgtm

#2448 [RHOAIENG-13262] Verify Data Science Pipelines Operator Alert
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
Labels: lgtm

#2451 [2.20] Fix DW release assets to the GitHub specific release
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2443 Refactor TensorBoard frame selection in JupyterHub tests
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-pytorch-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/minimal-tensorflow-test.robot
Labels: verified, enhancements, lgtm

#2453 Rename CodeFlare env variables to reflect midstream changes
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2446 [2.19] RHOSi.resource: Include rhaiseng domain as a selfmanaged cluster
  ods_ci/tests/Resources/RHOSi.resource
Labels: lgtm

#2456 rhods_operator_logs: Check return code for easier failure analysis
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0108__rhods_operator_logs_verification.robot
Labels: lgtm

#2460 Update Codeflare SDK release tag for 2.21 release
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration_compiled.yaml
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2461 Update interop testing related files
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2462 Update interop testing related files
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2466 Upgrade Ray images to version 2.44.1
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2467 Add debugging kws to randomly failig trusted ca bundles unmanaged tc
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0111__trusted_ca_bundles.robot
Labels: lgtm

#2470 Use latest Ray images in pipeline tests
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration_compiled.yaml
  ods_ci/tests/Resources/Page/DistributedWorkloads/ray_cluster_cr.yaml
Labels: lgtm

#2472 Rename the Jupyter tile in Dashboard enabled applications
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0101__post_install.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/jupyterhub-user-access.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/networkpolicy-test.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-flask-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-git-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-jupyterlab-notebook.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-minimal-image.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-s3-cc-fraud.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test.robot
Labels: verified, enhancements, lgtm

#2465 RHOAIENG-26136: Automatically clean dependent operators
  ods_ci/tasks/Resources/RHODS_OLM/uninstall/uninstall.robot
Labels: verified, lgtm, approved, jira/valid-reference

#2473 Rename the Workbench settings section in Dashboard
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDashboard.robot
Labels: verified, enhancements, lgtm

#2475 add whole gateway name to differentiate between the other gateway CR
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0105__serverless_operator/0105__serverless_operator.robot
Labels: lgtm

#2476 [2.19] add whole gateway name to differentiate between the other gateway CR
  ods_ci/tests/Resources/OCP.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0105__serverless_operator/0105__serverless_operator.robot
Labels: lgtm, approved

#2479 Update Feast release tag and new tests for 2.21 release
  ods_ci/tests/Resources/Page/FeatureStore/FeatureStore.resource
  ods_ci/tests/Tests/0700__feature_store/test-run-feast-operator-e2e.robot
Labels: lgtm
