Repository red-hat-data-services/ods-ci, pull requests merged in 2025-03, with the labels that each got.

#2255 RHOAIENG-20768: the Anaconda support was decided to be removed since RHOAI 2.18
  ods_ci/tests/Tests/0500__ide/0503__ide_anaconda_professional.robot
Labels: lgtm, jira/valid-reference

#2259 Upgrade fms-hf-tuning image to 2.6.0
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2258 Fix DSP UI test in RHOAI 2.18
  ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataSciencePipelines.resource
  ods_ci/tests/Tests/1100__data_science_pipelines/1110__test-run-data-science-pipelines-operator-e2e-tests.robot
Labels: verified, enhancements, lgtm

#2260 Adjust fms-hf-tuning tests to use Granite model
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-tuning-stack-tests.robot
Labels: lgtm

#2262 Adjust KFTO upgrade test to reflect upstream changes
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2263 Remove fms tests from QG GPU run
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-tuning-stack-tests.robot
Labels: lgtm

#2264 Freeze ODH DW release assets
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2268 Remove Tier1 tag from multinode singleGPU tests
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-run-training-stack-tests.robot
Labels: lgtm

#2269 make login to OCP console and ODH/RHOAI dashboard slightly more stable
  ods_ci/tests/Resources/Page/ODH/JupyterHub/LaunchJupyterHub.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test.robot
Labels: verified, enhancements, lgtm

#2271 fix the xpath for the Application launcher button in OCP4.18+
  ods_ci/tests/Resources/Page/OCPDashboard/OCPMenu.robot
Labels: verified, enhancements, lgtm

#2261 Add Smoke tests to Upgrade
  ods_ci/run_interop.sh
Labels: lgtm

#2266 enhancement: add new monitoring test to check RHOAI Metrics parameters
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0101__metrics/0101__metrics.robot
Labels: verified

#2270 Add NGC_API_KEY for executing NIM specific E2E Dashboard tests
  ods_ci/utils/scripts/testconfig/generateTestConfigFile.py
  ods_ci/utils/scripts/testconfig/test-variables.yml
Labels: lgtm, needs-ok-to-test

#2275 fix model registry teardown keywords failing if files/resources do not exist
  ods_ci/tests/Resources/Page/ModelRegistry/ModelRegistry.resource
  ods_ci/tests/Tests/1300__model_registry/1302_model_registry_smoke.robot
Labels: lgtm

#2257 Fix Dockerfile_interop env var usage
  ods_ci/build/Dockerfile_interop
Labels: lgtm

#2245 Add Interop files for release-2.10
  ods_ci/build/Dockerfile_interop
  ods_ci/configs/templates/user_config.json
  ods_ci/run_interop.sh
Labels: lgtm

#2246 Add Interop files for release-2.13
  ods_ci/build/Dockerfile_interop
  ods_ci/configs/templates/user_config.json
  ods_ci/run_interop.sh
Labels: lgtm

#2222 Update Verify RHODS User Groups Test Case to new Auth CRD
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm, approved

#2277 In DSP UI test, shorten project title if longer than 30 chars
  ods_ci/tests/Tests/1100__data_science_pipelines/1150__data-science-pipelines-ui.robot
Labels: verified, enhancements, lgtm

#2281 ModelRegistry: remove space in log level
  ods_ci/tests/Resources/Page/ModelRegistry/ModelRegistry.resource
Labels: lgtm

#2288 Add missing PATH for poetry in Dockerfile - Interop testing
  ods_ci/build/Dockerfile_interop
Labels: lgtm

#2290 Add missing PATH for poetry in Dockerfile - Interop testing
  ods_ci/build/Dockerfile_interop
Labels: lgtm

#2283 [2.16] Fix RayCluster upgrade tests permission issue for OCP
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2287 Add missing PATH for poetry in Dockerfile - Interop testing
  ods_ci/build/Dockerfile_interop
Labels: lgtm

#2292 Update Interop testing files
  ods_ci/build/Dockerfile_interop
  ods_ci/configs/templates/user_config.json
  ods_ci/run_interop.sh
Labels: lgtm

#2289 Add missing PATH for poetry in Dockerfile - Interop testing
  ods_ci/build/Dockerfile_interop
Labels: lgtm

#2294 Update Alert names on Verify Alerts Severity Test Case
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
Labels: lgtm

#2295 Install Authorino Stable when using ODH
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: lgtm

#2296 Backport Update Alert names on Verify Alerts Severity Test Case
  ods_ci/tests/Tests/0100__platform/0102__monitor_and_manage/0102__alerts/0102__alerts.robot
Labels: lgtm

#2293 fix: adapt disruptive tests to ODH/RHOAI 2.19
  ods_ci/tasks/Resources/Files/dsc_template.yml
  ods_ci/tasks/Resources/Files/dsci_template.yml
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tasks/Tasks/rhods_olm.robot
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Resources/RHOSi.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0104__rhods_operator/0113__dsc_components.robot
  ods_ci/tests/Tests/0100__platform/0101__deploy/0104__operators/0105__serverless_operator/0105__serverless_operator.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2002__dsc_negative_dependant_operators_not_installed.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: verified, lgtm

#2300 don't check for webhook pod when installing Authorino from stable channel
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: lgtm

#2301 Add fix for poetry path
  ods_ci/build/Dockerfile_interop
Labels: lgtm

#2303 fix the jupyter workbench start for RHOAI 2.19+
  ods_ci/tests/Resources/Page/ODH/JupyterHub/JupyterHubSpawner.robot
  ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test.robot
Labels: verified, enhancements, lgtm, approved

#2307 Update DW UI tests to align with the 2.19 release Dashboard changes
  ods_ci/tests/Resources/Page/DistributedWorkloads/WorkloadMetricsUI.resource
  ods_ci/tests/Tests/0600__distributed_workloads/test-distributed-workloads-metrics-ui.robot
Labels: lgtm

#2306 Adjust tests for Training operator GA
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
  ods_ci/tests/Tests/0100__platform/0101__deploy/0101__installation/0113__installation.robot
  ods_ci/tests/Tests/0600__distributed_workloads/0602__training/test-smoke.robot
Labels: lgtm

#2308 split ENV in dockerfile for poetry path
  ods_ci/build/Dockerfile_interop
Labels: lgtm

#2309 Run KFTO upgrade tests for RHOAI 2.19 onwards
  ods_ci/tests/Tests/0200__rhoai_upgrade/0201__pre_upgrade.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
Labels: lgtm

#2312 Modify DSP backend tests not to use the UI to assign user permissions to projects
  ods_ci/tests/Resources/ODS.robot
  ods_ci/tests/Tests/0200__rhoai_upgrade/0203__post_upgrade.robot
  ods_ci/tests/Tests/0600__distributed_workloads/0601__workloads_orchestration/test-pipelines-integration.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1101__data-science-pipelines-kfp.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1102__data-science-pipelines-api.robot
  ods_ci/tests/Tests/1100__data_science_pipelines/1103__data-science-pipelines-project-sharing.robot
Labels: verified, enhancements, lgtm

#2313 fix: delete auth when deleting dsci
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2002__dsc_negative_dependant_operators_not_installed.robot
Labels: verified, lgtm

#2302 bump poetry to 2.1.1 version including deprecation warn fix
  .github/workflows/code_quality.yaml
  ods_ci/run_robot_test.sh
  poetry.lock
  pyproject.toml
Labels: utils, lgtm

#2280 Create DSCI and DSC for Kserve raw deployment in ODS-CI
  ods_ci/tasks/Resources/Files/dsc_template_raw.yml
  ods_ci/tasks/Resources/Files/dsci_template_raw.yml
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: lgtm

#2315 Handle if KSERVE_RAW_DEPLOYMENT is unset
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
Labels: lgtm

#2314 Use latest fms-hf-tuning image - 2.7.1
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2305 Add deprecatedTest tag to model server tests
  ods_ci/tests/Tests/1000__model_serving/1001__model_serving_modelmesh.robot
  ods_ci/tests/Tests/1000__model_serving/1005__model_serving_ovms_on_kserve.robot
  ods_ci/tests/Tests/1000__model_serving/1006__model_serving_ovms_on_kserve_cli.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_caikit_embeddings.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_UI.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_other_runtimes_UI.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_tgis.robot
  ods_ci/tests/Tests/1000__model_serving/1009_model_serving_test_oci_image.robot
Labels: lgtm, approved

#2320 Use latest CUDA training image
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2322 cherry-pick: Add deprecatedTest tag to model server tests
  ods_ci/tests/Tests/1000__model_serving/1001__model_serving_modelmesh.robot
  ods_ci/tests/Tests/1000__model_serving/1005__model_serving_ovms_on_kserve.robot
  ods_ci/tests/Tests/1000__model_serving/1006__model_serving_ovms_on_kserve_cli.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_caikit_embeddings.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_UI.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_other_runtimes_UI.robot
  ods_ci/tests/Tests/1000__model_serving/1007__model_serving_llm/1007__model_serving_llm_tgis.robot
  ods_ci/tests/Tests/1000__model_serving/1009_model_serving_test_oci_image.robot
Labels: lgtm, approved

#2326 Fix interop test variables 2.8
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2328 Fix interop test variables 2.13
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2329 Fix interop test variables 2.16
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2330 Fix interop test variables 2.18
  ods_ci/build/Dockerfile_interop
  ods_ci/run_interop.sh
Labels: lgtm

#2331 Update Codeflare SDK release tag for 2.19 release
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_integration_compiled.yaml
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration.py
  ods_ci/tests/Resources/Files/pipeline-samples/v2/cache-disabled/ray_job_integration_compiled.yaml
  ods_ci/tests/Resources/Page/DistributedWorkloads/DistributedWorkloads.resource
Labels: lgtm

#2339 fix: add v3 sarif version because v2 is now deprecated
  .github/workflows/code_quality.yaml
Labels: verified, lgtm

#2341 fix: add v3 sarif version because v2 is now deprecated
  .github/workflows/code_quality.yaml
Labels: lgtm

#2338 fix: add minor fixes to make the scmp test work
  ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: lgtm

#2340 fix: add v3 sarif version because v2 is now deprecated
  .github/workflows/code_quality.yaml
Labels: lgtm

#2344 fix: add v3 sarif version because v2 is now deprecated
  .github/workflows/code_quality.yaml
Labels: lgtm

#2345 fix: add v3 sarif version because v2 is now deprecated
  .github/workflows/code_quality.yaml
Labels: lgtm

#2343 Add AutomationBug Tag to SMCP Already created TC
  ods_ci/tests/Tests/2001__disruptive_tests/2003__smcp_already_created.robot
Labels: lgtm
